### ISSUE TITLE
Gluster S3 install fails with 'item' is undefined

### ISSUE THREAD

**Issue by j00p34** [openshift/openshift-ansible#10219]
#### Description

TASK [Copy gluster-s3 PVCs template file] fails consistently with message 'item' is undefined

##### Version

```
Using origin-ansible installer container image (latest)
```

##### Steps To Reproduce
Use origin-ansible installer to install and 
set openshift_storage_glusterfs_s3_deploy=True

##### Expected Results
Installation succeeds

##### Observed Results

   Play:     Configure GlusterFS
     Task:     Copy gluster-s3 PVCs template file
     Message:  The task includes an option with an undefined variable. The error was: 'item' is undefined
               
               The error appears to have been in '/usr/share/ansible/openshift-ansible/roles/openshift_storage_glusterfs/tasks/gluster_s3_deploy.yml': line 47, column 3, but may
               be elsewhere in the file depending on the exact syntax problem.
               
               The offending line appears to be:
               
               
               - name: Copy gluster-s3 PVCs template file
                 ^ here

```
same problem seems to occur in two separate tasks in the same file ( line 47 and 88 ) : 

- name: Copy gluster-s3 template file
  copy:
    src: "gluster-s3-template.yml"
    dest: "{{ mktemp.stdout }}/{{ item }}"
```
