### ISSUE TITLE
Issue deploying VMs on oVirt using xip.io as a openshift_ovirt_dns_zone

### ISSUE THREAD

**Issue by jparrill** [openshift/openshift-ansible#10415]
#### Description

Because of a race condition problem with **xip.io** or **nip.io** domains and openshift-ovirt module, I cannot provision a VM with a defined and correct IP. I will explain this problem: 

The problem are in the VM naming, by default when you provision a VM, the name assigned are based on a dict variable openshift_ovirt_vm_manifest['name'], this variable will be not the final name, this is an example of definition:

```
openshift_ovirt_dns_zone: 'xip.io'
openshift_ovirt_vm_manifest:
- name: 'master'
  count: 1
  profile: 'master_vm'
  nic_mode:
      master0:
        nic_ip_address: '10.19.138.1'
        nic_netmask: '255.255.248.0'
        nic_gateway: '10.19.143.254'
        dns_servers: '10.19.138.10'
        dns_search: "{{ openshift_ovirt_dns_zone }}"
```
This example will provision a node called **master0.xip.io** but this doesn`t resolv, to work with xip.io you need to include the IP on the hostname. If you try to use this with xip.io, the translation will be something like:

```
openshift_ovirt_dns_zone: 'xip.io'
openshift_ovirt_vm_manifest:
- name: '10.19.138.1'
  count: 1
  profile: 'master_vm'
  nic_mode:
      10.19.138.10:  <<<<<<<------ HERE IS THE PROBLEM
        nic_ip_address: '10.19.138.1'
        nic_netmask: '255.255.248.0'
        nic_gateway: '10.19.143.254'
        dns_servers: '10.19.138.10'
        dns_search: "{{ openshift_ovirt_dns_zone }}"
```
And the resultant name will be **10.19.138.10.xip.io** instead of **10.19.138.1.xip.io** because of how the role manage the counter.

##### Version

```
ansible 2.6.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
* Your ansible version per `ansible --version`
```

Place the output between the code block below:
```
openshift-ansible-3.11.23-1
```

But is the same for older ones

##### Steps To Reproduce
1. Use the VM definition on provision-variables like the example provided
2. Use this command to execute the playbook 
  `ansible-playbook -i downstream/inventory -e @downstream/provisioning-vars.yaml openshift-cluster/ovirt-vm-infra.yml`

##### Expected Results

VM name and vm Hostname matches with the correct and expected IP: **10.19.138.1.xip.io**

##### Observed Results

VM name and VM hostname: **10.19.138.10.xip.io** meanwhile the node IP is **10.19.138.1**

##### Additional Information

This is a race condition of create more than one node with this role, with just a couple of tweaks on the j2 file, will be fixed.
