### ISSUE TITLE
K8s : not update deployment.yml in openshift

### ISSUE THREAD

**Issue by qasmi** [openshift/openshift-ansible#10518]
I use k8s ansible module to deploy, my ansible role is :

```
- name: Create OpenShift resource
  k8s:
    host: "{{ inventory_hostname }}"
    api_key: "{{ namespace_token }}"
    verify_ssl: false
    state: present
    src: "{{ openshift_template }}"
    name : "{{ openshift_resource }}"
    namespace: "{{ openshift_namespace }}"
```

```
ansible version : 2.6.2
```
By executing the ansible playbook I get  :

`localhost                  : ok=2    changed=0    unreachable=0    failed=0  `
```
- hosts: localhost
  connection: local
  roles:
    - role: openshift_deployment
  vars_files:
    - inventories/qa/group_vars/hub-openshift-deployment.yaml
```

But my deplyment.yml has not been modified in openshift, amy idea please ?
