### ISSUE TITLE
Building a primed AMI failed on running subscription manager

### ISSUE THREAD

**Issue by literalice** [openshift/openshift-ansible#10525]
#### Description

On creating a primed AMI for cluster scaling according to [the document](https://docs.openshift.com/container-platform/3.11/admin_guide/cluster-autoscaler.html#creating-primed-image-cluster-auto-scaler-cluster-auto-scaler) , the process failed with some error messages.

##### Version

* Your ansible version per `ansible --version`

```
ansible 2.6.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

* The output of `rpm -q openshift-ansible`

```
openshift-ansible-3.11.16-1.git.0.4ac6f81.el7.noarch
```

##### Steps To Reproduce
1. Create a new Ansible inventory file on your local host:

```
[OSEv3:vars]
openshift_deployment_type=openshift-enterprise
ansible_ssh_user=ec2-user
openshift_clusterid=mycluster
ansible_become=yes

[masters]
[etcd]
[nodes]
```

2. Create provisioning file, build-ami-provisioning-vars.yaml, on your local host:

```
openshift_clusterid: mycluster
openshift_aws_create_vpc: false
openshift_aws_region: ap-northeast-1
openshift_aws_vpc_name: mycluster
openshift_aws_subnet_az: ap-northeast-1a
openshift_aws_create_security_groups: false
openshift_aws_ssh_key_name: mycluster
openshift_aws_base_ami: ami-xx
openshift_aws_create_s3: false
openshift_aws_build_ami_group: primed-ami
container_runtime_docker_storage_type: overlay2
container_runtime_docker_storage_setup_device: /dev/xvdb
openshift_aws_vpc:
  name: "{{ openshift_aws_vpc_name }}"
  cidr: 10.0.0.0/16
  subnets:
    ap-northeast-1:
    - cidr: 10.0.128.0/20
      az: ap-northeast-1a
openshift_aws_ami_build_set_gquota_on_slashfs: true
ansible_ssh_user: ec2-user
openshift_use_crio: true
openshift_use_crio_only: true
openshift_node_group_name: node-config-compute-crio
openshift_crio_enable_docker_gc: true
rhsub_user: "xxx"
rhsub_pass: "xxx"
rhsub_pool: "xxx"
```

3. run that command:

```
ansible-playbook -i ~/primed-ami-inventory /usr/share/ansible/openshift-ansible/playbooks/aws/openshift-cluster/build_ami.yml -e @build-ami-provisioning-vars.yaml -vvv | tee ansible-$(date +%Y%m%d%H%M%S)-build_ami.log
```

##### Expected Results
Creating a AMI should be successful.

##### Observed Results
Creating a AMI failed with the message.

```
TASK [rhel_subscribe : Is host already registered?] ************************************************************************************************
task path: /usr/share/ansible/openshift-ansible/roles/rhel_subscribe/tasks/main.yml:13
Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
<ec2-52-194-186-252.ap-northeast-1.compute.amazonaws.com> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<ec2-52-194-186-252.ap-northeast-1.compute.amazonaws.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 -o ControlPath=/home/ec2-user/.ansible/cp/f28236325e ec2-52-194-186-252.ap-northeast-1.compute.amazonaws.com '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<ec2-52-194-186-252.ap-northeast-1.compute.amazonaws.com> (1, '\n{"changed": true, "end": "2018-10-26 02:18:05.167808", "stdout": "", "cmd": ["subscription-manager", "version"], "failed": true, "delta": "0:00:06.087266", "stderr": "The password you typed is invalid.\\nPlease try again.", "rc": 1, "invocation": {"module_args": {"warn": true, "executable": null, "_uses_shell": false, "_raw_params": "subscription-manager version", "removes": null, "argv": null, "creates": null, "chdir": null, "stdin": null}}, "start": "2018-10-26 02:17:59.080542", "msg": "non-zero return code"}\n', '')
fatal: [ec2-52-194-186-252.ap-northeast-1.compute.amazonaws.com]: FAILED! => {
    "changed": false, 
    "cmd": [
        "subscription-manager", 
        "version"
    ], 
    "delta": "0:00:06.087266", 
    "end": "2018-10-26 02:18:05.167808", 
    "invocation": {
        "module_args": {
            "_raw_params": "subscription-manager version", 
            "_uses_shell": false, 
            "argv": null, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": true
        }
    }, 
    "msg": "non-zero return code", 
    "rc": 1, 
    "start": "2018-10-26 02:17:59.080542", 
    "stderr": "The password you typed is invalid.\nPlease try again.", 
    "stderr_lines": [
        "The password you typed is invalid.", 
        "Please try again."
    ], 
    "stdout": "", 
    "stdout_lines": []
}
 [WARNING]: Could not create retry file '/usr/share/ansible/openshift-ansible/playbooks/aws/openshift-cluster/build_ami.retry'.         [Errno 13]
Permission denied: u'/usr/share/ansible/openshift-ansible/playbooks/aws/openshift-cluster/build_ami.retry'

PLAY RECAP *****************************************************************************************************************************************
ec2-52-194-186-252.ap-northeast-1.compute.amazonaws.com : ok=22   changed=0    unreachable=0    failed=1   
localhost                  : ok=13   changed=1    unreachable=0    failed=0   


INSTALLER STATUS ***********************************************************************************************************************************
Initialization  : In Progress (0:00:11)
```

##### Additional Information

* Red Hat Enterprise Linux Server release 7.5 (Maipo)
