### ISSUE TITLE
Ansible Inventory multi line configuation

### ISSUE THREAD

**Issue by Reamer** [openshift/openshift-ansible#10582]
#### Description

Hi,
I doesn't find any example how to add a multi line configuration in ansible inventory.
How to add a multi line configuration for `openshift_cluster_monitoring_operator_alertmanager_config`?

##### Version

* ansible version
```
ansible 2.6.7
  config file = /home/pdallig/git/openshift-ansible-3-11/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```
* The output of `git describe`
```
openshift-ansible-3.11.38-1
```

##### Expected Results
Add a multi line configuration for alertmanager, with `openshift_cluster_monitoring_operator_alertmanager_config`

**Comment by vrutkovs** [comment]
Not sure what's the issue here, default config is multiline anyway

**Comment by Reamer** [comment]
Hi @vrutkovs,
thanks for your fast response. I want to overwrite the default config with my ansible inventory which based on the example playbooks (https://github.com/openshift/openshift-ansible/blob/master/inventory/hosts.example)

**Comment by vrutkovs** [comment]
You should use YAML-style for any complex group variables, see https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#group-variables

**Comment by zoobab** [comment]
@Klaas maybe try a syntax similar to:

openshift_cloudprovider_aws_secret_key="\{\{ lookup('env','AWS_SECRET_ACCESS_KEY') \}\}"

I am trying on my side and coming back to you if it works for me...

**Comment by Klaas-** [comment]
the file lookup I think, if you want to put it into the inventory file you need to do something like this:
```
openshift_cluster_monitoring_operator_alertmanager_config: |+
  global:
    resolve_timeout: 5m
    smtp_from: "alert_from@example.com"
    smtp_smarthost: "smtp.gmail.com:587"
    smtp_auth_username: "gmail_user@example.com"
    smtp_auth_password: "<Gmail_Auth_Token>"
  route:
    group_wait: 30s
[...]
```
