### ISSUE TITLE
misleading message from glusterfs new_install playbook upon failure

### ISSUE THREAD

**Issue by obnoxxx** [openshift/openshift-ansible#10592]
#### Description

When the glusterfs install fails (in my case it timed out waiting for the gluster-block-provisioner pod to come up), then it issues a message that suggests running the `playbooks/openshift-glusterfs/new_install.yml` playbook to restart, but this playbook does not exist. (Instead, `playbooks/openshift-glusterfs/private/new_install.yml` exists.)

##### Version

```
# ansible --version
ansible 2.6.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

# rpm -q openshift-ansible
openshift-ansible-3.11.36-1.git.0.2213c76.el7.noarch
```

##### Steps To Reproduce

1. Run openshift-ansible with gluster deployment configured, including gluster-block.
2. When the glusterfs install fails for some reason (in my case it timed out waiting for the gluster-block-provisioner pod to come up), then it issues a message that suggests running the `playbooks/openshift-glusterfs/new_install.yml` playbook to restart, but this playbook does not exist. (Instead, `playbooks/openshift-glusterfs/private/new_install.yml` exists.)

```
...
INSTALLER STATUS ***************************************************************
Initialization              : Complete (0:00:31)
Health Check                : Complete (0:00:06)
Node Bootstrap Preparation  : Complete (0:07:09)
etcd Install                : Complete (0:00:55)
Master Install              : Complete (0:05:10)
Master Additional Install   : Complete (0:00:41)
Node Join                   : Complete (0:00:22)
GlusterFS Install           : In Progress (0:12:25)
        This phase can be restarted by running: playbooks/openshift-glusterfs/new_install.yml
...
```

##### Expected Results

Get a message that points to a playbook that actually exists.

##### Observed Results

Message listed playbook that does not exist:

```
This phase can be restarted by running: playbooks/openshift-glusterfs/new_install.yml
```

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version: RHEL 7.5
* Your inventory file (especially any non-standard configuration parameters)

**Comment by obnoxxx** [comment]
Some analysis:

The only reference to this non-existent file came from the playbook itself in
https://github.com/openshift/openshift-ansible/blob/master/playbooks/openshift-glusterfs/private/new_install.yml#L15

```
...
- name: GlusterFS Install Checkpoint Start
  hosts: all
  gather_facts: false
  tasks:
  - name: Set GlusterFS install 'In Progress'
    run_once: true
    set_stats:
      data:
        installer_phase_glusterfs:
          title: "GlusterFS Install"
          playbook: "playbooks/openshift-glusterfs/new_install.yml"
          status: "In Progress"
          start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
...
```

So a fix could be one of:
* fix this line to include `private/` before `new_install.yml`
* include a new playbook in `playbooks/openshift-glusterfs/new_install.yml` that imports this private one.

Happy to provide a fix myself, just want to get guidance what would be the correct way to do it.
