### ISSUE TITLE
Unable to complete installation with OIDC IdP

### ISSUE THREAD

**Issue by ricfeatherstone** [openshift/openshift-ansible#10602]
#### Description

Using the following IdP provider configuration I have previously been able to install v3.9. When I now try to a fresh installation of 3.11 it fails when trying to bring up the control plane.

```
openshift_master_identity_providers=[{"name": "oidc","login": "true","challenge": "false","kind": "OpenIDIdentityProvider","client_id": “REDACTED”,”client_secret": "REDACTED",claims": {"id": ["sub"],"preferredUsername": ["preferred_username","email"],"name": ["name","email"],"email": ["email"]},"urls": {"authorize": “REDACTED”,”token": “REDACTED”,”userInfo": "REDACTED"}}]
```

Docker logs for k8s_api_master-api-ip-xxx.eu-west-1.compute.internal_kube-system_c5135e8736a35a2f4d20ac7bcba88340_6

```
Invalid MasterConfig /etc/origin/master/master-config.yaml
  oauthConfig.identityProvider[0].provider.ca: Invalid value: "/etc/origin/master/oidc_openid_ca.crt": could not read file: stat /etc/origin/master/oidc_openid_ca.crt: no such file or directory
```

I've tracked this down to the following `ca` entry being added to the `oathConfig` section in `/etc/origin/master/master-config.yaml` that was not previously being added.

```
oauthConfig:
  identityProviders:
  - challenge: false
    login: true
    mappingMethod: claim
    name: oidc
    provider:
      apiVersion: v1
      ca: /etc/origin/master/oidc_openid_ca.crt
      claims:
        email:
        - email
        id:
        - sub
        name:
        - name
        - email
        preferredUsername:
        - preferred_username
        - email
      clientID: REDACTED
      clientSecret: REDACTED
      kind: OpenIDIdentityProvider
      urls:
        authorize: REDACTED
        token: REDACTED
        userInfo: REDACTED
```

Looking at the [docs](https://docs.okd.io/3.11/install_config/configuring_authentication.html#OpenID)
this ca should be optional and use system ca if not provided.

Is this a regression or is there a way to format `openshift_master_identity_providers` to prevent this field being added?

##### Version

```
$ ansible --version
ansible 2.6.4
  config file = /home/centos/openshift-ansible/ansible.cfg
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/centos/.local/lib/python2.7/site-packages/ansible
  executable location = /home/centos/.local/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

$ git describe
openshift-ansible-3.11.39-1
```

##### Expected Results

Expect installation to complete and OIDC Provider to be configured correctly and use system cas as per previous versions

##### Observed Results

Installation fails
