### ISSUE TITLE
Etcd scaleup for collocated master nodes fails due to undefined openshift_is_atomic variable

### ISSUE THREAD

**Issue by mandre** [openshift/openshift-ansible#10682]
#### Description

While trying to automate the etcd collocated master node scale up, it fails on undefined openshift_is_atomic variable.

```
TASK [fail] ********************************************************************
fatal: [openshift-openshiftmaster-0]: FAILED! => {"msg": "The conditional check 'openshift_is_atomic | bool' failed. The error was: error while evaluating conditional (openshift_is_atomic | bool): 'openshift_is_atomic' is undefined\n\nThe error appears to have been in '/usr/share/ansible/openshift-ansible/playbooks/openshift-etcd/private/scaleup.yml': line 6, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n  - fail:\n    ^ here\n"}
```

I'm using ansible to call openshift-ansible twice. Once for the master nodes scale up, and a second time for the etcd nodes scale up.

The second time, the logs show that is skips [setting the openshift_is_atomic fact](https://github.com/openshift/openshift-ansible/blob/release-3.11/playbooks/init/basic_facts.yml#L35-L37) on the existing master nodes, which is really odd since there is no `when` clause.

```
TASK [initialize_facts set fact openshift_is_atomic] ***************************
skipping: [openshift-openshiftmaster-0]
ok: [openshift-openshiftmaster-1]
```

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

I'm using ansible to call a containerized openshift-ansible. The outside ansible version is:
```
  ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/mistral/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

The OSA container image ansible version is:
```
  ansible 2.6.7
  config file = /usr/share/ansible/openshift-ansible/ansible.cfg
  configured module search path = [u'/opt/app-root/src/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
openshift-ansible-3.11.42-1.git.0.6a1fb8e.el7.noarch, in the ose-ansible:v3.11 container image.
```

##### Steps To Reproduce

The ansible playbook I'm using goes more or less like this:

```
- name: generate openshift master scaleup playbook
  copy:
    dest: "{{playbook_dir}}/openshift/playbook.yml"
    content: |
      - include: "/usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml"
      - include: "/usr/share/ansible/openshift-ansible/playbooks/openshift-master/scaleup.yml"
      - include: "/usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml"

- name: set openshift command
  set_fact:
    openshift_command: >-
      docker run \
          -v {{playbook_dir}}:{{playbook_dir}} \
          -w {{playbook_dir}} \
          -e ANSIBLE_HOST_KEY_CHECKING=False \
          -e ANSIBLE_CONFIG=ansible.cfg \
          -e INVENTORY_DIR=openshift/inventory \
          -e PLAYBOOK_FILE=openshift/playbook.yml \
          -t registry.reg-aws.openshift.com:443/openshift3/ose-ansible:v3.11

# Run osa a first time for master node scale up
# Full log in playbook.log file.
- name: run openshift for master scale up
  shell: |
    {{openshift_command}} 2>&1 | tee playbook.log
    exit ${PIPESTATUS[0]}

# Add openshift-openshiftmaster-1 to the new_etcd group
- name: generate additional openshift inventory for new_etcd group
  copy:
    dest: "{{playbook_dir}}/openshift/inventory/new_etcd_groups.yml"
    content: |
      all:
        children:
          new_etcd:
            children:
              new_masters: {}

- name: generate openshift etcd scaleup playbook
  copy:
    dest: "{{playbook_dir}}/openshift/playbook.yml"
    content: |
      - include: "/usr/share/ansible/openshift-ansible/playbooks/openshift-etcd/scaleup.yml"

# Run OSA a second time for etcd scale up
# Full log in playbook-etcd.log file.
# This is the one that fails over undefined variable openshift_is_atomic for openshift-openshiftmaster-0
- name: run etcd node scale up
  shell: |
    {{openshift_command}} 2>&1 | tee playbook-etcd.log
    exit ${PIPESTATUS[0]}
```

##### Expected Results
Etcd scale up playbook to complete successfully.

##### Observed Results
Etcd scale up playbook fails on undefined `openshift_is_atomic` variable.

```
TASK [initialize_facts set fact openshift_is_atomic] ***************************
skipping: [openshift-openshiftmaster-0]
ok: [openshift-openshiftmaster-1]

[snip]

PLAY [Check for etcd stand-alone hosts on atomic] ******************************

TASK [Gathering Facts] *********************************************************
ok: [openshift-openshiftmaster-0]

TASK [fail] ********************************************************************
fatal: [openshift-openshiftmaster-0]: FAILED! => {"msg": "The conditional check 'openshift_is_atomic | bool' failed. The error was: error while evaluating conditional (openshift_is_atomic | bool): 'openshift_is_atomic' is undefined\n\nThe error appears to have been in '/usr/share/ansible/openshift-ansible/playbooks/openshift-etcd/private/scaleup.yml': line 6, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n  - fail:\n    ^ here\n"}
```

##### Additional Information

[inventory.gz](https://github.com/openshift/openshift-ansible/files/2576905/inventory.gz)
[logs.gz](https://github.com/openshift/openshift-ansible/files/2576906/logs.gz)
