### ISSUE TITLE
openshift_cockpit_deployer_version not honored

### ISSUE THREAD

**Issue by jaymccon** [openshift/openshift-ansible#10700]
#### Description

setting `openshift_cockpit_deployer_version` in the ansible hosts file has no effect.

The 3.10 release is trying to fetch `registry.access.redhat.com/openshift3/registry-console:v3.10.66` which (at the time of writing) [does not exist in the repo](https://access.redhat.com/containers/?tab=tags#/registry.access.redhat.com/openshift3/registry-console), so `docker_image_availability` check fails when running deploy_cluster playbook. Setting `openshift_cockpit_deployer_version` has no effect and the check still fails pointing to the `v3.10.66` tag.

Setting `openshift_cockpit_deployer_image='registry.access.redhat.com/openshift3/registry-console:v3.10' works though, but is undocumented from what I can see.

##### Version

```
ansible 2.4.6.0
downloaded release 3.10.76-1 from github
```

##### Steps To Reproduce
1. run `deploy_cluster.yml` playbook with hosted registry enabled, it should fail when checking image availability, reporting the image checked was tagged `v3.10.66`
2. set `openshift_cockpit_deployer_version='3.10'`
3.  re-run deploy playbook, should fail with same error, pointing to same `v3.10.66` image tag.

##### Expected Results
When setting `openshift_cockpit_deployer_version='3.10'` the checks (and subsequent install steps) should use the image tagged `v3.10`

##### Observed Results
Describe what is actually happening.

```
ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml

...

2018-11-14 20:40:09,722 p=14386 u=root |  	This phase can be restarted by running: playbooks/openshift-checks/pre-install.yml
2018-11-14 20:40:09,723 p=14386 u=root |  Failure summary:


  1. Hosts:    xxx, yyy, zzz
     Play:     OpenShift Health Checks
     Task:     Run health checks (install) - EL
     Message:  One or more checks failed
     Details:  check "docker_image_availability":
               One or more required container images are not available:
                   registry.access.redhat.com/openshift3/registry-console:v3.10.66
               Checked with: skopeo inspect [--tls-verify=false] [--creds=<user>:<pass>] docker://<registry>/<image>


The execution of "/usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml" includes checks designed to fail early if the requirements of the playbook are not met. One or more of these checks failed. To disregard these results,explicitly disable checks by setting an Ansible variable:
   openshift_disable_check=docker_image_availability
Failing check names are shown in the failure details above. Some checks may be configurable by variables if your requirements are different from the defaults; consult check documentation.
Variables can be set in the inventory or passed on the command line using the -e flag to ansible-playbook.
```

##### Additional Information

ansible hosts file:
```
OSEv3:
  children:
    etcd:
      hosts:
        <REDACTED>
    masters:
      hosts:
        <REDACTED>
    nodes:
      hosts:
        <REDACTED>
  vars:
    ansible_ssh_user: root
    containerized: 'false'
    openshift_clock_enabled: 'true'
    openshift_cloudprovider_kind: aws
    openshift_clusterid: owned
    openshift_deployment_type: openshift-enterprise
    openshift_examples_modify_imagestreams: 'true'
    openshift_hosted_registry_acceptschema2: 'true'
    openshift_hosted_registry_enforcequota: 'true'
    openshift_hosted_registry_pullthrough: 'true'
    openshift_hosted_registry_storage_kind: object
    openshift_hosted_registry_storage_provider: s3
    openshift_hosted_registry_storage_s3_bucket: <REDACTED>
    openshift_hosted_registry_storage_s3_chunksize: 26214400
    openshift_hosted_registry_storage_s3_region: <REDACTED>
    openshift_hosted_registry_storage_s3_rootdirectory: /registry
    openshift_master_api_port: '443'
    openshift_master_cluster_hostname: <REDACTED>
    openshift_master_cluster_method: native
    openshift_master_cluster_public_hostname: <REDACTED>
    openshift_master_console_port: '443'
    openshift_master_default_subdomain: <REDACTED>
    openshift_master_identity_providers:
    - challenge: 'true'
      kind: HTPasswdPasswordIdentityProvider
      login: 'true'
      name: htpasswd_auth
    openshift_metrics_cassandra_storage_type: dynamic
    openshift_metrics_hawkular_hostname: <REDACTED>
    openshift_metrics_install_metrics: 'true'
    openshift_metrics_start_cluster: 'true'
    openshift_node_groups:
    - labels:
      - node-role.kubernetes.io/master=true
      name: node-config-master
    - labels:
      - node-role.kubernetes.io/infra=true
      - node-role.kubernetes.io/compute=true
      - registry_node=true
      - router_node=true
      name: node-config-compute-infra
    - labels:
      - node-role.kubernetes.io/compute=true
      name: node-config-compute
    - labels:
      - node-role.kubernetes.io/infra=true
      - router_node=true
      - registry_node=true
      name: node-config-infra
    - labels:
      - router_node=true
      name: node-config-router
    - labels:
      - registry_node=true
      name: node-config-registry
    openshift_registry_selector: registry_node=true
    openshift_router_selector: router_node=true
    oreg_url: registry.access.redhat.com/openshift3/ose-${component}:${version}
    # Setting this has no effect
    # openshift_cockpit_deployer_version: '3.10'
    # setting this successfully sets image tag
    # openshift_cockpit_deployer_image: 'registry.access.redhat.com/openshift3/registry-console:v3.10'
```
