### ISSUE TITLE
only ose-pod is upgraded from  v3.11.43 to v3.11.51 whilst  other components could not 

### ISSUE THREAD

**Issue by vishnoisuresh** [openshift/openshift-ansible#10951]
#### Description

> Trying to Minor Upgrade OpenShift cluster from  v3.11.43  to v3.11.51, however only one component (**ose-pod** ) is upgraded . The upgadation process was successful there were no issues.  

> Static Pods are having` ImagePullPolicy= IfNotPresent`

##### Version

* Your ansible version per `ansible --version`
```
ansible 2.6.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

Place the output between the code block below:

**OC VERSION** 
```
oc v3.11.51
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://console-openshift-test.int.kn:8443
openshift v3.11.16
kubernetes v1.11.0+d4cacc0

```

##### Expected Results
All of the Components need to be upgraded from  v3.11.43  to v3.11.51

##### Observed Results
Only ose-pod is upgraded to  v3.11.51

```
REPOSITORY                                                  TAG                 IMAGE ID            CREATED             SIZE
registry.redhat.io/openshift3/ose-pod                       v3.11.51            cb27f13ea47a        4 weeks ago         238 MB
registry.redhat.io/openshift3/ose-pod                       v3.11.43            47ea091bca33        7 weeks ago         238 MB
registry.redhat.io/openshift3/ose-logging-fluentd           v3.11.43            0fef36d87b56        7 weeks ago         289 MB
registry.redhat.io/openshift3/ose-node-problem-detector     v3.11.43            c997ba3207cb        7 weeks ago         254 MB
registry.redhat.io/openshift3/ose-logging-fluentd           v3.11.16            715c3499714d        3 months ago        286 MB
registry.redhat.io/openshift3/ose-node                      v3.11               074bf04571e2        3 months ago        1.15 GB
registry.redhat.io/openshift3/ose-node                      v3.11.16            074bf04571e2        3 months ago        1.15 GB
registry.redhat.io/openshift3/ose-control-plane             v3.11               1f23828b535b        3 months ago        794 MB
registry.redhat.io/openshift3/ose-control-plane             v3.11.16            1f23828b535b        3 months ago        794 MB
registry.redhat.io/openshift3/ose-deployer                  v3.11.16            a6b0077a8dd8        3 months ago        357 MB
registry.redhat.io/openshift3/ose-kube-rbac-proxy           v3.11               5c1087872e66        3 months ago        482 MB
registry.redhat.io/openshift3/ose-kube-rbac-proxy           v3.11.16            5c1087872e66        3 months ago        482 MB
registry.redhat.io/openshift3/ose-console                   v3.11               325013035116        3 months ago        250 MB
registry.redhat.io/openshift3/ose-console                   v3.11.16            325013035116        3 months ago        250 MB
registry.redhat.io/openshift3/ose-template-service-broker   v3.11               4bb11311e3eb        3 months ago        308 MB
registry.redhat.io/openshift3/ose-template-service-broker   v3.11.16            4bb11311e3eb        3 months ago        308 MB
registry.redhat.io/openshift3/ose-web-console               v3.11               81206d80b8cb        3 months ago        318 MB
registry.redhat.io/openshift3/ose-web-console               v3.11.16            81206d80b8cb        3 months ago        318 MB
registry.redhat.io/openshift3/ose-pod                       v3.11               751ff215ba5d        3 months ago        234 MB
registry.redhat.io/openshift3/ose-pod                       v3.11.16            751ff215ba5d        3 months ago        234 MB
registry.redhat.io/openshift3/ose-service-catalog           v3.11               07094eebb54e        3 months ago        306 MB
registry.redhat.io/openshift3/ose-service-catalog           v3.11.16            07094eebb54e        3 months ago        306 MB
registry.redhat.io/openshift3/registry-console              v3.11               26eb64a24c85        3 months ago        268 MB
registry.redhat.io/openshift3/registry-console              v3.11.16            26eb64a24c85        3 months ago        268 MB
registry.redhat.io/openshift3/prometheus-node-exporter      v3.11               82e339558772        3 months ago        222 MB
registry.redhat.io/openshift3/prometheus-node-exporter      v3.11.16            82e339558772        3 months ago        222 MB
registry.redhat.io/rhel7/etcd                               3.2.22              fef709cdf7bf        3 months ago        256 MB

```
##### static pod manifest
```
kind: Pod
apiVersion: v1
metadata:
  namespace: kube-system
  
  labels:
    openshift.io/component: api
    openshift.io/control-plane: 'true'
  annotations:
    kubernetes.io/config.hash: f7764dd814eacbb13875a9a3cc507b93
    kubernetes.io/config.mirror: f7764dd814eacbb13875a9a3cc507b93
    kubernetes.io/config.seen: '2019-01-02T13:49:54.023060779Z'
    kubernetes.io/config.source: file
    scheduler.alpha.kubernetes.io/critical-pod: ''
spec:
  restartPolicy: Always
  priority: 2000001000
  schedulerName: default-scheduler
  hostNetwork: true
  terminationGracePeriodSeconds: 30
  nodeName: dehamsl2472.int.kn
  securityContext: {}
  containers:
    - resources: {}
      readinessProbe:
        httpGet:
          path: healthz/ready
          port: 8443
          scheme: HTTPS
        initialDelaySeconds: 10
        timeoutSeconds: 10
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      terminationMessagePath: /dev/termination-log
      name: api
      command:
        - /bin/bash
        - '-c'
      livenessProbe:
        httpGet:
          path: healthz
          port: 8443
          scheme: HTTPS
        initialDelaySeconds: 45
        timeoutSeconds: 10
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      securityContext:
        privileged: true
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: master-config
          mountPath: /etc/origin/master/
        - name: master-cloud-provider
          mountPath: /etc/origin/cloudprovider/
        - name: master-data
          mountPath: /var/lib/origin/
        - name: master-pki
          mountPath: /etc/pki
      terminationMessagePolicy: File
      image: 'registry.redhat.io/openshift3/ose-control-plane:v3.11'
      args:
        - >
          #!/bin/bash

          set -euo pipefail

          if [[ -f /etc/origin/master/master.env ]]; then
            set -o allexport
            source /etc/origin/master/master.env
          fi

          exec openshift start master api
          --config=/etc/origin/master/master-config.yaml
          --loglevel=${DEBUG_LOGLEVEL:-2}
  volumes:
    - name: master-config
      hostPath:
        path: /etc/origin/master/
        type: ''
    - name: master-cloud-provider
      hostPath:
        path: /etc/origin/cloudprovider
        type: ''
    - name: master-data
      hostPath:
        path: /var/lib/origin
        type: ''
    - name: master-pki
      hostPath:
        path: /etc/pki
        type: ''
  dnsPolicy: ClusterFirst
  tolerations:
    - operator: Exists
      effect: NoExecute
  priorityClassName: system-node-critical

```

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system ` Red Hat Enterprise Linux Server release 7.6 (Maipo)`
* The Upgradation workflow was successful there was no issue with the following command 
` ansible-playbook  -e ansible_ssh_user=$USER /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_11/upgrade.yml`

##### Questions 

* Why is there inconsistency with components upgradtion?  
* what does OSE (ose-pod)stands for ? I believe its infrastructure pod
* Why the  **imagePullPolicy: IfNotPresent**?  shouldn't it be  **Always** ? In order to fetch new images with the same tag ?
