### ISSUE TITLE
Deploy cluster playbook should verify master hosts are listed in nodes group

### ISSUE THREAD

**Issue by Mad-ness** [openshift/openshift-ansible#11224]
#### Description

I'm trying to set up openshift-3.11 on CentOS-7 on VirtualBox VMs:
```shell
cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

Running of the playbook ```ansible-playbook -i ../ansible/inventory.yml playbooks/deploy_cluster.yml``` fails with following output:
```shell
TASK [openshift_control_plane : Start and enable self-hosting node] *************************************************
task path: /root/openshift-ansible/roles/openshift_control_plane/tasks/main.yml:183
Thursday 21 February 2019  14:15:42 +0000 (0:00:00.226)       0:02:16.502 *****
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/systemd.py
<192.168.3.11> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.3.11> SSH: EXEC sshpass -d11 ssh -vvv -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="../.vagrant/machines/master01/virtualbox/private_key"' -o User=root -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/%h-%r 192.168.3.11 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<192.168.3.11> (1, '\n{"msg": "Could not find the requested service origin-node: host", "failed": true, "invocation": {"module_args": {"no_block": false, "force": null, "name": "origin-node", "enabled": true, "daemon_reload": false, "state": "restarted", "masked": null, "scope": null, "user": null}}}\n', 'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 14569\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n')
<192.168.3.11> Failed to connect to the host via ssh: OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 58: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 14569
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 1
fatal: [master01.ocp.local]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "daemon_reload": false,
            "enabled": true,
            "force": null,
            "masked": null,
            "name": "origin-node",
            "no_block": false,
            "scope": null,
            "state": "restarted",
            "user": null
        }
    },
    "msg": "Could not find the requested service origin-node: host"
}
...ignoring

TASK [openshift_control_plane : Get node logs] **********************************************************************
task path: /root/openshift-ansible/roles/openshift_control_plane/tasks/main.yml:193
Thursday 21 February 2019  14:15:42 +0000 (0:00:00.277)       0:02:16.780 *****
Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
<192.168.3.11> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.3.11> SSH: EXEC sshpass -d11 ssh -vvv -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="../.vagrant/machines/master01/virtualbox/private_key"' -o User=root -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/%h-%r 192.168.3.11 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<192.168.3.11> (0, '\n{"changed": true, "end": "2019-02-21 14:15:43.118744", "stdout": "-- No entries --", "cmd": ["journalctl", "--no-pager", "-n", "300", "-u", "origin-node"], "rc": 0, "start": "2019-02-21 14:15:43.114739", "stderr": "", "delta": "0:00:00.004005", "invocation": {"module_args": {"warn": true, "executable": null, "_uses_shell": false, "_raw_params": "journalctl --no-pager -n 300 -u origin-node", "removes": null, "argv": null, "creates": null, "chdir": null, "stdin": null}}}\n', 'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 14569\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
changed: [master01.ocp.local] => {
    "changed": true,
    "cmd": [
        "journalctl",
        "--no-pager",
        "-n",
        "300",
        "-u",
        "origin-node"
    ],
    "delta": "0:00:00.004005",
    "end": "2019-02-21 14:15:43.118744",
    "invocation": {
        "module_args": {
            "_raw_params": "journalctl --no-pager -n 300 -u origin-node",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "warn": true
        }
    },
    "rc": 0,
    "start": "2019-02-21 14:15:43.114739",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "-- No entries --",
    "stdout_lines": [
        "-- No entries --"
    ]
}

TASK [openshift_control_plane : debug] ******************************************************************************
task path: /root/openshift-ansible/roles/openshift_control_plane/tasks/main.yml:197
Thursday 21 February 2019  14:15:43 +0000 (0:00:00.212)       0:02:16.992 *****
ok: [master01.ocp.local] => {
    "msg": [
        "-- No entries --"
    ]
}

TASK [openshift_control_plane : fail] *******************************************************************************
task path: /root/openshift-ansible/roles/openshift_control_plane/tasks/main.yml:199
Thursday 21 February 2019  14:15:43 +0000 (0:00:00.088)       0:02:17.080 *****
fatal: [master01.ocp.local]: FAILED! => {
    "changed": false,
    "msg": "Node start failed."
}

NO MORE HOSTS LEFT **************************************************************************************************

PLAY RECAP **********************************************************************************************************
lb.ocp.local               : ok=28   changed=2    unreachable=0    failed=0
localhost                  : ok=12   changed=0    unreachable=0    failed=0
master01.ocp.local         : ok=193  changed=32   unreachable=0    failed=1
node01.ocp.local           : ok=98   changed=18   unreachable=0    failed=0
```

I found that package origin-node is not installed at all by the openshift-ansible playbooks. If I install it manually and check a list of the files which included in the package, there is still no such service origin-node:

```
# rpm -ql origin-node
/etc/kubernetes/manifests
/etc/origin/node
/etc/sysconfig/origin-node
/etc/systemd/system.conf.d/origin-accounting.conf
/usr/bin/openshift-node-config
```

```shell
ansible --version
ansible 2.7.7
  config file = /root/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

This is my inventory file. Docker registry **registry.ocp.local:5000** has all required images downloaded.
```yaml
all:
    children:
        OSEv3:
            children:
                nodes:
                masters:
                etcd:
                lb:
            vars:
                ansible_user: root
                ansible_become: true
                openshift_deployment_type: origin
                openshift_release: '3.11'
                openshift_ip_check: true
                system_images_registry: 'registry.ocp.local:5000'
                openshift_docker_insecure_registries: 'registry.ocp.local:5000'
                openshift_master_default_subdomain: 'apps.ocp.prod'
                oreg_url: 'registry.ocp.local:5000/openshift/origin-${component}:${version}'
                openshift_master_cluster_hostname: 'lb.ocp.local'
                openshift_master_cluster_public_hostname: 'lb.ocp.local'
                openshift_docker_selinux_enabled: false
                openshift_disable_check:
                - disk_availability
                - memory_availability
                - docker_storage
        etcd:
            children:
                masters:
        masters:
            hosts:
                master01.ocp.local:
                    ansible_host: 192.168.3.11
                    ansible_ssh_port: 22
                    ansible_ssh_private_key_file: "../.vagrant/machines/master01/virtualbox/private_key"
                    net2_ip: 192.168.3.11
                    openshift_ip: 192.168.3.11
            vars:
                openshift_node_group_name: 'node-config-master-infra'
                openshift_schedulable: true
        lb:
            hosts:
                lb.ocp.local:
                    ansible_host: 192.168.3.12
                    ansible_ssh_port: 22
                    ansible_ssh_private_key_file: "../.vagrant/machines/lb01/virtualbox/private_key"
                    net2_ip: 192.168.3.12
                    openshift_ip: 192.168.3.12
        nodes:
            hosts:
                node01.ocp.local:
                    ansible_host: 192.168.3.21
                    ansible_ssh_port: 22
                    ansible_ssh_private_key_file: "../.vagrant/machines/node01/virtualbox/private_key"
                    net2_ip: 192.168.3.21
                    openshift_ip: 192.168.3.21
            vars:
              openshift_node_group_name: 'node-config-compute'
    vars:
        ansible_ssh_user: vagrant
        ansible_password: 123
        cluster_domain_name: "ocp.local"
        internal_docker_registry_hostname: 'registry.ocp.local'
```

This is HAProxy's config configured on **lb.ocp.local**
```shell
# grep -Ev '^\s*(#|$)' /etc/haproxy/haproxy.cfg
global
    maxconn     20000
    log         /dev/log local0 info
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    user        haproxy
    group       haproxy
    daemon
    stats socket /var/lib/haproxy/stats
defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          300s
    timeout server          300s
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 20000
listen stats
    bind :9000
    mode http
    stats enable
    stats uri /
frontend  atomic-openshift-api
    bind *:8443
    default_backend atomic-openshift-api
    mode tcp
    option tcplog
backend atomic-openshift-api
    balance source
    mode tcp
    server      master0 192.168.3.11:8443 check
```

Tried latest available openshift-ansible release-3.11 playbooks taken from this repo
```shell
# git describe
openshift-ansible-3.11.87-1-4-g8dbe16b

# git branch
  master
* release-3.11
```

##### Steps To Reproduce
1. Prepare three VMs: lb, master01, node01 with IP addresses and hostnames as mentioned in the inventory. Each of the VMs has eth0 for management purposes and eth1 for openshift.
2. Run playbooks/prerequisites.yml first and then playbooks/deploy_cluster.yml

##### Expected Results
playbooks/deploy_cluster.yml should go without errors

##### Observed Results

Task **TASK [openshift_control_plane : Start and enable self-hosting node]** completes with the error: 
```json
fatal: [master01.ocp.local]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "daemon_reload": false,
            "enabled": true,
            "force": null,
            "masked": null,
            "name": "origin-node",
            "no_block": false,
            "scope": null,
            "state": "restarted",
            "user": null
        }
    },
    "msg": "Could not find the requested service origin-node: host"
}
...ignoring
```
The error is ignored. But the next task stops the playbook execution:
```shell
TASK [openshift_control_plane : Get node logs] **********************************************************************
task path: /root/openshift-ansible/roles/openshift_control_plane/tasks/main.yml:193
Thursday 21 February 2019  14:15:42 +0000 (0:00:00.277)       0:02:16.780 *****
Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
<192.168.3.11> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.3.11> SSH: EXEC sshpass -d11 ssh -vvv -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="../.vagrant/machines/master01/virtualbox/private_key"' -o User=root -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/%h-%r 192.168.3.11 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<192.168.3.11> (0, '\n{"changed": true, "end": "2019-02-21 14:15:43.118744", "stdout": "-- No entries --", "cmd": ["journalctl", "--no-pager", "-n", "300", "-u", "origin-node"], "rc": 0, "start": "2019-02-21 14:15:43.114739", "stderr": "", "delta": "0:00:00.004005", "invocation": {"module_args": {"warn": true, "executable": null, "_uses_shell": false, "_raw_params": "journalctl --no-pager -n 300 -u origin-node", "removes": null, "argv": null, "creates": null, "chdir": null, "stdin": null}}}\n', 'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 14569\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
changed: [master01.ocp.local] => {
    "changed": true,
    "cmd": [
        "journalctl",
        "--no-pager",
        "-n",
        "300",
        "-u",
        "origin-node"
    ],
    "delta": "0:00:00.004005",
    "end": "2019-02-21 14:15:43.118744",
    "invocation": {
        "module_args": {
            "_raw_params": "journalctl --no-pager -n 300 -u origin-node",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "warn": true
        }
    },
    "rc": 0,
    "start": "2019-02-21 14:15:43.114739",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "-- No entries --",
    "stdout_lines": [
        "-- No entries --"
    ]
}

TASK [openshift_control_plane : debug] ******************************************************************************
task path: /root/openshift-ansible/roles/openshift_control_plane/tasks/main.yml:197
Thursday 21 February 2019  14:15:43 +0000 (0:00:00.212)       0:02:16.992 *****
ok: [master01.ocp.local] => {
    "msg": [
        "-- No entries --"
    ]
}

TASK [openshift_control_plane : fail] *******************************************************************************
task path: /root/openshift-ansible/roles/openshift_control_plane/tasks/main.yml:199
Thursday 21 February 2019  14:15:43 +0000 (0:00:00.088)       0:02:17.080 *****
fatal: [master01.ocp.local]: FAILED! => {
    "changed": false,
    "msg": "Node start failed."
}
```

Tried to play with different options but could not move over the failed task.
Could you please give some ideas on what the cause might be.

**Comment by vrutkovs** [comment]
>I found that package origin-node is not installed at all by the openshift-ansible playbooks. 

It should have installed the CentOS repos. Could you post the full log of deploy_cluster playbook?

>If I install it manually and check a list of the files which included in the package, there is still no such service origin-node:

What's the version of the package was picked up? It looks like 4.x RPMs have been installed

**Comment by Mad-ness** [comment]
1. [openshift-ansible.log](https://github.com/openshift/openshift-ansible/files/2890871/openshift-ansible.log) attached, it includes logs from deploy_cluster.yml.
2. Package origin-node is not installed.
```
# yum info origin-node
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.airenetworks.es
 * extras: mir01.syntis.net
 * updates: mirror.airenetworks.es
Available Packages
Name        : origin-node
Arch        : x86_64
Version     : 3.11.0
Release     : 1.el7.git.0.62803d0
Size        : 6.1 M
Repo        : centos-openshift-origin311
Summary     : Origin Node
URL         : https://github.com/openshift/origin
License     : ASL 2.0
Description : Origin Node
```
Configured repos
```
# yum repolist
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.airenetworks.es
 * extras: mir01.syntis.net
 * updates: mirror.airenetworks.es
repo id                                    repo name                                status
base/7/x86_64                              CentOS-7 - Base                          10,019
centos-openshift-origin311                 CentOS OpenShift Origin                      30
extras/7/x86_64                            CentOS-7 - Extras                           364
updates/7/x86_64                           CentOS-7 - Updates                        1,067
repolist: 11,480
```


Btw, before the error I shown at the beginning, **deploy_cluster.yml** checks the file **/etc/sysconfig/origin-node**, and it fails because the file not found. I did the trick by creating the file on my own like this.
```
- name: Make sure file /etc/sysconfig/origin-node exists
  file:
    path: /etc/sysconfig/origin-node
    state: touch
```
But the error in the topic I couldn't fix.
