### ISSUE TITLE
newline being inserted at space in LDAP url for master-config 

### ISSUE THREAD

**Issue by David-Igou** [openshift/openshift-ansible#11323]
#### Description

I have a pretty long LDAP URL with spaces, that gets a newline inserted when master-config is generated

From my auth providers variable:
```
openshift_master_identity_providers:
 - name: 'LDAP Users'
   login: 'true'
   challenge: 'true'
   kind: 'LDAPPasswordIdentityProvider'
   attributes:
     id: ['dn']
     email: ['mail']
     name: ['cn']
     preferredUsername: ['sAMAccountName']
   bindDN: "omitted"
   bindPassword: "omitted"
   url: 'ldap://mycorp.net:1234/DC=mycorp,DC=net?sAMAccountName?sub?(&(memberOf=cn=IT-AUTOMATION-TEAM-WITH-LONGISH-NAME,ou=Ldap Groups,ou=Micro Management,dc=mycorp,dc=net))'
   insecure: true
```

When master-config is generated, I get:

```
[...]
      url: ldap://mycorp.net:1234/DC=mycorp,DC=net?sAMAccountName?sub?(&(memberOf=cn=IT-AUTOMATION-TEAM-WITH-LONGISH-NAME,ou=Ldap
         Groups,ou=Micro Management,dc=mycorp,dc=net))
[...]
```

For my LDAP URL entry. This is not interpreted properly by Openshift and leads to authentication errors.

##### Version

```
$ ansible --version
ansible 2.6.12
ansible python module location = /usr/lib/python2.7/site-packages/ansible executable location =/usr/bin/
ansible python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] 
$ rpm -q openshift-ansible 
openshift-ansible-3.11.82-3.git.0.9718d0a.el7.noarch 
```

##### Steps To Reproduce
1. Run cluster deployment (openshift-master/config.yml portion to be exact)

##### Expected Results
Describe what you expected to happen.

Single line ldap url

##### Observed Results
Describe what is actually happening.

newline/indention inserted
