### ISSUE TITLE
openshift_ovirt creates an inventory with missing items, wrong groups

### ISSUE THREAD

**Issue by rgolangh** [openshift/openshift-ansible#11457]
#### Description

The inventory which is created by the 'create_inventory_from_vms.yaml' task is missing items and groups details. Consider this manifest:
```yaml
 openshift_ovirt_vm_manifest:
      - name: master
        count: 3
      - name: compute
        count: 3
      - name: etcd
        count: 3
```

Expected:
```ini
[masters]
master[0:2].DOMAIN
[nodes]
master[0:2].DOMAIN
compute[0:2].DOMAIN
[etcd]
etcd[0:2].DOMAIN
```
Actual:
```ini
[masters]
master0.DOMAIN
[nodes]
compute0.DOMAIN
[etcd]
etc0.DOMAIN
```

Also, if etcd isn't requested, we miss the masters assigment as etcd nodes:
```yaml
 openshift_ovirt_vm_manifest:
      - name: master
        count: 3
      - name: compute
        count: 3
      - name: etcd
        count: 0
```
expected:
```ini
[master]
master[0:2].DOM
[etcd]
master[0:2].DOM
[nodes]
master[0:2].DOM
compute[0:2].DOM
```

##### Version
okd 3.11

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
2.7

* The output of `git describe`
openshift-ansible-3.11.103-1-16-g656e94a86

##### Observed Results
Cluster deployment fails
