### ISSUE TITLE
Custom certificates breaks CRD creation

### ISSUE THREAD

**Issue by ephracis** [openshift/openshift-ansible#11753]
#### Description

When I deploy with custom certificates using `openshift_master_named_certificates` the task *Wait for the ServiceMonitor CRD to be created* retries until failure. But this only happens if I set `cafile` on the item:

```
# this works
openshift_master_named_certificates:
  - certfile: /path/to/openshift.crt
    keyfile: /path/to/openshift.key
    names:
      - openshift.example.com

# this does not
openshift_master_named_certificates:
  - certfile: /path/to/openshift.crt
    keyfile: /path/to/openshift.key
    names:
      - openshift.example.com
    cafile: /path/to/openshift_ca.crt
```

In the first case though, I get an error at the cluster console after it logs me in, and get thrown back to the login page. If I leave out the `openshift_master_named_certificates` completely it works, though I will obviously not have a proper certificate in front of the API or web ui.

##### Version

```
ansible 2.7.11
  config file = /Users/chbr/repos/work/components/openshift/ansible.cfg
  configured module search path = ['/Users/chbr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/chbr/repos/work/products/bcp/venv/lib/python3.7/site-packages/ansible
  executable location = /Users/chbr/repos/work/products/bcp/venv/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)]

I downloaded the tag `3.11.123`.
```

##### Steps To Reproduce
1. Create 3 virtual machines with CentOS 7.6
2. Download openshift-ansible
3. Configure the inventory according to the scenarios above
4. Run the prereq/deploy playbooks

##### Expected Results

- Ansible should finish without errors.
- When I use `oc` or browse to the web ui I should get a certificate signed by my custom CA.
- When I go to the cluster console it should allow me to login in a view the page without errors.

##### Observed Results

If I have no `cafile` in the named certificate item:
- Ansible finishes without error
- The web UI shows the correct certificate, though the CA is not included like it is for the cluster console (router certificate)
- After logging in to the cluster console (console.apps.example.com) I briefly see an error and get redirected back to the login page

If I have a `cafile` in the named certificate item:
- Ansible fails at the task *Wait for the ServiceMonitor CRD to be created*

If I skip `openshift_master_named_certificates` completely:
- Ansible finishes without errors
- The web UI shows the certificate signed by openshift-signer
- The cluster console shows the certificate I configured using `openshift_hosted_router_certificate`
- I can log in to the cluster console and the web ui without problems

##### Additional Information

- Deploying from macOS
- Deploying onto freshly built CentOS 7.6 machines every time (OpenShift qcow images)
- `openshift_master_cluster_hostname` is the floating IP
- `openshift_master_cluster_public_hostname` is a dynamic DNS record pointing to the floating IP
