### ISSUE TITLE
OpenShift ClusterMonitoring Operator with very old quay image

### ISSUE THREAD

**Issue by padyx** [openshift/openshift-ansible#11767]
#### Description

OpenShift 3.11

The [openshift_cluster_monitoring_operator role](https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_cluster_monitoring_operator/defaults/main.yml) seems to use a very old image from quay.io (quay.io/coreos/cluster-monitoring-operator:v0.1.1).

That version deploys node-exporter pods without tolerations, which thus can't handle node taints. Newer versions are able to properly handle properly (https://github.com/openshift/cluster-monitoring-operator/issues/227#issuecomment-510377777).

I'm not sure if there are other differences between the images - but shouldn't the role be changed to use the **openshift**/origin-cluster-monitoring-operator:3.11 image, or use a newer version of the **coreos**/cluster-monitoring-operator?

##### Version

```
$ ansible --version
ansible 2.6.11
  config file = None
  configured module search path = [u'/home/.../.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]


$ git describe
openshift-ansible-3.11.119-1-8-gc188f3652
```

##### Steps To Reproduce
1. Deploy a new cluster with monitoring enabled
2. Check the image of the prometheus-operator-... pod (openshift-monitoring namespace) 

Related issue: #10553

**Comment by ytcisme** [comment]
Is there any progress here? 
I'd like to know which one is the right image, `quay.io/coreos/cluster-monitoring-operator:v0.1.1` or `quay.io/openshift/origin-cluster-monitoring-operator:v3.11` ?

I read the [ansible-playbooks](https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_cluster_monitoring_operator/defaults/main.yml#L8). 
```
---
openshift_cluster_monitoring_operator_namespace: openshift-monitoring

l_openshift_cluster_monitoring_operator_image_dicts:
  origin: 'quay.io/openshift/origin-cluster-monitoring-operator:v3.11'
  openshift-enterprise: "{{ l_osm_registry_url | regex_replace('${component}' | regex_escape, 'cluster-monitoring-operator') }}"

openshift_cluster_monitoring_operator_image: "{{ l_openshift_cluster_monitoring_operator_image_dicts[openshift_deployment_type] }}"
```

Maybe the image `quay.io/openshift/origin-cluster-monitoring-operator:v3.11` is right, if the value of `openshift_deployment_type` is origin.But I got `quay.io/openshift/origin-cluster-monitoring-operator:v0.1.1`, when the value of `openshift_deployment_type` is origin in my inventory file.
