### ISSUE TITLE
Should an openshift_logging_elasticsearch_pvc_dynamic value be passed in, here?

### ISSUE THREAD

**Issue by gswallow** [openshift/openshift-ansible#11786]
When setting up storage for Openshift Logging, the `openshift-logging` role's `install_logging.yml` task doesn't pass `openshfit_logging_elasticsearch_pvc_dynamic` to the `openshift_logging_elasticsearch` role: 

https://github.com/openshift/openshift-ansible/blob/11838de2955d4d48815a8993e060dc293f9914f2/roles/openshift_logging/tasks/install_logging.yaml#L129

This causes Ansible to create pvc templates without storage class names in them, like this:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logging-es-0
  labels:
    logging-infra: support
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
```

You can see this behavior in https://github.com/openshift/openshift-ansible/blob/11838de2955d4d48815a8993e060dc293f9914f2/roles/openshift_logging_elasticsearch/tasks/main.yaml#L376-L409

By contrast, when creating an ops ES cluster (our app logging cluster is split from our ops logging cluster), the `openshift_logging_elasticsearch_pvc_dynamic` parameter *is* passed into the `openshift_logging_elasticsearch` role, here:

https://github.com/openshift/openshift-ansible/blob/11838de2955d4d48815a8993e060dc293f9914f2/roles/openshift_logging/tasks/install_logging.yaml#L213

And that results in a properly formatted PVC template:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logging-es-ops-1
  labels:
    logging-infra: support
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: glusterfs-registry-block
```

My intention is to set up a block-backed volume storage class for "infrastructure" storage, as that's what the Openshift documentation recommends, and then leave file-backed volume storage as the default storage class.  The only way to work around this is to set infra-related block storage as default, and then change the default post-openshift-install.

If this change is appropriate, I can submit a pull request and possibly work on https://bugzilla.redhat.com/show_bug.cgi?id=1703239#, too.
