### ISSUE TITLE
"openshift_logging_es_cpu_limit" is ignored

### ISSUE THREAD

**Issue by yuanlinios** [openshift/openshift-ansible#12018]
#### Description

The cpu limit variable "openshift_logging_es_cpu_limit" is ignored

According to document 
https://docs.openshift.com/container-platform/3.11/install_config/aggregate_logging.html
It is possible to set the cpu limit for elasticsearch pod with the variable "openshift_logging_es_cpu_limit". However this setting is totally ignored

##### Version
```
ansible --version
ansible 2.8.1

git describe
openshift-ansible-3.11.154-1-10-g2644e49
```

##### Steps To Reproduce
Related yaml inventory snippet
```
...
    openshift_logging_install_logging: true
    openshift_logging_install_eventrouter: true
    openshift_logging_use_ops: false
    openshift_logging_purge_logging: true
    openshift_logging_eventrouter_cpu_limit: 100m
    openshift_logging_eventrouter_memory_limit: 128Mi
    openshift_logging_eventrouter_nodeselector: { 'node-role.kubernetes.io/infra': 'true' }
    openshift_logging_elasticsearch_storage_type: pvc
    openshift_logging_es_pvc_dynamic: true
    openshift_logging_es_pvc_storage_class_name: ceph-rbd
    openshift_logging_es_pvc_size: 10Gi
    openshift_logging_es_cluster_size: 3
    openshift_logging_es_number_of_replicas: 1
    openshift_logging_es_number_of_shards: 3
    openshift_logging_es_memory_limit: 8G
    openshift_logging_es_cpu_limit: 800m
    openshift_logging_es_cpu_request: 800m
    openshift_logging_es_nodeselector: { 'node-role.kubernetes.io/infra': 'true' }
    openshift_logging_curator_default_days: 3
    openshift_logging_curator_cpu_limit: 100m
    openshift_logging_curator_nodeselector: { 'node-role.kubernetes.io/infra': 'true' }
    openshift_logging_fluentd_journal_read_from_head: false
    openshift_logging_fluentd_cpu_limit: 100m
    openshift_logging_kibana_cpu_limit: 200m
    openshift_logging_kibana_replica_count: 1
    openshift_logging_kibana_nodeselector: { 'node-role.kubernetes.io/infra': 'true' }
```

##### Expected Results
`oc -n openshift-logging get dc logging-es-data-master-xxxxx -o yaml` should show the specified cpu limit
```
        resources:
          limits:
            memory: 8G
            cpu: 800m
          requests:
            cpu: 800m
            memory: 8G

```

##### Observed Results
The setting is ignored. 
```
        resources:
          limits:
            memory: 8G
          requests:
            cpu: 800m
            memory: 8G
```

A quick inspect of ansible roles code shows me the variable is never referenced
