### ISSUE TITLE
AnsibleUndefinedVariable: 'kuryr_openstack_auth_url' is undefined

### ISSUE THREAD

**Issue by madipietro** [openshift/openshift-ansible#12067]
#### Description

Provide a brief description of your issue here. For example: Hi!!, im installing ocp3.11 enterprise version on top of openstack 13, on all cases im having problems to start the kuryr plugin, the playbook "playbooks/openstack/openshift-cluster/provision.yml" works and ends OK, the playbook "playbooks/openstack/openshift-cluster/prerequisites.yml" works and ends OK, the playbook "playbooks/openstack/openshift-cluster/install.yml" doesn't work because some kuryr vars are not defined and thats why im here, on the file "playbooks/roles/kuryr/templates/configmap.yaml.j2" for create the config map we have some vars like

   The root URL of the Kubernetes API (string value)
    `api_root = https://{{ kuryr_openstack_api_lb_ip }}:{{openshift_master_api_port}}`

The var "kuryr_openstack_api_lb_ip" fails in first place, but i did set it to the full dns domain of my installation, but then the var "'kuryr_openstack_auth_url" fails with the message of the title, the question, where i find the correct value for this vars since they are not on "inventory/group_vars/all.yml" and are not on the documentation.

Version
Version im using "openshift-ansible-3.11.99-1"

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
```
ansible 2.6.0
  config file = /home/mdipietro/Laburo/github.com/openshift-ansible/ansible.cfg
  configured module search path = [u'/home/mdipietro/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mdipietro/Laburo/github.com/openshift-ansible/venv/venv/lib/python2.7/site-packages/ansible
  executable location = /home/mdipietro/Laburo/github.com/openshift-ansible/venv/venv/bin/ansible
  python version = 2.7.17 (default, Oct 22 2019, 09:14:09) [GCC 9.2.0]
```

If you're operating from a **git clone**:

* The output of `git describe`
openshift-ansible-3.11.99-1

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
1. [step 1]

Running the playbook playbooks/openstack/openshift-cluster/provision.yml OK

2. [step 2]

playbooks/openstack/openshift-cluster/prerequisites.yml OK
 
3. [step 3]

playbooks/openstack/openshift-cluster/install.yml  FAILS

##### Expected Results
The ocp 3.11 cluster fully installed

```
ansible-playbook --user openshift -i playbooks/openstack/inventory.py -i inventory playbooks/openstack/openshift-cluster/install.yml
```

##### Observed Results.
The install fails because undefined kuryr variables
kuryr_openstack_api_lb_ip
kuryr_openstack_auth_url

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information
Installer running from an arch linux box, using a Rhel vm ( openstack director ) as jumpbox, the infra creation works fine but the install of the cluster fails at the master bootstraping cause the kuryr undefined variables.

My kuryr config taken from the documentation
```

openshift_use_kuryr: true
openshift_use_openshift_sdn: false
os_sdn_network_plugin_name: cni
openshift_node_proxy_mode: userspace
use_trunk_ports: true

openshift_master_open_ports:
- service: dns tcp
  port: 53/tcp
- service: dns udp
  port: 53/udp
openshift_node_open_ports:
- service: dns tcp
  port: 53/tcp
- service: dns udp
  port: 53/udp

kuryr_openstack_public_net_id: 7c238f93-2d20-4ba1-864f-e80298549cc2

openshift_openstack_kuryr_cni_image:  registry.redhat.io/rhosp13/openstack-kuryr-cni:13.0
openshift_openstack_kuryr_controller_image: registry.redhat.io/rhosp13/openstack-kuryr-controller:13.0

```

* Your operating system and version, ie: Red Hat Enterprise Linux Server release 7.6 (Maipo)
* Your inventory file (especially any non-standard configuration parameters)
```
---
openshift_openstack_clusterid: "{{ openshift_openstack_clusterid }}" 
openshift_openstack_public_dns_domain: "openshifttestlogicalis.com"
openshift_openstack_dns_nameservers: []


openshift_openstack_master_hostname: "master"
openshift_openstack_infra_hostname: "infra-node"
openshift_openstack_node_hostname: "app-node"


openshift_openstack_keypair_name: "mykey"
openshift_openstack_external_network_name: "Public Network"
openshift_openstack_private_network_name:  "openshift-ansible-{{ openshift_openstack_stack_name }}-net"

openshift_use_kuryr: true
openshift_use_openshift_sdn: false
os_sdn_network_plugin_name: cni
openshift_node_proxy_mode: userspace
use_trunk_ports: true

openshift_master_open_ports:
- service: dns tcp
  port: 53/tcp
- service: dns udp
  port: 53/udp
openshift_node_open_ports:
- service: dns tcp
  port: 53/tcp
- service: dns udp
  port: 53/udp

kuryr_openstack_public_net_id: my_ext_net_id

openshift_openstack_kuryr_cni_image:  registry.redhat.io/rhosp13/openstack-kuryr-cni:13.0
openshift_openstack_kuryr_controller_image: registry.redhat.io/rhosp13/openstack-kuryr-controller:13.0
openshift_kuryr_subnet_driver: namespace
openshift_kuryr_sg_driver: namespace

# If you VM images will name the ethernet device different than 'eth0',
# override this
#kuryr_cni_link_interface: eth0

enable_kuryr_cni_probes: False

openshift_openstack_default_image_name: "rhel-7.6"

openshift_openstack_num_masters: "{{ openshift_openstack_num_masters }}"
openshift_openstack_num_infra: "{{ openshift_openstack_num_infra }}"
openshift_openstack_num_nodes: "{{ openshift_openstack_num_nodes }}"


openshift_openstack_load_balancer_floating_ip: true

openshift_openstack_default_flavor: "Clouda"

openshift_openstack_use_lbaas_load_balancer: true

openshift_openstack_master_volume_size: "15"
openshift_openstack_infra_volume_size: "15"
openshift_openstack_node_volume_size: "15"
openshift_openstack_docker_volume_size: "15"



# The Classless Inter-Domain Routing (CIDR) for the OpenStack VM subnet.
openshift_openstack_subnet_cidr: "192.168.88.0/27"
# The starting IP address for the OpenStack subnet allocation pool.
openshift_openstack_pool_start: "192.168.88.3"
# The ending IP address for the OpenStack subnet allocation pool.
openshift_openstack_pool_end: "192.168.88.30"

## Red Hat subscription using user/password
rhsub_user: 'name'
rhsub_pass: 'password'
# Or if using activation key:
#rhsub_ak: '<ak>'
#rhsub_orgid: '<orgid>'
rhsub_pool: '8a85f99c6cb985'

ansible_user: openshift
openshift_openstack_ephemeral_volumes: false

## cloud config
openshift_openstack_disable_root: true
openshift_openstack_user: openshift
```

* Sample code, etc

EXTRA INFORMATION GOES HERE

Creation of infra
Running from arch linux box direct to the openstack API.
Ansible 2.6
Python 2.7

Cluster install 
Running from arch linux box, using the director to talk to nodes and start the installation.
Ansible 2.6
Python 2.7
My ssh jumbox config

```

#Jumpbox 
Host 10.80.xxx.*
  ProxyCommand ssh -W %h:%p 10.80.111.5
  IdentityFile ~/.ssh/director1.pem
  MACs hmac-sha2-256
  KexAlgorithms ecdh-sha2-nistp521

Host 10.80.zzz.5
  Hostname 10.80.zzz.5
  User stack
  IdentityFile ~/.ssh/id_rsa
  ControlMaster auto
  ControlPath ~/.ssh/ansible-%r@%h:%p
  ControlPersist 5m
 
  MACs hmac-sha2-256
  KexAlgorithms ecdh-sha2-nistp521
```

My OSEv3.yml

```
---
## Openshift product versions and repos to install from
#openshift_deployment_type: origin
#openshift_repos_enable_testing: true
openshift_deployment_type: "openshift-enterprise"
openshift_image_tag: "v3.11.161"
openshift_pkg_version: "-3.11.161"
openshift_release: "3.11.161"
oreg_url: "registry.access.redhat.com/openshift3/ose-${component}:${version}"
oreg_auth_user: "myaccount"
oreg_auth_password: "mypassword"


openshift_master_default_subdomain: "apps.{{ (openshift_openstack_clusterid|trim == '') | ternary(openshift_openstack_public_dns_domain, openshift_openstack_clusterid + '.' + openshift_openstack_public_dns_domain) }}"

openshift_master_cluster_public_hostname: "console.{{ (openshift_openstack_clusterid|trim == '') | ternary(openshift_openstack_public_dns_domain, openshift_openstack_clusterid + '.' + openshift_openstack_public_dns_domain) }}"


openshift_hosted_router_wait: True
openshift_hosted_registry_wait: True


## Kuryr label configuration
kuryr_openstack_pool_driver: multi

openshift_node_groups:
  - name: node-config-master
    labels:
      - 'node-role.kubernetes.io/master=true'
      - 'pod_vif=nested-vlan'
    edits: []
  - name: node-config-infra
    labels:
      - 'node-role.kubernetes.io/infra=true'
      - 'pod_vif=nested-vlan'
    edits: []
  - name: node-config-compute
    labels:
      - 'node-role.kubernetes.io/compute=true'
      - 'pod_vif=nested-vlan'
    edits: []

openshift_hostname_check: false
openshift_disable_check: disk_availability,memory_availability

ansible_become: true

```

Ty in advance!
