### ISSUE TITLE
cockpit/kubernetes-image no longer available from dockerhub

### ISSUE THREAD

**Issue by pgress** [openshift/openshift-ansible#12115]
#### Description

On a fresh cluster-installation the playbooks fail at the docker_image_availability-step. Reason for this issue is, that the cockpit/kubernetes:latest image is deleted. It looks like the work on this image ist discontinued.
See also https://github.com/cockpit-project/cockpit/commit/37aa31e58f3375feafdfa87d66ac8a494148b418

##### Version
```
* Your ansible version per `ansible --version`
ansible 2.9.4
  config file = None
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.5 (default, Oct 17 2019, 12:25:15) [GCC 8.3.0]

* The output of `git describe`
openshift-ansible-3.11.174-1
```

##### Steps To Reproduce
1. Just follow the instruction to install any sort of cluster

##### Expected Results
A working Cluster in initial state

##### Observed Results

```
     One or more checks failed
      check "docker_image_availability":
                One or more required container images are not available:
                    docker.io/cockpit/kubernetes:latest
                Checked with: skopeo inspect [--tls-verify=false] [--creds=<user>:<pass>] docker://<registry>/<image>
```

**Comment by js-max** [comment]
got errors also deploying 3.11 here, same msg

**Comment by js-max** [comment]
Checking the code if I'm wrong please correct me

`defaults/main.yml` file will have 
```
openshift_health_check_required_images: "{{ [] + l_required_node_images + l_cockpit_images + l_master_required_images + l_etcd_required_images + l_atomic_node_required_images }}"
```

`l_cockpit_images` var is evaluated two lines before with a ternary

```
l_cockpit_images: "{{ (openshift_hosted_manage_registry_console | bool) | ternary([openshift_cockpit_deployer_image], []) }}"
```

so as a quick workaround `openshift_hosted_manage_registry_console=false` at inventory file is enough for a basic installation

different configs should need to be checked accordingly

**Comment by ZrytyADHD** [comment]
I have the same error today installing cluster several times. I write on cockpit git and also try to pull image to my private repo from other clusterr.

**Comment by thdevelthreesixtiy** [comment]
Thx very much to timbrd for the copy.
You made my day!

**Comment by aroute** [comment]
Is there a way to fix this on an already-running OKD 3.11 cluster? My registry-console pod has ImagePullBackOff error due to this issue.

**Comment by pgress** [comment]
@aroute Yes, you can use the image from @timbrd and put it in your deployment for the registry-console

**Comment by aroute** [comment]
okay, that worked. I built the image, which also worked. But, this must not be a permanent solution? Is anyone looking to resolve this so we don't have to apply our own work around?

**Comment by timbrd** [comment]
> okay, that worked. I built the image, which also worked. But, this must not be a permanent solution? Is anyone looking to resolve this so we don't have to apply our own work around?

@ZrytyADHD has opened [an issue](https://github.com/cockpit-project/cockpit/issues/13654) on the cockpit project. Hopefully they reupload the image to the official namespace again soon.

**Comment by magick93** [comment]
I have tried the following:

- docker pull cockpit/kubernetes:latest
- docker pull registry.access.redhat.com/openshift3/registry-console:latest
- docker pull timbordemann/kubernetes:latest
- docker pull openshift3/registry-console
- oc import-image openshift3/registry-console --from=registry.access.redhat.com/openshift3/registry-console --confirm


None have worked.

**Comment by magick93** [comment]
This playbook will pull the image (tested on Centos 7)

```
---
- name: Fix missing registry console
  hosts: masters
  gather_facts: True

  tasks:

    - name: ensure /etc/rhsm/ca/redhat-uep.pem exists
      copy:
        content: ""
        dest: /etc/rhsm/ca/redhat-uep.pem
        owner: root
      become: yes


    - name: pull registry.access.redhat.com/openshift3/registry-console:v3.11.170-5
      docker_image:
        name: registry.access.redhat.com/openshift3/registry-console:v3.11.170-5
        source: pull
```
