### ISSUE TITLE
openshift_install fails to install cluster on openstack

### ISSUE THREAD

**Issue by 1va13n7in** [openshift/openshift-ansible#12378]
#### Description
openshift_install fails to install cluster on openstack

```
FATAL failed to fetch Metadata: failed to load asset "Install Config": failed to create a volume client: No suitable endpoint could be found in the service catalog.
```

openstack-install fails, no matter if clouds.yaml + install-config.yaml are present or not, even on interactive install.

##### Version

```
./openshift-install 4.9.0-0.okd-2022-01-29-035536
built from commit 8d5b2831d3afa00a5a524283718c9577c957a49d
release image quay.io/openshift/okd@sha256:ce42e3e42c19b2d97f51221a65e1f97191b6f51f6e8552ba339dace501e29d1a
release architecture amd64
```
identical behavior on versions: 4.9.22 + 4.8.32

##### Steps To Reproduce
1. install openstack-ansible version 23.2.1
2. create clouds.yaml according to documentation https://github.com/openshift/installer/blob/master/docs/user/openstack/customization.md#openstack-platform-customization
```
clouds:
  openstack_local:
    auth:
      auth_url: https://10.0.2.15:5000
      username: "admin"
      project_id: 5240ffd10f4b41c3ac3055db50ea6ee5
      project_name: "admin"
      user_domain_name: "Default"
      password: "XXX"
    region_name: "RegionOne"
    interface: "public"
    identity_api_version: 3
```
3. create install-config.yaml
```
---
apiVersion: v1
baseDomain: "op3nsh1ft.cluster"
metadata:
  name: "va13"
compute:
- name: worker
  platform:
    openstack:
      type: m.ocp.node
  replicas: 1
controlPlane:
  name: master
  platform:
    openstack:
      type: l.ocp.master
  replicas: 3
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostSubnetLength: 9
  serviceCIDR: 172.30.0.0/16
  machineCIDR: 10.196.0.0/16
platform:
  openstack:
    cloud: "openstack_local"
    defaultMachinePlatform:
    externalDNS:
    - "192.168.1.1"
    - "192.168.23.1"
    externalNetwork: "public"
    clusterOSImage: "fedora-coreos-35.20220116.3.0-openstack.x86_64"
    region: "regionOne"
    computeFlavor: "s.ocp.node"
    lbFloatingIP: "172.29.251.243"
    ingressFloatingIp: "172.29.251.248"
pullSecret: 'XXX'
# yamllint disable
sshKey: 'XXX'
# yamllint enable
```

##### Expected Results
Expect the installer to deploy a cluster, or give a more descriptive error message

##### Observed Results
```
E./openshift-install create cluster --dir=okd4
FATAL failed to fetch Metadata: failed to load asset "Install Config": failed to create a volume client: No suitable endpoint could be found in the service catalog.
```
This error message is not understandable at my knowledge level.

##### Additional Information

Installer is run on ubuntu, but might be any other operating system

```
uname -a
Linux tux 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

```
EXTRA INFORMATION GOES HERE
```
