### ISSUE TITLE
[RFE] add variable for configuring the default project's node selector

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-ansible#1358]
We have a config yaml option for configuring the default node selector (all created projects).

We do not have an installer option for post-configuration of a node selector for the default, openshift-infra, and other proejcts.

This would be nice (saves a manual step that most folks will probably end up doing).

**Comment by detiber** [comment]
@thoraxe what are your thoughts on the format for providing it?

would you expect it to be something like this (assuming ini format):
```
openshift_admin_project_default_selector={'region': 'infra'}
```
or something more involved like this (assuming yaml format):
```
openshift_admin_project_selectors:
  default:
    region: infra
  openshift_infra:
    region: metrics_and_logging
  my_special_project:
    region: special_project
```
which in ini format would look like this monstrosity:
```
openshift_admin_project_selectors={'default': {'region': 'infra'}, 'openshift_infra': {'region': 'metrics_and_logging'}, 'my_special_project': {'region': 'special_project'}}
```
