### ISSUE TITLE
GitHubIdentityProvider organization config

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-ansible#1360]
https://github.com/openshift/origin/pull/7161 adds the ability to optionally limit GitHub logins to specific GitHub organizations.

Example config to allow members of `myorgname` or `anotherorgname` to log in:
```
oauthConfig:
  ...
  identityProviders:
  - name: github 
    challenge: false 
    login: true 
    mappingMethod: claim
    provider:
      apiVersion: v1
      kind: GitHubIdentityProvider
      clientID: ...
      clientSecret: ...
      organizations:
      - myorgname
      - anotherorgname
```
