### ISSUE TITLE
RequestHeaderIdentityProvider options

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-ansible#1468]
https://github.com/openshift/origin/pull/7547 brings the requestheader IDP to parity with the other providers by allowing setting the display name, email, and preferred username from header values.

Added config for listing headers to read display name, email, and preferred username from headers. The new, optional, config fields are `emailHeaders`, `nameHeaders`, `preferredUsernameHeaders`. Example config:

```
oauthConfig:
  ...
  identityProviders:
  - name: "..."
    provider:
      apiVersion: v1
      kind: RequestHeaderIdentityProvider
      headers:
      - X-Remote-User
      emailHeaders:
      - X-Remote-User-Email
      nameHeaders:
      - X-Remote-User-Display-Name
      preferredUsernameHeaders:
      - X-Remote-User-Login
```
