### ISSUE TITLE
bin/cluster changes needed

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-ansible#1581]
Currently bin/cluster invokes provider specific playbooks which encapsulate both instance creation and bootstrapping of the cluster by configuring all variables and invoking the common playbooks directly. 

The issue that arises from this is that as variables, groups, and playbooks are added, changed, etc many times those changes are not also reflected in the provider specific playbooks.

Instead I propose the following solution for simplifying the maintenance of these playbooks.
- Move configuration logic out of the provider specific playbooks, instead the provider playbooks should:
  - Instantiate and bootstrap the hosts
  - Map provider specific groups to the groups used by the byo playbooks
  - Invoke the associated byo playbook based on the task being run.
- Consolidate common steps between different providers
  - Currently libvirt and gce groups are handled differently because of the way that the groups are created from the tags. The gce inventory now has an option to work the same way as the aws/openstack inventories in this regard. The libvirt inventory would need to be updated in a similar way.
  - Common cloud-provider playbooks, tasks, etc could be placed in a playbooks/cloud-provider-common directory and called into from the provider specific playbooks.
- Replace the use of the oo_option lookup plugin with a yaml config file that can be read from a default location or passed into bin/cluster
  - The yaml file could allow for setting provider specific config as well as env, cluster, and group vars, the variables could then be added to the group mappings in the appropriate places
  - rough idea for yaml file format:

```

---
provider:
  libvirt:
    image_name: CentOS-7-x86_64-GenericCloud.qcow2
    ssh_user: cloud-user
    libvirt_instance_vcpu: 1
  aws:
    image: ami-10663b78
    ssh_user: ec2-user
    keypair: default
env:
  dev:
    openshift_use_flannel: yes
    openshift_use_openshift_sdn: no
  prod:
    openshift_use_openshift_sdn: yes
    openshift_use_flannel: no
cluster:
  cluster1:
    openshift_deployment_type: origin
  cluster2:
    openshfit_deployment_type: openshift-enterprise
masters:
  openshift_master_cluster_method: native
  openshift_master_console_port: 443
  openshift_master_api_port: 443
nodes:
  openshift_node_iptables_sync_period: 5
...
```
