### ISSUE TITLE
openshift_master_identity_providers for OpenID config

### ISSUE THREAD

**Issue by anweiss** [openshift/openshift-ansible#1587]
Was wondering if there was an example showing how the `openshift_master_identity_providers` variable could be set for OpenID per settings [here](https://docs.openshift.org/latest/install_config/configuring_authentication.html#OpenID).

**Comment by detiber** [comment]
@anweiss assuming using an ansible inventory file (like inventory/byo/hosts.ose.example):
```
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'false', 'kind': 'OpenIDIdentityProvider', 'client_id': 'my_client_id', 'client_secret': 'my_client_secret', 'claims': { 'id': ['sub'], 'preferredUsername': ['preferred_username'], 'name': ['name'], 'email': ['email']}, 'urls': {'authorize': 'https://myidp.example.com/oauth2/authorize', 'token':  https://myidp.example.com/oauth2/token'}}]
```

If using a group_vars or host_vars file, you can get away with defining it in yaml:
```
openshift_master_identity_providers:
- name: my_openid_connect 
  challenge: false 
  login: true 
  mappingMethod: claim 
  kind: OpenIDIdentityProvider
  clientID: ... 
  clientSecret: ... 
  claims:
    id:
    - sub 
    preferredUsername:
    - preferred_username
    name:
    - name
    email:
    - email
  urls:
    authorize: https://myidp.example.com/oauth2/authorize 
    token: https://myidp.example.com/oauth2/token
```

As an aside, if you want to allow password based auth through the cli tooling, there will need to be an additional identity provider configured to handle for challenge auth, since the OpenID provider does not support challenge auth
