### ISSUE TITLE
Fail to upgrade Origin after updating openshift-ansible to the latest release

### ISSUE THREAD

**Issue by macedogm** [openshift/openshift-ansible#2167]
Hi. I have updated openshift-ansible today to the latest release. I tried to update Origin to v1.2.1 with the following command:

`# ansible-playbook -i /etc/ansible/hosts  openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_2/upgrade.yml`

But it failed with this error:

```
TASK: [openshift_version | fail ] ********************************************* 
failed: [master-1.paas.srv.srvr.rbs.net] => {"failed": true}
msg: Detected openshift version 1.2.0 does not match requested openshift_release 3.2. 
You may need to adjust your yum repositories or specify an exact openshift_pkg_version. 
FATAL: all hosts have already failed -- aborting
```

I  have made this procedure many times before and never got this type of error.
Does anyone knows what this error can be?

Thanks in advance.

**Comment by dgoodwin** [comment]
@macedogm a bug in my recent work, the upgrade playbook is overriding openshift_release to v3.2 (OpenShift Enterprise behavior), I forgot about origin upgrade here.

I'll get you a fix as soon as possible.

If you'd like to work around the issue immediately, edit /playbooks/common/openshift-cluster/upgrades/v3_1_to_v3_2/pre.yml and look for:


```
- include: ../../../../common/openshift-cluster/initialize_openshift_version.yml
  vars:
    # Request openshift_release 3.2 and let the openshift_version role handle converting this
    # to a more specific version, respecting openshift_image_tag and openshift_pkg_version if
    # defined, and overriding the normal behavior of protecting the installed version
    openshift_release: "3.2"
```

Change 3.2 to 1.2 there.

You likely will also need openshift_image_tag=v1.2.1 in your inventory if you don't already have it.

**Comment by macedogm** [comment]
@dgoodwin no problem with that! I did the workaround as you told, but I got a new error.

```
TASK: [Verify OpenShift 3.2 RPMs are available for upgrade] ******************* 
failed: [node-1.paas.srv.srvr.rbs.net] => {"failed": true}
msg: OpenShift 1.2.0 is available, but 3.2 or greater is required
failed: [master-1.paas.srv.srvr.rbs.net] => {"failed": true}
msg: OpenShift 1.2.0 is available, but 3.2 or greater is required

FATAL: all hosts have already failed -- aborting
```

So I changed  version_compare('3.2', '<') in /playbooks/common/openshift-cluster/upgrades/v3_1_to_v3_2/pre.yml from this:
```
  - name: Verify OpenShift 3.2 RPMs are available for upgrade
    fail:
      msg: "OpenShift {{ avail_openshift_version.stdout }} is available, but 3.2 or greater is required"
    when: not openshift.common.is_containerized | bool and not avail_openshift_version | skipped and avail_openshift_version.stdout | default('0.0', True) | version_compare('3.2', '<')
```

To this  version_compare('1.2', '<'):
```
  - name: Verify OpenShift 3.2 RPMs are available for upgrade
    fail:
      msg: "OpenShift {{ avail_openshift_version.stdout }} is available, but 3.2 or greater is required"
    when: not openshift.common.is_containerized | bool and not avail_openshift_version | skipped and avail_openshift_version.stdout | default('0.0', True) | version_compare('1.2', '<')
```

And the upgrade executed without errors, but I believe that it actually did not worked as expected.
```
# openshift version 
openshift v1.2.0
```

Please, correct me if I am wrong.
