### ISSUE TITLE
Support setting the deserialization-cache-size option in the master-config.yaml

### ISSUE THREAD

**Issue by sjenning** [openshift/openshift-ansible#2197]
https://github.com/openshift/openshift-docs/pull/2542

Example:
```
kubernetesMasterConfig:
  apiServerArguments:
    deserialization-cache-size:
    - "1000"
```

@ncdc @adellape @smarterclayton
