### ISSUE TITLE
Unattended atomic-openshift-installer fails

### ISSUE THREAD

**Issue by relaxdiego** [openshift/openshift-ansible#2200]
I'd like to reiterate @ganhuang's concerns with https://github.com/openshift/openshift-ansible/pull/1778#issuecomment-223903971 that have not been addressed and I'm currently experiencing in production. Specifically, the installer.cfg.yml generated by "atomic-openshift-installer install":

```yml
ansible_callback_facts_yaml: /home/ghuang/.config/openshift/.ansible/callback_facts.yaml
ansible_config: /usr/share/atomic-openshift-utils/ansible.cfg
ansible_inventory_path: /home/ghuang/.config/openshift/hosts
ansible_log_path: /tmp/ansible.log
ansible_ssh_user: root
deployment:
  hosts:
  - connect_to: 10.x.x.x
    containerized: true
    hostname: 10.x.x.x
    ip: 10.x.x.x
    public_hostname: 10.x.x.x
    public_ip: 10.x.x.x
    roles:
    - master
    - node
    - storage
  master_routingconfig_subdomain: ''
  proxy_exclude_hosts: ''
  proxy_http: ''
  proxy_https: ''
  roles: {}
variant: openshift-enterprise
variant_version: '3.2'
version: v2
```

Trigger the unattended mode with installer.cfg.yml above

```
# atomic-openshift-installer -u install
Any roles assigned to hosts must be defined.
```

The workaround to this is to manually change the empty roles dict from:

```yml
roles: {}
```

to 

```yml
roles:
  master:
    containerized: false
  storage:
    containerized: false
  node:
    containerized: false
```

However, while I've gotten past the original problem, I'm now encountering a different error. I manually added a master lb to the installer.cfg.yml:

```yml
- connect_to: lb.sample.com
  hostname: lb.sample.com
  ip: 1.2.3.4
  public_hostname: lb.sample.com
  public_ip: 1.2.3.4
  roles:
  - master_lb
```

and the following role in the same file:

```yml
deployment:
  ...
  roles:
    ...
    master_lb:
      preconfigured: true
```

Re-running `atomic-openshift-installer --unattended install` yields the following:

```
*** Installation Summary ***

Hosts:
- 10.10.10.7
  - OpenShift Master
  - OpenShift Node (Unscheduled)
  - Etcd Member
  - Storage
- 10.10.10.8
  - OpenShift Master
  - OpenShift Node (Unscheduled)
  - Etcd Member
- 10.10.10.9
  - OpenShift Master
  - OpenShift Node (Unscheduled)
  - Etcd Member
- 10.10.10.10
  - OpenShift Node (Dedicated)
- 10.10.10.11
  - OpenShift Node (Dedicated)
- lb.sample.com
  - Load Balancer (Preconfigured)

Total OpenShift Masters: 3
Total OpenShift Nodes: 5

NOTE: Multiple Masters specified, this will be an HA deployment with a separate
etcd cluster. You will be prompted to provide the FQDN of a load balancer and
a host for storage once finished entering hosts.


WARNING: A minimum of 3 dedicated Nodes are recommended for an HA
deployment.

Gathering information from hosts...
ERROR: /root/.config/openshift/hosts:6: child group is not defined: (master_lb)
There was a problem fetching the required information. Please see /tmp/ansible.log for details
```

As you can see, the installer recognizes the `master_lb` role based on the summary. However, it is not producing the correct group in the hosts file resulting in the error at the bottom.
