### ISSUE TITLE
Support upgrading to protobuf

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#2214]
Starting with 1.3, it will be possible to use protobuf for internal communications between node, masters, and controllers.  To configure this, the following stanzas need to be altered in the following configurations:

```
# master-config.yaml:

masterClients:
  externalKubernetesClientConnectionOverrides:
    acceptContentTypes: application/vnd.kubernetes.protobuf,application/json
    contentType: application/vnd.kubernetes.protobuf
    burst: 400
    ops: 200
  externalKubernetesKubeConfig: ""
  openshiftLoopbackClientConnectionOverrides:
    acceptContentTypes: application/vnd.kubernetes.protobuf,application/json
    contentType: application/vnd.kubernetes.protobuf
    burst: 600
    ops: 300
  openshiftLoopbackKubeConfig: openshift-master.kubeconfig

# node-config.yaml:

masterClientConnectionOverrides:
  acceptContentTypes: application/vnd.kubernetes.protobuf,application/json
  contentType: application/vnd.kubernetes.protobuf
  burst: 40
  ops: 20
```

Note that if you run create-nodeconfig or create a master config directly, you will get these stanzas set automatically.  However, existing clusters *must* be upgraded.

If you try to upgrade these at the same time as rolling out 1.3 code, you will need to do the following:

1. Update the masters to have new code
2. Update clients:
  1. Update the controllers and change their config
  2. Update the nodes and change their config

Otherwise, you can make these changes after all components are running 1.3.
