### ISSUE TITLE
enable service-serving-cert-signer by default

### ISSUE THREAD

**Issue by deads2k** [openshift/openshift-ansible#2345]
Commands like `oadm router` want to take advantage of the service-serving-cert-signing controller.  This requires that 
```yaml
controllerConfig:
  serviceServingCert:
    signer:
      certFile: service-signer.crt
      keyFile: service-signer.key
```

in the master-config.yaml be configured with a signer.  This signs for internal DNS names and can be created using a command like:

```bash
oadm ca create-signer-cert --cert=service-signer.crt --key=service-signer.key --serial=service-signer-serial.txt
```

https://github.com/openshift/openshift-docs/pull/2324 has docs about using it.
