### ISSUE TITLE
No chance to unset BuildDefaults environment variables

### ISSUE THREAD

**Issue by jkroepke** [openshift/openshift-ansible#2352]
Hi,

we have an internal openshift cluster. For downloading docker images from RedHat, I have to configure a proxy:

```
openshift_http_proxy='http://proxy.ose:3128/'
openshift_https_proxy='http://proxy.ose:3128/'
openshift_no_proxy='172.30.21.246,172.30.136.227'
openshift_generate_no_proxy_hosts=True
```

After rerun the config playbook, I have this configuration in master-config.yml

```
kubernetesMasterConfig:
  admissionConfig:
    pluginConfig:
      BuildDefaults:
        configuration:
          apiVersion: v1
          env:
          - name: HTTP_PROXY
            value: http://proxy.ose:3128/
          - name: HTTPS_PROXY
            value: http://proxy.ose:3128/
          - name: NO_PROXY
            value: .cluster.local,<some nodes>
          - name: http_proxy
            value: http://proxy.ose:3128/
          - name: https_proxy
            value: http://proxy.ose:3128/
          - name: no_proxy
            value: .cluster.local,<some nodes>
          gitHTTPSProxy: http://proxy.ose:3128/
          kind: BuildDefaultsConfig
```

Our build does not require an internet connections. I do not want default proxy options for alle builds.

I have try to set this in my inventory:

```
openshift_builddefaults_http_proxy=' '
openshift_builddefaults_https_proxy=' '
openshift_builddefaults_no_proxy=' '
openshift_builddefaults_git_http_proxy=' '
openshift_builddefaults_git_https_proxy=' '
openshift_builddefaults_json='{"BuildDefaults":{"configuration":{"apiVersion":"v1","kind":"BuildDefaultsConfig"}}}'
```

But it does not have an effect.

Using ansible 2.2 and tag 3.2.24 

Jan
