### ISSUE TITLE
openshift_master_session_max_seconds seems to be ineffective

### ISSUE THREAD

**Issue by gravis** [openshift/openshift-ansible#2408]
Hi,

I have updated the session expiration in our playbook: 

``` python
# Session options
# openshift_master_session_name=ssn
openshift_master_session_max_seconds=864000
```

But I'm still logged out everyday. 
Any Idea why?

**Comment by hzgraham** [comment]
I tested an install with that setting and /etc/origin/master/master-config.yaml was set with that value
```
 sessionConfig:
    sessionMaxAgeSeconds: 864000
    sessionName: ssn
    sessionSecretsFile: /etc/origin/master/session-secrets.yaml
```
Is the issue that this was being set correctly for you, but you are still being logged out?

Also, what version are you running?
