### ISSUE TITLE
policyConfig.openshiftInfrastructureNamespace addition to master config

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-ansible#276]
https://github.com/openshift/origin/pull/2777/files#diff-381e09db7a55a712234f2c2413f7d987 adds a configurable namespace used to hold infrastructure components. Currently, those consist of the service accounts used to run build controllers, replication controllers, and deployment controllers.

The option appears in the master config file under the policyConfig stanza:
```
policyConfig:
  bootstrapPolicyFile: ""
  openshiftInfrastructureNamespace: ""
  openshiftSharedResourcesNamespace: ""
...
```

If unspecified, the default value is "openshift-infra"
