### ISSUE TITLE
Unable to start service docker: Failed to start docker.service: Unit not found.

### ISSUE THREAD

**Issue by cooktheryan** [openshift/openshift-ansible#2792]
[provide a description of the issue]
On nodes the system.d file seems to be missing. On the masters the file exists but on the nodes it does not. With the file missing this stops the docker service from started and then the installation fails.

##### Version
[if you're operating from a git clone provide the output of `git describe`]
[if you're running from playbooks installed via RPM or atomic-openshift-utils `rpm -q atomic-openshift-utils openshift-ansible`]
[Your version of ansible, `ansible --version`]
```
openshift-ansible-3.4.17-1-73-gb29e934
[root@openshift-ose-aws-slave openshift-ansible]# ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
[root@openshift-ose-aws-slave openshift-ansible]# rpm -qa | grep ansible
ansible-2.2.0.0-3.el7.noarch
```
##### Steps To Reproduce
1. Launching new cluster 
2. Run /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
3. Wait until docker attempts to start on nodes

##### Current Result
```
TASK [docker : Install Docker] *************************************************
ok: [ose-master03.ci.sysdeseng.com]
ok: [ose-app-node01.ci.sysdeseng.com]
ok: [ose-infra-node01.ci.sysdeseng.com]
ok: [ose-master02.ci.sysdeseng.com]
ok: [ose-infra-node02.ci.sysdeseng.com]
ok: [ose-master01.ci.sysdeseng.com]
ok: [ose-app-node02.ci.sysdeseng.com]

TASK [docker : Ensure docker.service.d directory exists] ***********************
changed: [ose-infra-node01.ci.sysdeseng.com]
changed: [ose-app-node01.ci.sysdeseng.com]
changed: [ose-infra-node02.ci.sysdeseng.com]
ok: [ose-master03.ci.sysdeseng.com]
ok: [ose-master01.ci.sysdeseng.com]
changed: [ose-app-node02.ci.sysdeseng.com]
ok: [ose-master02.ci.sysdeseng.com]

TASK [docker : Configure Docker service unit file] *****************************
ok: [ose-master01.ci.sysdeseng.com]
ok: [ose-master03.ci.sysdeseng.com]
ok: [ose-master02.ci.sysdeseng.com]
changed: [ose-infra-node01.ci.sysdeseng.com]
changed: [ose-app-node01.ci.sysdeseng.com]
changed: [ose-infra-node02.ci.sysdeseng.com]
changed: [ose-app-node02.ci.sysdeseng.com]

TASK [docker : Start the Docker service] ***************************************
fatal: [ose-infra-node02.ci.sysdeseng.com]: FAILED! => {
    "changed": false, 
    "failed": true
}

MSG:

Unable to start service docker: Failed to start docker.service: Unit not found.


fatal: [ose-app-node01.ci.sysdeseng.com]: FAILED! => {
    "changed": false, 
    "failed": true
}

MSG:

Unable to start service docker: Failed to start docker.service: Unit not found.


ok: [ose-master01.ci.sysdeseng.com]
fatal: [ose-infra-node01.ci.sysdeseng.com]: FAILED! => {
    "changed": false, 
    "failed": true
}

MSG:

Unable to start service docker: Failed to start docker.service: Unit not found.


ok: [ose-master03.ci.sysdeseng.com]
fatal: [ose-app-node02.ci.sysdeseng.com]: FAILED! => {
    "changed": false, 
    "failed": true
}

MSG:

Unable to start service docker: Failed to start docker.service: Unit not found.


ok: [ose-master02.ci.sysdeseng.com]
```

When manually going to the node and attempting to start. It appears the file is missing
```
[root@ip-10-20-5-105 ~]# systemctl restart docker
Failed to restart docker.service: Unit not found.
[root@ip-10-20-5-105 ~]# rpm -qa | grep docker
docker-common-1.10.3-57.el7.x86_64
docker-rhel-push-plugin-1.10.3-57.el7.x86_64
docker-1.10.3-57.el7.x86_64
docker-selinux-1.10.3-57.el7.x86_64
[root@ip-10-20-5-105 ~]# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─custom.conf
   Active: inactive (dead)
     Docs: http://docs.docker.com
```
##### Expected Result
Docker starts as expected.

##### Additional Information
[The exact command you ran]
```
ansible-playbook -i inventory/aws/hosts -e 'public_hosted_zone=ci.sysdeseng.com 
wildcard_zone=ci.sysdeseng.com console_port=443 deployment_type=openshift-enterprise 
rhsm_user=nope@nope.com rhsm_password=nope rhsm_pool=Employee SKU region=us-east-1 
byo_bastion=no ci=true stack_name=openshift-infra' playbooks/openshift-install.yaml
- include: /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml 
  vars:
    debug_level: 2
    openshift_debug_level: "{{ debug_level }}"
    openshift_node_debug_level: "{{ node_debug_level | default(debug_level, true) }}"
    osm_controller_args:
      cloud-provider:
      - "aws"
    osm_api_server_args:
      cloud-provider:
      - "aws"
    openshift_node_kubelet_args:
      cloud-provider:
      - "aws"
      node-labels:
      - "role={{ openshift_node_labels.role }}"
    openshift_master_debug_level: "{{ master_debug_level | default(debug_level, true) }}"
    openshift_master_access_token_max_seconds: 2419200
    openshift_master_api_port: "{{ console_port }}"
    openshift_master_console_port: "{{ console_port }}"
    osm_cluster_network_cidr: 172.16.0.0/16
    openshift_registry_selector: "role=infra"
    openshift_router_selector: "role=infra"
    openshift_hosted_router_replicas: 2
    openshift_hosted_registry_replicas: 2
    openshift_master_cluster_method: native
    openshift_node_local_quota_per_fsgroup: 512Mi
    openshift_cloudprovider_kind: aws
    openshift_master_cluster_hostname: "internal-openshift-master.{{ public_hosted_zone }}"
    openshift_master_cluster_public_hostname: "openshift-master.{{ public_hosted_zone }}"
    osm_default_subdomain: "{{ wildcard_zone }}"
    osm_default_node_selector: "role=app"
    deployment_type: openshift-enterprise
    openshift_master_identity_providers:
    - name: github
      kind: GitHubIdentityProvider
      login: true
      challenge: false
      mapping_method: claim
      clientID: e76865557b0417387b35 
      clientSecret: 72b36e28221c1b93089ecf72f1a19963a8532b06 
      organizations:
      - openshift
    osm_use_cockpit: false
    containerized: false
```
[Your operating system and version, ie: RHEL 7.2, Fedora 23]
Workstation RHEL 7 lauching into RHEL 7.2 and RHEL 7.3 seperately but same result
[Your inventory file]
[visit https://docs.openshift.org/latest/welcome/index.html]
