### ISSUE TITLE
Origin 1.3 upgrade to 1.4 on RHEL fails because etcd-3.0.x RPMs aren't available

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#3027]
I assume this is because on RHEL / OCP we have etcd-3.0.x in our channels, but is not in the centos / epel channels yet?

@sdodson

**Comment by smarterclayton** [comment]
I'm wondering if this should have a check like Docker:

```
- fail:
    msg: This playbook requires access to Docker 1.10 or later
  # Disable the 1.10 requirement if the user set a specific Docker version
  when: docker_version is not defined and (docker_upgrade is not defined or docker_upgrade | bool == True) and (pkg_check.rc == 0 and (avail_docker_version.stdout == "" or avail_docker_version.stdout | version_compare('1.10','<')))
```

in the preflight.
