### ISSUE TITLE
origin-master service wont start with proxy configured 

### ISSUE THREAD

**Issue by aerialls** [openshift/openshift-ansible#3180]
#### Description

On a clean server, the default BYO is not working with proxy configured. 

##### Version

ansible 2.2.0.0
openshift-ansible-3.5.2-1-2-gc5a1e1e

##### Steps To Reproduce

1. Use the following config https://gist.github.com/aerialls/f45abab663233d5f2a63eda37d6f8789
2. Launch ansible with `ansible-playbook playbooks/byo/config.yml`

##### Expected Results

The service origin-master starts successfully.

##### Observed Results

The origin-master is not starting.

```
TASK [openshift_master : Start and enable master] ******************************
FAILED - RETRYING: TASK: openshift_master : Start and enable master (1 retries left).
fatal: [os01.foobar.com]: FAILED! => {"attempts": 1, "changed": false, "failed": true, "msg": "Unable to start service origin-master: Job for origin-master.service failed because the control process exited with error code. See \"systemctl status origin-master.service\" and \"journalctl -xe\" for details.\n"}
```

In the server logs, I can see the following error

```
Jan 25 16:34:13 os01 origin-master: F0125 16:34:13.845990    3399 plugins.go:140] Couldn't init admission plugin "BuildDefaults": error reading config: [pos 197]: json: expect char '"' but got char '['
```

If the lines `openshift_http_proxy` and `openshift_https_proxy` are commented, the service starts. 

##### Additional Information

I'm using `CentOS Linux release 7.3.1611 (Core)`

**Comment by abutcher** [comment]
Hey @aerialls, what does that section of your `/etc/origin/master/master-config.yaml` look like when it fails? I'd expect the `BuildDefaults` plugin to look something like this based on your inventory but it must not be formatted correctly.

```
admissionConfig:
  pluginConfig:
    BuildDefaults:
      configuration:
        apiVersion: v1
        env:
        - name: HTTP_PROXY
          value: http://proxy.foobar.com:8080
        - name: HTTPS_PROXY
          value: http://proxy.foobar.com:8080
        - name: NO_PROXY
          value: .foobar.com
        gitHTTPProxy: http://proxy.foobar.com:8080
        gitHTTPSProxy: http://proxy.foobar.com:8080
        kind: BuildDefaultsConfig
```

**Comment by aerialls** [comment]
Hey @abutcher! Thanks for the quick answer.

The config is currently this one:
```
admissionConfig:
  pluginConfig:
    BuildDefaults:
      configuration:
        apiVersion: v1
        env:
        - name: HTTP_PROXY
          value: http://proxy.foobar.com:8080
        - name: HTTPS_PROXY
          value: http://proxy.foobar.com:8080
        - name: NO_PROXY
          value:
          - .cluster.local
          - .foobar.com
          - os01.foobar.com
        - name: http_proxy
          value: http://proxy.foobar.com:8080
        - name: https_proxy
          value: http://proxy.foobar.com:8080
        - name: no_proxy
          value:
          - .cluster.local
          - .foobar.com
          - os01.foobar.com
        gitHTTPProxy: http://proxy.foobar.com:8080
        gitHTTPSProxy: http://proxy.foobar.com:8080
        gitNoProxy:
        - .cluster.local
        - .foobar.com
        - os01.foobar.com
        kind: BuildDefaultsConfig
        resources:
          limits: {}
          requests: {}
```

**Comment by aerialls** [comment]
In addition if it helps, the only '[' character in the file is way below:

```
kubernetesMasterConfig:
  apiServerArguments:
  controllerArguments:
  masterCount: 1
  masterIP: 172.22.3.245
  podEvictionTimeout:
  proxyClientInfo:
    certFile: master.proxy-client.crt
    keyFile: master.proxy-client.key
  schedulerArguments:
  schedulerConfigFile: /etc/origin/master/scheduler.json
  servicesNodePortRange: ""
  servicesSubnet: 172.30.0.0/16
  staticNodeNames: []
```
