### ISSUE TITLE
IDEMPOTENCY - Are you command/shell grepping?

### ISSUE THREAD

**Issue by tbielawa** [openshift/openshift-ansible#3335]
# Description

We do a lot of 'greps' in the code base. There is no grep module. And `lineinfile` will change files. This is not cool because running cmd/shell is overkill/hacky for just checking if a string is in a file.

# What can you do instead?

Take this snippet from [playbooks/common/openshift-cluster/upgrades/post_control_plane.yml](https://github.com/openshift/openshift-ansible/blob/master/playbooks/common/openshift-cluster/upgrades/post_control_plane.yml#L70) for example:

```yaml
# Check for warnings to be printed at the end of the upgrade:
- name: Check for warnings
  hosts: oo_masters_to_config
  tasks:
  # Check if any masters are using pluginOrderOverride and warn if so, only for 1.3/3.3 and beyond:
  - command: >
      grep pluginOrderOverride {{ openshift.common.config_base }}/master/master-config.yaml
    register: grep_plugin_order_override
    when: openshift.common.version_gte_3_3_or_1_3 | bool
    failed_when: false

  - name: Warn if pluginOrderOverride is in use in master-config.yaml
    debug: msg="WARNING pluginOrderOverride is being deprecated in master-config.yaml, please see https://docs.openshift.com/enterprise/latest/architecture/additional_concepts/admission_controllers.html for more information."
    when: not grep_plugin_order_override | skipped and grep_plugin_order_override.rc == 0
```

# So, what do?

What can you do different? Use the [`find` module](http://docs.ansible.com/ansible/find_module.html) instead.

```yaml
# Check for warnings to be printed at the end of the upgrade:
- name: Check for warnings
  hosts: oo_masters_to_config
  tasks:
  # Check if any masters are using pluginOrderOverride and warn if so, only for 1.3/3.3 and beyond:
  - name : Check if any masters are using pluginOrderOverride and warn if so
    find:
      paths: "{{ openshift.common.config_base }}/master/"
      patterns: "master-config.yaml"
      contains: "pluginOrderOverride"
    register: grep_plugin_order_override
    when:
      - openshift.common.version_gte_3_3_or_1_3 | bool

  - name: Warn if pluginOrderOverride is in use in master-config.yaml
    debug: msg="WARNING pluginOrderOverride is being deprecated in master-config.yaml, please see https://docs.openshift.com/enterprise/latest/architecture/additional_concepts/admission_controllers.html for more information."
    when:
      - not grep_plugin_order_override | skipped
      - grep_plugin_order_override.matched > 0
```

* No more `failed_when` because it's not necessary, if no files are matched the task won't fail, it will just report **0** for `results.matched`.
* It will never report `changed: true` because it only inspects, never modifies. We don't rely on command return codes, we instead check the results of the task to see if there was a match.

# Got any thoughts?
