### ISSUE TITLE
openshift_manage_node Handle scheduleable node fails

### ISSUE THREAD

**Issue by dlbewley** [openshift/openshift-ansible#336]
Testing with Vagrant and VirtualBox on OS X.

After workaround in #331 and running the following to clear the decks:

```sh
#!/bin/bash
for node in node1 node2 master; do
	vagrant destroy -f $node;
done
vagrant up --no-provision
vagrant provision
```

The `openshift_manage_node` role fails on task `Handle scheduleable node`:

```
PLAY [Set scheduleability] ****************************************************

GATHERING FACTS ***************************************************************
ok: [master]

TASK: [set_fact ] *************************************************************
ok: [master]

TASK: [openshift_manage_node | Handle unscheduleable node] ********************
skipping: [master]

TASK: [openshift_manage_node | Handle scheduleable node] **********************
failed: [master] => (item=ose3-node1.example.com) => {"changed": true, "cmd": ["oadm", "manage-node", "ose3-node1.example.com", "--schedulable=true"], "delta": "0:00:00.349934", "end": "2015-07-09 16:51:20.779399", "item": "ose3-node1.example.com", "rc": 1, "start": "2015-07-09 16:51:20.429465", "warnings": []}
stderr: error: No nodes found
failed: [master] => (item=ose3-node2.example.com) => {"changed": true, "cmd": ["oadm", "manage-node", "ose3-node2.example.com", "--schedulable=true"], "delta": "0:00:00.367002", "end": "2015-07-09 16:51:21.437465", "item": "ose3-node2.example.com", "rc": 1, "start": "2015-07-09 16:51:21.070463", "warnings": []}
stderr: error: No nodes found

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/dlbewley/config.retry

localhost                  : ok=5    changed=0    unreachable=0    failed=0
master                     : ok=59   changed=27   unreachable=0    failed=1
node1                      : ok=46   changed=20   unreachable=0    failed=0
node2                      : ok=46   changed=20   unreachable=0    failed=0
```

- node1

```
[vagrant@ose3-node1 ~]$ systemctl status openshift-node
openshift-node.service - OpenShift Node
   Loaded: loaded (/usr/lib/systemd/system/openshift-node.service; enabled)
  Drop-In: /usr/lib/systemd/system/openshift-node.service.d
           └─openshift-sdn-ovs.conf
   Active: active (running) since Thu 2015-07-09 16:51:17 UTC; 6min ago
     Docs: https://github.com/openshift/origin
 Main PID: 16193 (openshift)
   CGroup: /system.slice/openshift-node.service
           └─16193 /usr/bin/openshift start node --config=/etc/openshift/node/node-config.yaml --loglevel=4
```

- master

```
[vagrant@ose3-master ~]$ oc get all
NAME      TYPE      SOURCE
NAME      TYPE      STATUS    POD
NAME      DOCKER REPO   TAGS      UPDATED
NAME      TRIGGERS   LATEST VERSION
CONTROLLER   CONTAINER(S)   IMAGE(S)   SELECTOR   REPLICAS
NAME      HOST/PORT   PATH      SERVICE   LABELS
NAME            LABELS                                    SELECTOR   IP(S)        PORT(S)
kubernetes      component=apiserver,provider=kubernetes   <none>     172.30.0.2   443/TCP
kubernetes-ro   component=apiserver,provider=kubernetes   <none>     172.30.0.1   80/TCP
NAME      READY     REASON    RESTARTS   AGE

[vagrant@ose3-master ~]$ oc get nodes
NAME                     LABELS                                          STATUS
ose3-node1.example.com   kubernetes.io/hostname=ose3-node1.example.com   Ready
ose3-node2.example.com   kubernetes.io/hostname=ose3-node2.example.com   Ready
```

- running by hand seems to work?

```
[vagrant@ose3-master ~]$ oadm manage-node ose3-node1.example.com --schedulable=true
NAME                     LABELS                                          STATUS
ose3-node1.example.com   kubernetes.io/hostname=ose3-node1.example.com   Ready
[vagrant@ose3-master ~]$ echo $?
0
```

**Comment by detiber** [comment]
@dlbewley you may be hitting this: https://github.com/openshift/openshift-ansible/pull/332

**Comment by dlbewley** [comment]
That doesn't fix it.

After applying https://github.com/brenton/openshift-ansible/commit/feb192761a182a82cb1db9e53ac9fce58455c21f.diff from #332 I eventually get a max tries failure which dumps a huge blob of output from the prior yum openshift-node task.

```
PLAY [Set scheduleability] ****************************************************

GATHERING FACTS ***************************************************************
ok: [master]

TASK: [set_fact ] *************************************************************
ok: [master]

TASK: [openshift_manage_node | Wait for Node Registration] ********************
failed: [master -> master] => (item={u'ansible_product_version': u'1.2', 'node_install_result':
...lots and lots of json...
ver.crt", "stat": {"exists": false}}]}}, "rc": 1, "start": "2015-07-09 23:00:34.448332", "warnings": []}
stderr: when passing arguments in resource/name form, all arguments must include the resource
msg: Task failed as maximum retries was encountered

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/dlbewley/config.retry

localhost                  : ok=5    changed=0    unreachable=0    failed=0
master                     : ok=59   changed=27   unreachable=0    failed=1
node1                      : ok=46   changed=20   unreachable=0    failed=0
node2                      : ok=46   changed=20   unreachable=0    failed=0
```

More complete output available in https://gist.github.com/dlbewley/26c7ca655975f7157062

**Comment by dlbewley** [comment]
I found that `openshift_nodes` is a large dict, not a list. By adding some debug tasks like this:

```yaml
- name: Debug info openshift_scheduleable_nodes
  debug: msg="{{openshift_scheduleable_nodes}}"

- name: Debug info openshift_unscheduleable_nodes
  debug: msg="{{openshift_unscheduleable_nodes}}"

- name: Debug info openshift_nodes
  debug: msg="{{openshift_nodes}}"
```

That is why this fails:

```yaml
- name: Wait for Node Registration
  delegate_to: "{{ openshift_first_master }}"
  command: >
      {{ openshift.common.client_binary }} get node {{ item }}
  register: omd_get_node
  until: omd_get_node.rc == 0
  retries: 10
  delay: 5
  with_items: {{ openshift_nodes }}
```

Hard coding the items fixes this issue:

```yaml
- name: Wait for Node Registration
  delegate_to: "{{ openshift_first_master }}"
  command: >
      {{ openshift.common.client_binary }} get node {{ item }}
  register: omd_get_node
  until: omd_get_node.rc == 0
  retries: 10
  delay: 5
  with_items: [ 'ose3-node1.example.com', 'ose3-node2.example.com' ]
```

And now the common Ansible refrain, what is the proper var to use in the `with_items` above?

I'm not sure if this is preferred, but dipping into the openshift_nodes `item` dict for the hostnames seems to work for me.

```yaml
- name: Wait for Node Registration
  command: >
      {{ openshift.common.client_binary }} get node {{ item.ansible_fqdn }}
  register: omd_get_node
  until: omd_get_node.rc == 0
  retries: 10
  delay: 5
  with_items: {{ openshift_nodes }}
```
