### ISSUE TITLE
LDAP identity provider option added

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-ansible#345]
LDAP password authentication is now supported.

Implementation: https://github.com/openshift/origin/pull/3558 
Docs: https://github.com/openshift/openshift-docs/pull/741

Sample config stanza:
```
  identityProviders:
  - name: "my_ldap_provider"
    challenge: true
    login: true
    provider:
      apiVersion: v1
      kind: LDAPPasswordIdentityProvider
      attributes:
        id:
        - dn
        email:
        - mail
        name:
        - cn
        preferredUsername:
        - uid
      bindDN: ""
      bindPassword: ""
      ca: my-ldap-ca-bundle.crt
      insecure: false
      url: "ldap://ldap.example.com/ou=users,dc=acme,dc=com?uid"
```
