### ISSUE TITLE
Option to add http to https redirect to loadbalancer hosts HAProxy config.

### ISSUE THREAD

**Issue by cameron-scrace** [openshift/openshift-ansible#3478]
When a user tries to access the openshift web console via http it would be nice to redirect to https. This is straightforward to add to the HAProxy config, however when re-running ansible to apply other configuration changes the HAProxy config is overwritten and the redirect is removed. Would it be possible to add an ansible hosts file option that would add the http to https redirect to the HAProxy config?

**Comment by ioggstream** [comment]
I patched the files that way:

```
openshift_loadbalancer_additional_frontends:
  - name: openshift-api-80
      mode: tcp
      options: tcplog
      binds: [ "*:80" ]
      default_backend: openshift-api-80
  - name: openshift-api-443
      mode: tcp
      options: tcplog
      binds: [ "*:443" ]
      default_backend: openshift-api-443

openshift_loadbalancer_additional_backends:
  - name: openshift-api-80
    mode: tcp
    option: tcplog
    balance: source
    servers:
    - name: infra0
      address: 192.168.0.7:80
      opts: check
    - name: infra1
      address: 192.168.0.14:80
      opts: check
  - name: openshift-api-be-443
    mode: tcp
    option: tcplog
    balance: source
    servers:
    - name: infra0
      address: 192.168.0.7:443
      opts: check
    - name: infra1
      address: 192.168.0.14:443
      opts: check

```

And modified the os_firewall settings.
