### ISSUE TITLE
Cannot do OpenShift Origin Disconnected Install - custom yum repo file for alt repo host is being overwritten

### ISSUE THREAD

**Issue by johnr-spindance** [openshift/openshift-ansible#3553]
#### Description

Trying to do a disconnected install of OpenShift Origin... When I run the openshift ansible byo config.yml playbook, it keeps overwriting /etc/yum.repos.d/openshift-ansible-centos-paas-sig.repo on all my nodes. I'm trying to have a custom version of that file that points to a repo server instead of the internet (which OpenShift nodes won't have access to). Any ideas on what to do?

##### Version

Please put the following version information in the code block
indicated below.

ansible 2.2.0.0

If you're operating from a **git clone**:

openshift-ansible-3.3.33-1

##### Steps To Reproduce
1. Place a custom /etc/yum.repos.d/openshift-ansible-centos-paas-sig.repo file on nodes
2. Run playbook: `$ ansible-playbook playbooks/byo/config.yml -vv`
3. Somewhere in the first few minutes, the playbook overwrites /etc/yum.repos.d/openshift-ansible-centos-paas-sig.repo

##### Expected Results
Describe what you expected to happen.

There should be a way to prevent this from happening so I can point to an alternative repo host (for disconnected install)

##### Observed Results
Describe what is actually happening.

I'm not able to use alternative repo host for a disconnected install because openshift-ansible overwrites /etc/yum.repos.d/openshift-ansible-centos-paas-sig.repo in this main.yaml task file:

`roles/openshift_repos/tasks/main.yaml`  - line 41

**Comment by johnr-spindance** [comment]
Perhaps I answered my question... the latest commit on this playbook has a new boolean in there that I may be able to use: https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_repos/tasks/main.yaml#L45

**Comment by detiber** [comment]
You can set `openshift_enable_origin_repo=false` in your inventory.

On a side note, you can use`openshift_additional_repos` to setup your custom repo: https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.origin.example#L118

**Comment by johnr-spindance** [comment]
So I just tried this with the latest release (openshift-ansible-3.3.68-1) and `openshift_enable_origin_repo=false` doesn't seem to prevent the overwrite.

Is the `useopenshift_additional_repos` supposed to override the repos that ansible deploys or are they "in addition to"?

**Comment by johnr-spindance** [comment]
Ok, here is an update to the issue:

`openshift_enable_origin_repo=false` only works if I remove the `| default(True)' in this line: 
https://github.com/openshift/openshift-ansible/blob/openshift-ansible-3.3.68-1/roles/openshift_repos/tasks/main.yaml#L50

**Comment by johnr-spindance** [comment]
So ultimately, this is what worked (reworking the when statement and removing the `| default(true)` filter on the `openshift_enable_origin_repo` var
```
- name: Configure origin yum repositories RHEL/CentOS
  copy:
    src: origin/repos/openshift-ansible-centos-paas-sig.repo
    dest: /etc/yum.repos.d/
  notify: refresh cache
  when:
    - ansible_os_family == "RedHat" and ansible_distribution != "Fedora"
    - openshift_deployment_type == 'origin'
    - not openshift.common.is_containerized | bool
    - openshift_enable_origin_repo
```
