### ISSUE TITLE
es_pvc_pool is being left empty causing fail later on in openshift_logging : Applying /tmp/openshift-logging-ansible-

### ISSUE THREAD

**Issue by Office-Manager** [openshift/openshift-ansible#3584]
#### Description

On a multi master with co located etcd install we notice an issue regarding the claim_name variable not being set correctly for the logging.
In the README.md we see 
/openshift_logging/README.md:- `openshift_logging_es_pvc_prefix`: The prefix for the generated PVCs. Defaults to 'logging-es'

However when running the playbook without defining it we see the yaml for the claim will fail because it has a -0 as the name rather than {{claim_name}}-0 

##### Version
```
ansible --version
ansible 2.2.0.0
  config file = /home/shane/openshift-ansible/ansible.cfg
  configured module search path = Default w/o overrides

git describe
openshift-ansible-3.5.25-1

```

##### Steps To Reproduce
1.  Hosts file without openshift_logging_es_pvc_prefix being defined
2. Run -- ansible-playbook -i hosts playbooks/byo/config.yml 

##### Observed Results
We see the PVC claim fail due to a naming issue. 
```
STDERR:

error: unable to decode "/tmp/openshift-logging-ansible-yGSaGl/templates/logging-logging-es-nfjp57ye-dc.yaml": [pos 1924]: json: expect char '"' but got char '0'
es
```

The file in question is 
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: -0
  labels:
    logging-infra: support
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
```

Where the -0 should of course be claim_name=0

##### Additional Information
A workaround we're using is in the hosts file to explicitly set  
```
#
openshift_logging_es_pvc_prefix=es-logging
#
```

Ansible server:
cat /etc/redhat-release
Fedora release 25 (Twenty Five)

Master //node servers:
cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
