### ISSUE TITLE
oc_scale module has change conflicts sometimes

### ISSUE THREAD

**Issue by ewolinetz** [openshift/openshift-ansible#3773]
Using the oc_scale module uses `oc replace` and at times can have change conflicts.

My relevant tasks:
```
- name: Retrieve elasticsearch
  oc_obj:
    state: list
    kind: dc
    selector: "component=es"
    namespace: "{{openshift_logging_namespace}}"
  register: es_dc

- name: start elasticsearch
  oc_scale:
    kind: dc
    name: "{{ object }}"
    namespace: "{{openshift_logging_namespace}}"
    replicas: 1
  with_items: "{{ es_dc.results.results[0]['items'] | map(attribute='metadata.name') | list }}"
  loop_control:
    loop_var: object
```

And I'll see the following failure in my play:
```
TASK [openshift_logging : Retrieve elasticsearch] ******************************
ok: [54.146.104.80]
 
TASK [openshift_logging : start elasticsearch] *********************************
changed: [54.146.104.80] => (item=logging-es-etryefaf)
failed: [54.146.104.80] (item=logging-es-jqy9lhx2) => {"failed": true, "msg": {"cmd": "/usr/bin/oc replace -f /tmp/logging-es-jqy9lhx2-uFDycI -n logging", "results": {}, "returncode": 1, "stderr": "Error from server (Conflict): error when replacing \"/tmp/logging-es-jqy9lhx2-uFDycI\": Operation cannot be fulfilled on deploymentconfigs \"logging-es-jqy9lhx2\": the object has been modified; please apply your changes to the latest version and try again\n", "stdout": ""}, "object": "logging-es-jqy9lhx2"}
```
