### ISSUE TITLE
oc pods are in error state

### ISSUE THREAD

**Issue by naveenkumartangallapally** [openshift/openshift-ansible#3795]
i have setup openshift environment with one master and one node with the given official URL:https://docs.openshift.com/container-platform/3.4/install_config/install/quick_install.html
i used quick installation method to build openshift envoronment.
after installation completed all pods are falling error state.

```
[root@master1 ~]# oc get nodes
NAME                  STATUS                     AGE
master1.example.com   Ready,SchedulingDisabled   51m
node1.example.com     Ready                      51m

[root@master1 ~]# oc get pods
NAME                        READY     STATUS    RESTARTS   AGE
docker-registry-2-deploy    0/1       Error     0          43m
registry-console-1-deploy   0/1       Error     0          48m
router-1-deploy             0/1       Error     0          48m
```

and this is my hosts file:

```
[root@master1 ~]# cat .config/openshift/hosts

[OSEv3:children]
nodes
nfs
masters
etcd

[OSEv3:vars]
openshift_master_cluster_public_hostname=None
ansible_ssh_user=root
openshift_master_cluster_hostname=None
deployment_type=openshift-enterprise

[nodes]
master1.example.com  openshift_public_ip=103.60.214.202 openshift_ip=192.168.57.50 openshift_public_hostname=master1.example.com openshift_hostname=master1.example.com connect_to=master1.example.com openshift_schedulable=False
node1.example.com  openshift_public_ip=103.60.214.202 openshift_ip=192.168.59.50 openshift_public_hostname=node1.example.com openshift_hostname=node1.example.com connect_to=node1.example.com openshift_node_labels="{'region': 'infra'}" openshift_schedulable=True

[nfs]
master1.example.com  openshift_public_ip=103.60.214.202 openshift_ip=192.168.57.50 openshift_public_hostname=master1.example.com openshift_hostname=master1.example.com connect_to=master1.example.com

[masters]
master1.example.com  openshift_public_ip=103.60.214.202 openshift_ip=192.168.57.50 openshift_public_hostname=master1.example.com openshift_hostname=master1.example.com connect_to=master1.example.com

[etcd]
master1.example.com  openshift_public_ip=103.60.214.202 openshift_ip=192.168.57.50 openshift_public_hostname=master1.example.com openshift_hostname=master1.example.com connect_to=master1.example.com
```

and this is my insttler-config.yaml file:

```
ansible_callback_facts_yaml: /root/.config/openshift/.ansible/callback_facts.yaml
ansible_inventory_path: /root/.config/openshift/hosts
ansible_log_path: /tmp/ansible.log
deployment:
  ansible_ssh_user: root
  hosts:
  - connect_to: master1.example.com
    hostname: master1.example.com
    ip: 192.168.57.50
    public_hostname: master1.example.com
    public_ip: 103.60.214.202
    roles:
    - master
    - etcd
    - node
    - storage
  - connect_to: node1.example.com
    hostname: node1.example.com
    ip: 192.168.59.50
    node_labels: '{''region'': ''infra''}'
    public_hostname: node1.example.com
    public_ip: 103.60.214.202
    roles:
    - node
  master_routingconfig_subdomain: ''
  openshift_master_cluster_hostname: None
  openshift_master_cluster_public_hostname: None
  proxy_exclude_hosts: ''
  proxy_http: ''
  proxy_https: ''
  roles:
    etcd: {}
    master: {}
    node: {}
    storage: {}
variant: openshift-enterprise
variant_version: '3.4'
version: v2
```

and my logs are saying as:

```
[root@master1 ~]# oc get pods
NAME                        READY     STATUS    RESTARTS   AGE
docker-registry-2-deploy    0/1       Error     0          54m
registry-console-1-deploy   0/1       Error     0          59m
router-1-deploy             0/1       Error     0          1h


[root@master1 ~]# oc logs docker-registry-2-deploy
error: couldn't get deployment docker-registry-2: Get https://172.30.0.1:443/api/v1/namespaces/default/replicationcontrollers/docker-registry-2: dial tcp 172.30.0.1:443: getsockopt: connection refused
```

what is my next debug step to solve the issue.
