### ISSUE TITLE
LIBVIRT Setup instructions fail on Fedora 25

### ISSUE THREAD

**Issue by jpkrohling** [openshift/openshift-ansible#4306]
#### Description

When trying to run the playbooks following the `README_libvirt.md` , the execution fails on this step on a Fedora 25 with the latest updates:

```
TASK [Evaluate oo_glusterfs_to_config] ****************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "failed": true
}

MSG:

'g_glusterfs_registry_hosts' is undefined
```

This is the command used for installing: `bin/cluster create libvirt lenaic`

##### Version

* Your ansible version per `ansible --version`
```
ansible 2.3.0.0
  config file = /mnt/storage/jpkroehling/Projects/ansible/src/github.com/openshift/openshift-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

* The output of `git describe`
`openshift-ansible-3.6.85-1-8-gc5f4a60` (using master as of now, commit's SHA: c5f4a60fdd9ebc81180a96677717ca96b9badc72)

##### Steps To Reproduce
1. https://github.com/openshift/openshift-ansible/blob/master/README_libvirt.md

**Comment by Seth-Miller** [comment]
A workaround for this is to define g_glusterfs_registry_hosts in the inventory/libvirt/hosts/hosts file.
```
localhost ansible_connection=local ansible_become=no ansible_python_interpreter='/usr/bin/env python2' g_glusterfs_registry_hosts=[]
```

**Comment by Seth-Miller** [comment]
#3945 fixed a similar issue but in this case, the `Evaluate oo_glusterfs_to_config` task in `playbooks/common/openshift-cluster/evaluate_groups.yml` is trying to apply the union() function to the g_glusterfs_registry_hosts variable which is undefined.

```
  - name: Evaluate oo_glusterfs_to_config
    add_host:
      name: "{{ item }}"
      groups: oo_glusterfs_to_config
      ansible_ssh_user: "{{ g_ssh_user | default(omit) }}"
      ansible_become: "{{ g_sudo | default(omit) }}"
    with_items: "{{ g_glusterfs_hosts | union(g_glusterfs_registry_hosts) | default([]) }}"
    changed_when: no
```
