### ISSUE TITLE
GlusterFS installation not compatible with CentOS Atomic

### ISSUE THREAD

**Issue by juanwolf** [openshift/openshift-ansible#4319]
#### Description

When trying to install GlusterFS on CentOS Atomic, I've got an error 
```
TASK [Make sure heketi-client is installed] ****************************************************************************
fatal: [a.nice.ip.here]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find a module for unknown."}
```

on line 11 in `roles/openshift_storage_glusterfs/tasks/glusterfs_common.yml`

##### Version

* Ansible
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 17 2016, 23:03:43) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```
* Project 
  * Branch: Master
  * Commit:  a353d4daf48f37eb95affcff0cf318d90c055e7a

##### Steps To Reproduce
1. Spin up a VM or EC2 instance with CentOS Atomic
2. Create a simple playbook containing the task. Ex: 
```
# test_centos.yaml
---
- hosts: atomic
  tasks:
    - name: Make sure heketi-client is installed
      package: name=heketi-client state=present
```
3. `ansible-playbook -i inventory test_centos.yaml`

##### Additional Information

* Cloud provider: AWS
* Operating System: CentOS Atomic Host 7 x86_64 HVM EBS 1704_01 (ami-14425570)
