### ISSUE TITLE
Support resource requests in Logging role

### ISSUE THREAD

**Issue by madddi** [openshift/openshift-ansible#4320]
#### Description

I'm able to set resource requests in the metrics deployment role, but not in the logging deployment.

As far as I can see, nobody is working on this yet. If this is the case, I'm going to submit a pull request soon which will add support for resource requests.

**Comment by ewolinetz** [comment]
Have you seen the following?
```yaml
openshift_logging_curator_cpu_limit: 100m
openshift_logging_curator_memory_limit: null
openshift_logging_kibana_cpu_limit: null
openshift_logging_kibana_memory_limit: 736Mi
openshift_logging_kibana_proxy_cpu_limit: null
openshift_logging_kibana_proxy_memory_limit: 96Mi
openshift_logging_fluentd_cpu_limit: 100m
openshift_logging_fluentd_memory_limit: 512Mi
openshift_logging_es_cpu_limit: null
openshift_logging_es_memory_limit: "{{ openshift_hosted_logging_elasticsearch_instance_ram | default('8Gi') }}"

openshift_logging_curator_ops_cpu_limit: 100m
openshift_logging_curator_ops_memory_limit: null
openshift_logging_kibana_ops_cpu_limit: null
openshift_logging_kibana_ops_memory_limit: 736Mi
openshift_logging_kibana_ops_proxy_cpu_limit: null
openshift_logging_kibana_ops_proxy_memory_limit: 96Mi
openshift_logging_es_ops_cpu_limit: null
openshift_logging_es_ops_memory_limit: "{{ openshift_hosted_logging_elasticsearch_ops_instance_ram | default('8Gi') }}"
```
