### ISSUE TITLE
ServiceCatalog needs to enable API aggregation

### ISSUE THREAD

**Issue by deads2k** [openshift/openshift-ansible#4350]
The service catalog relies having a working aggregator which is another alpha feature in 1.7.  To enable it, follow the directions from https://github.com/openshift/origin/pull/14285 which I've copied here:

1. Generate front-proxy-ca cert/key and aggregator-front-proxy-client cert/key.  I did this with
```bash
oadm ca create-signer-cert \
  --cert=aggregator-config/front-proxy-ca.crt \
  --key=aggregator-config/front-proxy-ca.key \
  --serial=aggregator-config/front-proxy-ca.serial.txt

oadm create-api-client-config \
  --certificate-authority=aggregator-config/front-proxy-ca.crt \
  --signer-cert=aggregator-config/front-proxy-ca.crt \
  --signer-key=aggregator-config/front-proxy-ca.key \
  --signer-serial=aggregator-config/front-proxy-ca.serial.txt \
  --user aggregator-front-proxy \
  --client-dir=aggregator-config
```

2. Place desired files in master config dir:
```
cp aggregator-config/{front-proxy-ca.crt,aggregator-front-proxy.crt,aggregator-front-proxy.key} openshift.local.config/master/
```

3. Set up stanzas in master-config.yaml:
```yaml
aggregatorConfig:
  proxyClientInfo:
    certFile: aggregator-front-proxy.crt
    keyFile: aggregator-front-proxy.key
authConfig:
  requestHeader:
    clientCA: front-proxy-ca.crt
    clientCommonNames: 
    - aggregator-front-proxy
    usernameHeaders:
    - X-Remote-User
    groupHeaders:
    - X-Remote-Group
    extraHeaderPrefixes:
    - X-Remote-Extra-
```

@sdodson @jpeeler
