### ISSUE TITLE
cloudforms docker image project has been retagged, and now the cfme templates are broken

### ISSUE THREAD

**Issue by gordillo-ramon-redhat** [openshift/openshift-ansible#4446]
#### Description

Sample image from https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v1.5/cfme-templates/cfme-template.yaml :

registry.access.redhat.com/**cloudforms**/cfme-openshift-app

But

$ docker search registry.access.redhat.com/cloudforms
INDEX        NAME                                                                              DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
redhat.com   registry.access.redhat.com/**cloudforms42**/cfme                                      Red Hat® CloudForms manages private cloud...    0                    
redhat.com   registry.access.redhat.com/**cloudforms42**/cfme-openshift-app                        Red Hat® CloudForms Appliance image to be...    0                    
redhat.com   registry.access.redhat.com/**cloudforms42**/cfme-openshift-memcached                  Memcached image that provides distributed ...   0                    
redhat.com   registry.access.redhat.com/**cloudforms42**/cfme-openshift-postgresql                 Postgresql image that provides database se...   0                    
redhat.com   registry.access.redhat.com/**cloudforms45**/cfme-openshift-app                        Red Hat® CloudForms Appliance image to be...    0                    
redhat.com   registry.access.redhat.com/**cloudforms45**/cfme-openshift-memcached                  Memcached image that provides distributed ...   0                    
redhat.com   registry.access.redhat.com/**cloudforms45**/cfme-openshift-postgresql                 Postgresql image that provides database se...   0                    

##### Version

OCP 3.5

@jorgemoralespou

**Comment by sdodson** [comment]
@simon3z please advise what we need to do here? will the old images come back or are they gone forever?

**Comment by simon3z** [comment]
@sdodson in:

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v1.5/cfme-templates/cfme-template.yaml

The `registry.access.redhat.com/cloudforms45` images are referenced by default:

```yaml
  -
    name: "POSTGRESQL_IMG_NAME"
    displayName: "PostgreSQL Image Name"
    description: "This is the PostgreSQL image name requested to deploy."
    value: "registry.access.redhat.com/cloudforms45/cfme-openshift-postgresql"
  -
    name: "POSTGRESQL_IMG_TAG"
    displayName: "PostgreSQL Image Tag"
    description: "This is the PostgreSQL image tag/version requested to deploy."
    value: "latest"
  -
    name: "MEMCACHED_IMG_NAME"
    displayName: "Memcached Image Name"
    description: "This is the Memcached image name requested to deploy."
    value: "registry.access.redhat.com/cloudforms45/cfme-openshift-memcached"
  -
    name: "MEMCACHED_IMG_TAG"
    displayName: "Memcached Image Tag"
    description: "This is the Memcached image tag/version requested to deploy."
    value: "latest"
  -
    name: "APPLICATION_IMG_NAME"
    displayName: "Application Image Name"
    description: "This is the Application image name requested to deploy."
    value: "registry.access.redhat.com/cloudforms45/cfme-openshift-app"
```

And looking at:

https://access.redhat.com/containers#/search/cfme-openshift-app

I see

- cloudforms42/cfme-openshift-memcached
- cloudforms42/cfme-openshift-app
- cloudforms42/cfme-openshift-postgresql
- cloudforms45/cfme-openshift-memcached
- cloudforms45/cfme-openshift-app
- cloudforms45/cfme-openshift-postgresql

So everything seems fine to me (or maybe I am missing something). I am not sure what are the old images.

@bazulay @gtanzillo @fbladilo
