### ISSUE TITLE
multi-master certificate question

### ISSUE THREAD

**Issue by yangzhares** [openshift/openshift-ansible#449]
hi,

Have a question about creating multi-master certificate in HA ENV needs your help, from *common*->*openshift-master*->*config.yml*, can find a code snippet:
```
- name: Configure master certificates
  hosts: oo_first_master
  vars:
    master_generated_certs_dir: /etc/openshift/generated-configs
    masters_needing_certs: "{{ hostvars
                               | oo_select_keys(groups['oo_masters_to_config'] | difference(groups['oo_first_master']))
                               | oo_filter_list(filter_attr='master_certs_missing') }}"
    sync_tmpdir: "{{ hostvars.localhost.g_master_mktemp.stdout }}"
  roles:
  - openshift_master_certificates
```
a variable `masters_needing_certs` which it indicates only creates multi-master certificate on all masters except `oo_first_master` master,  what's the purpose of this?  why don't create certificate on `oo_first_master` master?  doesn't the first master `oo_first_master` need certificate?

I don't know certificate much more, hope you answer my questions, thanks in advance.

Thanks
