### ISSUE TITLE
oc_pvc errors with 'access_modes' variable

### ISSUE THREAD

**Issue by zgalor** [openshift/openshift-ansible#4893]
#### Description

oc_pvc module returns errors when passed a parameter or when it attempts to use default parameter for access_modes

##### Version

```
ansible 2.3.1.0
  config file = /home/zgalor/dev/openshift-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

openshift-ansible-3.6.153-1-138-g2bf06c6
```

##### Steps To Reproduce
Run this task:
```
- name: create pvc
  oc_pvc:
    namespace: "{{ namespace }}"
    name: "{{ pvc_name }}"
    access_modes:
    - ReadWriteMany
    volume_capacity: "{{ pvc_size }}"
```

##### Expected Results
The pvc should be created

##### Observed Results

```
fatal: [ocp-master01.10.35.48.153.nip.io]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "access_modes": "['ReadWriteMany']", 
            "debug": false, 
            "kubeconfig": "/etc/origin/master/admin.kubeconfig", 
            "name": "prometheus-pvc", 
            "namespace": "prometheus", 
            "state": "present", 
            "volume_capacity": "1G"
        }
    }
}

MSG:

value of access_modes must be one of: ReadWriteOnce,ReadOnlyMany,ReadWriteMany, got: ['ReadWriteMany']
```

##### Additional Information

Also if running without `access_modes` parameter the default value fails
Task:
```
- name: create pvc
  oc_pvc:
    namespace: "{{ namespace }}"
    name: "{{ pvc_name }}"
    volume_capacity: "{{ pvc_size }}"
```

Result:
```
fatal: [ocp-master01.10.35.48.153.nip.io]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "access_modes": "ReadWriteOnce", 
            "debug": false, 
            "kubeconfig": "/etc/origin/master/admin.kubeconfig", 
            "name": "prometheus-pvc", 
            "namespace": "prometheus", 
            "state": "present", 
            "volume_capacity": "1G"
        }
    }
}

MSG:

{u'returncode': 1, u'cmd': u'/usr/bin/oc create -f /tmp/prometheus-pvc-sQivjZ -n prometheus', u'results': {}, u'stderr': u'Error from server (BadRequest): error when creating "/tmp/prometheus-pvc-sQivjZ": PersistentVolumeClaim in version "v1" cannot be handled as a PersistentVolumeClaim: [pos 135]: bytes or string in the stream must be decoded into a slice or array of bytes, not []v1.PersistentVolumeAccessMode\n', u'stdout': u''}
```
