### ISSUE TITLE
Only the first identity provider is configured when you declare multiple providers

### ISSUE THREAD

**Issue by slaterx** [openshift/openshift-ansible#5038]
#### Description

On a single master multiple nodes install, openshift-ansible installs only the first provider defined in the fact openshift_master_identity_providers. 

##### Version

```
ansible 2.3.0.0
openshift-ansible-3.5.111-1 
```

##### Steps To Reproduce
1. Create your hosts file and declare your identity providers: 
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'mappingMethod': 'add', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'},{'name': 'ldap_auth', 'challenge': 'true', 'login': 'true', 'kind': 'LDAPPasswordIdentityProvider', 'attributes': {'id': ['dn'], 'email': ['mail'], 'name': ['cn'], 'preferredUsername': ['uid']}, 'bindDN': 'user', 'bindPassword': 'pass','insecure': 'true', 'url': 'ldap://ldap:389/OU=USERS,DC=dc,DC=com?sAMAccountName'}]
2. Run the byo playbook:
ansible-playbook playbooks/byo/config.yml

##### Expected Results
Two providers to be created in master yaml file - htpasswd and LDAP.

##### Observed Results
Only the first listed provided in the fact is created.

##### Additional Information
Running CentOS 7 and Origin 1.5.1.

Full hosts file:
```
# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# Ansible specific vars
ansible_become=true
ansible_ssh_user=centos

# Basic Openshift parameters
containerized=false
openshift_install_examples=true
openshift_set_hostname=true
openshift_deployment_type=origin
deployment_type=origin
openshift_pkg_version=-1.5.1
openshift_hosted_metrics_deployer_version=v1.5.1
openshift_hosted_metrics_deployer_prefix=openshift/origin-
openshift_override_hostname_check=true
openshift_disable_check=memory_availability,disk_availability,docker_storage

# Openshift cluster settings
openshift_portal_net=172.30.0.0/16
osm_cluster_network_cidr=10.128.0.0/14
openshift_hosted_metrics_deploy=false
openshift_hosted_metrics_public_url=https://hawkular-metrics.example.com/hawkular/metrics
openshift_use_dnsmasq=true
osm_default_node_selector='region=dmz'
osm_custom_cors_origins=['master.example.com', '127.0.0.1', 'kubernetes.default.svc.cluster.local', 'hostname.example.com']
osm_use_cockpit=true
osm_cockpit_plugins=['cockpit-kubernetes']

# Openshift resources
openshift_hosted_router_selector='region=prod,zone=dmz'
openshift_hosted_router_replicas=3
openshift_hosted_registry_selector='region=prod,zone=management'
openshift_master_default_subdomain=os.example.com
openshift_hosted_router_force_subdomain='${name}-${namespace}.os.example.com'
openshift_metrics_master_url='https://master.example.com:8443'
openshift_metrics_startup_timeout=900

# Openshift authentication
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'mappingMethod': 'add', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'},{'name': 'ldap_auth', 'challenge': 'true', 'login': 'true', 'kind': 'LDAPPasswordIdentityProvider', 'attributes': {'id': ['dn'], 'email': ['mail'], 'name': ['cn'], 'preferredUsername': ['uid']}, 'bindDN': 'user', 'bindPassword': 'pass','insecure': 'true', 'url': 'ldap://ldap:389/OU=USERS,DC=dc,DC=com?sAMAccountName'}]
openshift_master_htpasswd_users={'cluster_administration_user': '$apr1$HASH', user_a': '$apr1$HASH.', 'user_b': '$apr1$HASH'}

# host group for masters
[masters]
master.example.com openshift_public_hostname=master.example.com

# host group for nodes, includes region info
[nodes]
master.example.com openshift_public_hostname=master.example.com openshift_schedulable=true openshift_node_labels="{'region': 'prod', 'zone': 'management'}"
host1.example.com openshift_public_hostname=host1.example.com openshift_schedulable=true openshift_node_labels="{'region': 'prod', 'zone': 'dmz'}"
```

**Comment by bbrouwer** [comment]
I am trying to do the exact same thing. Did you ever find a workaround, or do I just need to configure each master post-installation?

**Comment by abutcher** [comment]
@bbrouwer Did you encounter the same problem with only one provider being configured in the master config?

**Comment by abutcher** [comment]
Multiple identity providers is working in my testing with `master` (`openshift-ansible-3.7.0-0.166.0-96-g8c85dd660`) and `release-1.5` (`openshift-ansible-3.5.135-1-6-g6da4bbd70`) branches.

```
oauthConfig:
  assetPublicURL: https://master1.abutcher.com:8443/console/
  grantConfig:
    method: auto
  identityProviders:
  - challenge: true
    login: true
    mappingMethod: add
    name: htpasswd_auth
    provider:
      apiVersion: v1
      file: /etc/origin/master/htpasswd
      kind: HTPasswdPasswordIdentityProvider
  - challenge: true
    login: true
    mappingMethod: claim
    name: ldap_auth
    provider:
      apiVersion: v1
      attributes:
        email:
        - mail
        id:
        - dn
        name:
        - cn
        preferredUsername:
        - uid
      bindDN: user
      bindPassword: pass
      insecure: true
      kind: LDAPPasswordIdentityProvider
      url: ldap://ldap:389/OU=USERS,DC=dc,DC=com?sAMAccountName
```
