### ISSUE TITLE
We should use jinja2 variable expansion to conditionally include roles and task lists

### ISSUE THREAD

**Issue by twiest** [openshift/openshift-ansible#521]
Currently we're using conditional includes for roles and task lists.

Instead, it would be better to use jinja2 variable expansion.

For example:

```

---
- hosts: localhost
  gather_facts: no
  vars:
    somevar: somerole1
  roles:
  - role: "{{ somevar }}"
```
