### ISSUE TITLE
Wrong etcd node hostname in master config

### ISSUE THREAD

**Issue by paralin** [openshift/openshift-ansible#5333]
On master commit dc0e3d218

The etcd hosts are configured with the `openshift_ip` correctly:

```
2017-09-07 20:33:42.843773 I | etcdserver: published {Name:bart.usb.cs.purdue.edu ClientURLs:[https://172.16.1.10:2379]} to cluster d08425
```

But the master config is wrong, using the public URLs instead:

```
etcdClientInfo:
  ca: master.etcd-ca.crt
  certFile: master.etcd-client.crt
  keyFile: master.etcd-client.key
  urls:
    - https://bart.usb.cs.purdue.edu:2379
    - https://lisa.usb.cs.purdue.edu:2379
    - https://marge.usb.cs.purdue.edu:2379
```

cc @smarterclayton
