### ISSUE TITLE
RequestHeaderIdentityProvider adds loginURL and challengeURL parameters

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-ansible#542]
See https://github.com/openshift/origin/pull/4279

RequestHeaderIdentityProvider can now set `login:true` if it includes a `loginURL`
RequestHeaderIdentityProvider can now set `challenge:true` if it includes a `challengeURL`

Example config:

```
  identityProviders:
  - challenge: true
    login: true
    name: authproxyprovider
    provider:
      apiVersion: v1
      challengeURL: "http://myproxy:1234/oauth/authorize?${query}"
      loginURL: "http://myproxy:1234/oauth/authorize?${query}"
      kind: RequestHeaderIdentityProvider
      headers:
      - Remote-User
```
