### ISSUE TITLE
Feature request: registry-console should use openshift service certificates

### ISSUE THREAD

**Issue by ibotty** [openshift/openshift-ansible#5570]
I have a proof of concept with following changes to the deployment and service:

## Generation of the service certificates

Add annotation to service registry-console:
```shell
oc patch svc/registry-console -p '{"metadata": {"annotations": {"service.alpha.openshift.io/serving-cert-secret-name": "registry-console-certs" }}}'
```

## Actually use the service certificates

Because of cockpit-project/cockpit#7763, a init container is needed to get them into the right format for cockpit. So I added the following init container to dc/registry-console.

```yaml
      initContainers:
      - command:
        - /bin/sh
        - -xc
        - cat /run/secrets/registry-console-certs/tls.crt /run/secrets/registry-console-certs/tls.key
          > /etc/cockpit/ws-certs.d/01-openshift-generated.cert
        image: cockpit/kubernetes:latest
        imagePullPolicy: Always
        name: cat-certificates
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/cockpit/ws-certs.d
          name: combined-certs
        - mountPath: /run/secrets/registry-console-certs
          name: registry-console-certs
```
(and the volumes and volumeMounts accordingly).

It would also be great to be able to specify the registry-console's route url.
