### ISSUE TITLE
Ansible fails to add-registry registry.access.redhat.com on Atomic Host

### ISSUE THREAD

**Issue by karthikrmit** [openshift/openshift-ansible#5681]
#### Description

Trying to install Openshift 3.6 using tag openshift-ansible-3.7.0-0.129.0 where the slaves are Atomic Hosts.
Ansible fails to add the default registry --add-registry registry.access.redhat.com to docker runtime on Atomic hosts due to which docker pull openshift3/node:v3.6.173.0.5 fails on the Atomic hosts. But the same passes on RHEL Server node.

I have tried the same with tags 135 and 140 too but no luck.

##### Version

```
*[root@ovs-11 openshift-ansible]# ansible --version
ansible 2.3.1.0
  config file = /root/openshift-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
[root@ovs-11 openshift-ansible]# 

```

If you're operating from a **git clone**:

```
[root@ovs-11 openshift-ansible]# git describe
openshift-ansible-3.7.0-0.129.0
[root@ovs-11 openshift-ansible]# 

```

##### Steps To Reproduce
1. git clone the above mentioned tags  (129 or 135 or 140)
2. Have a cluster setup where the nodes are Atomic hosts 
3. Run ansible-playbook

##### Expected Results

```
Successful install with the default registry path added to docker runtime
```

##### Observed Results

```
--add-registry registry.access.redhat.com missing from docker runtime on Atomic hosts.
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

```
 *[root@ovs-3 docker.service.d]# cat /etc/*release
NAME="Red Hat Enterprise Linux Atomic Host"
VERSION="7.3"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Atomic Host"
VARIANT_ID=atomic.host
VERSION_ID="7.3"
PRETTY_NAME="Red Hat Enterprise Linux Atomic Host 7.3"

```
```
[root@ovs-3 docker.service.d]# cat /etc/containers/registries.conf 
# Ansible managed
# This is a system-wide configuration file used to
# keep track of registries for various container backends.
# It adheres to YAML format and does not support recursive
# lists of registries.

# The default location for this configuration file is /etc/containers/registries.conf.

# The only valid categories are: 'registries', 'insecure_registies',
# and 'block_registries'.


#registries:
#  - registry.access.redhat.com

registries:
  - registry.access.redhat.com

[root@ovs-3 docker.service.d]# systemctl status docker.service -l
\u25cf docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           \u2514\u2500custom.conf
        /usr/lib/systemd/system/docker.service.d
           \u2514\u2500flannel.conf
   Active: active (running) since Thu 2017-10-05 14:25:16 PDT; 3min 56s ago
     Docs: http://docs.docker.com
 Main PID: 63680 (dockerd-current)
   Memory: 20.8M
   CGroup: /system.slice/docker.service
           \u251c\u250063680 /usr/bin/dockerd-current --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current --default-runtime=docker-runc --authorization-plugin=rhel-push-plugin --exec-opt native.cgroupdriver=systemd --userland-proxy-path=/usr/libexec/docker/docker-proxy-current --selinux-enabled --log-driver=journald --storage-driver devicemapper --storage-opt dm.fs=xfs --storage-opt dm.thinpooldev=/dev/mapper/atomicos-docker--pool --storage-opt dm.use_deferred_removal=true --mtu=1450
           \u2514\u250063688 /usr/bin/docker-containerd-current -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --shim docker-containerd-shim --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --runtime docker-runc --runtime-args --systemd-cgroup=true



```
