### ISSUE TITLE
GlusterFS just keeps failing.

### ISSUE THREAD

**Issue by f1gjam** [openshift/openshift-ansible#5788]
#### Description

Anisble run seems to fail when creating a temp folder for gluser

Single Master (etcd on single master)
3 * App nodes (App nodes also run Gluster)

##### Version

I have tried from master and version 3.6 branch

* Your ansible version per `ansible --version`
ansible 2.3.1.0

If you're operating from a **git clone**:

* The output of `git describe`
openshift-ansible-3.7.0-0.158.0-19-g5cca3fdc8

Terraform creates the following machines

1 * Master (Additional Disk for Docker)
3 * App nodes - These have 2 * additional disks (Disks for Docker and GlusterFS) 

I have created a play book as follows

Openshift.yml
```
---
  - include: openshift_pre.yml
  - include: roles/openshift-ansible/playbooks/byo/openshift-cluster/config.yml
```
Openshift_pre - installs all pre-reqs on nodes
```
---

- hosts: all
  tasks:
  - name: Install pre-req packages
    yum: name={{item}} state=latest
    with_items:
      - yum-utils
      - PyYAML

  - name: Update packages
    yum:
      state: latest
      name: '*'

  - name: Install docker
    yum:
      state: latest
      name: docker-1.12.6

  - name: Configure insecure-registry local setting for docker
    lineinfile: dest=/etc/sysconfig/docker
      regexp="^OPTIONS="
      line="OPTIONS='--selinux-enabled --log-driver=journald --signature-verification=false --insecure-registry 172.30.0.0/16'"

  - name: Configure Docker Storage
    blockinfile:
      path: /etc/sysconfig/docker-storage-setup
      block: |
        DEVS=/dev/sdb
        VG=docker-vg

  - name: docker-storage-setup
    shell: docker-storage-setup

  - name: Enable services
    service:
      name: "{{ item }}"
      enabled: yes
      state: started
    with_items:
```
Inventory file is as follows:

```
[all:vars]
ansible_ssh_user=ansible
ansible_ssh_private_key_file=/Users/kashif/.ssh/ansible_id_rsa
#ansible_become=true

[OSEv3:children]
masters
nodes
etcd
glusterfs
glusterfs_registry


[OSEv3:vars]
deployment_type=origin
openshift_master_default_subdomain=app.lab.unixcraft.lcl
#osm_default_node_selector='region=unixcraft-lab'
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/htpasswd'}]
#openshift_disable_check=memory_availability
openshift_disable_check=memory_availability,disk_availability

##Service Catalog
openshift_enable_service_catalog=true
#openshift_service_catalog_image_prefix=openshift/origin-
#openshift_service_catalog_image_version=latest

openshift_hosted_etcd_storage_kind=glusterfs
openshift_hosted_etcd_storage_volume_size=1G

#External NFS storage
#openshift_hosted_registry_storage_kind=nfs
#openshift_hosted_registry_storage_access_modes=['ReadWriteMany']
#openshift_hosted_registry_storage_host=192.168.1.240
#openshift_hosted_registry_storage_nfs_directory=/volume1/OpenShift
#openshift_hosted_registry_storage_volume_name=registry
#openshift_hosted_registry_storage_volume_size=50Gi

#GlusterFS Persistent
openshift_storage_glusterfs_namespace=glusterfs
openshift_storage_glusterfs_name=storage

#GlusterFS registry
openshift_hosted_registry_storage_kind=glusterfs


[masters]
osomd01.lab.unixcraft.lcl


[etcd]
osomd01.lab.unixcraft.lcl

[glusterfs]
osond01.lab.unixcraft.lcl glusterfs_devices='[ "/dev/sdc" ]'
osond02.lab.unixcraft.lcl glusterfs_devices='[ "/dev/sdc" ]'
osond03.lab.unixcraft.lcl glusterfs_devices='[ "/dev/sdc" ]'

[glusterfs_registry]
osond01.lab.unixcraft.lcl glusterfs_devices='[ "/dev/sdc" ]'
osond02.lab.unixcraft.lcl glusterfs_devices='[ "/dev/sdc" ]'
osond03.lab.unixcraft.lcl glusterfs_devices='[ "/dev/sdc" ]'


[nodes]
osomd01.lab.unixcraft.lcl openshift_node_labels="{'region': 'infra', 'zone': 'lhr'}" openshift_schedulable=true
osond01.lab.unixcraft.lcl openshift_node_labels="{'region': 'infra', 'zone': 'lhr'}" openshift_schedulable=true
osond02.lab.unixcraft.lcl openshift_node_labels="{'region': 'infra', 'zone': 'lhr'}" openshift_schedulable=true
osond03.lab.unixcraft.lcl openshift_node_labels="{'region': 'infra', 'zone': 'lhr'}" openshift_schedulable=true

```

##### Observed Results
Describe what is actually happening.

```

INSTALLER STATUS **************************************************************************************************************************************************************************************************
Initialization             : Complete
etcd Install               : Complete
NFS Install                : Not Started
Load balancer Install      : Not Started
Master Install             : Complete
Master Additional Install  : Complete
Node Install               : Complete
GlusterFS Install          : In Progress
	This phase can be restarted by running: playbooks/byo/openshift-glusterfs/config.yml
Hosted Install             : Not Started
Metrics Install            : Not Started
Logging Install            : Not Started
Service Catalog Install    : Not Started
Management Install         : Not Started



Failure summary:


  1. Hosts:    osond01.lab.unixcraft.lcl, osond02.lab.unixcraft.lcl, osond03.lab.unixcraft.lcl
     Play:     all
     Task:     docker-storage-setup
     Message:  Failed without returning a message.

  2. Hosts:    osomd01.lab.unixcraft.lcl
     Play:     Configure GlusterFS
     Task:     Label GlusterFS nodes
     Message:  the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'openshift'

               The error appears to have been in '/opt/kashif/github/f1gjam/ansible/roles/openshift-ansible/roles/openshift_storage_glusterfs/tasks/glusterfs_deploy.yml': line 58, column 3, but may
               be elsewhere in the file depending on the exact syntax problem.

               The offending line appears to be:


               - name: Label GlusterFS nodes
                 ^ here
```
