### ISSUE TITLE
AWS provisioning got'cha: subnet/vpc defaults

### ISSUE THREAD

**Issue by mbarnes** [openshift/openshift-ansible#6092]
Wanted to notify @kwoodson of something that tripped me up when trying to use his [AWS provisioning](https://github.com/openshift/openshift-ansible/tree/master/playbooks/aws).

Starting from [provisioning_vars.yml.example](https://github.com/openshift/openshift-ansible/blob/master/playbooks/aws/provisioning_vars.yml.example), I changed the `openshift_aws_region` from its default `us-east-1` to `ca-central-1` since the ops account is less busy there.

I was going to let the playbook provision a VPC for me, so I left the VPC section of [provisioning_vars.yml.example](https://github.com/openshift/openshift-ansible/blob/master/playbooks/aws/provisioning_vars.yml.example) commented out.

```
# --- #
# VPC #
# --- #

# openshift_aws_create_vpc defaults to true.  If you don't wish to provision
# a vpc, set this to false.
#openshift_aws_create_vpc: true

# Name of the vpc.  Needs to be set if using a pre-existing vpc.
#openshift_aws_vpc_name: "{{ openshift_aws_clusterid }}"

# Name of the subnet in the vpc to use.  Needs to be set if using a pre-existing
# vpc + subnet.
#openshift_aws_subnet_name:
```

Trying to run the `prerequisites.yml` playbook continually failed and it took me awhile to finally figure out why: the defaults for `openshift_aws_subnet_name` and `openshift_aws_vpc` have hard-coded `us-east-1` in their values and don't honor `openshift_aws_region`.

Not sure if these defaults can be set in a way that works for any region and use `"{{openshift_aws_region}}"`, or if this just needs to be somehow clarified in the [provisioning_vars.yml.example](https://github.com/openshift/openshift-ansible/blob/master/playbooks/aws/provisioning_vars.yml.example) comments.

**Comment by omphe** [comment]
I experienced this as well.  I found that `roles/openshift_aws/defaults/main.yml` contained the following stanza:

```yaml
openshift_aws_vpc:
  name: "{{ openshift_aws_vpc_name }}"
  cidr: 172.31.0.0/16
  subnets:
    us-east-1:
    - cidr: 172.31.48.0/20
      az: "us-east-1c"
    - cidr: 172.31.32.0/20
      az: "us-east-1e"
    - cidr: 172.31.16.0/20
      az: "us-east-1a"
```

In my case, I was targeting the Ireland region so I was receiving a dreaded failure of "dict object has no attribute eu-west-1"

My working fix was to add the following to my `provisioning_vars.yml` file:

```yaml
openshift_aws_vpc:
  name: "{{ openshift_aws_vpc_name }}"
  cidr: 172.31.0.0/16
  subnets:
    eu-west-1:
    - cidr: 172.31.48.0/20
      az: "eu-west-1c"
    - cidr: 172.31.32.0/20
      az: "eu-west-1b"
    - cidr: 172.31.16.0/20
      az: "eu-west-1a"
```

With this in place I got a successful run of the prerequisites.  

Once I've got a deploy, I'll try to figure out if this is a documentation or defaults amendment and look to open a PR.
