### ISSUE TITLE
Glusterfs Storage: heketi-storage-copy-job Failing 

### ISSUE THREAD

**Issue by juanwolf** [openshift/openshift-ansible#6111]
#### Description

On a hybrid gluster installation:
6 gluster nodes not in openshift (CentOS to be exact)
1 heketi pod on openshift

##### Version

```
ansible 2.4.0.0

openshift-ansible-3.6.173.0.48-1-74-g6dce9cc76
```

##### Steps To Reproduce
1. Deploy the 6 nodes, and a working openshift cluster
2. run the playbooks/byo/openshift-glusterfs/config.yml

##### Expected Results

Heketi installed and configured on the openshift cluster using the external glusterfs cluster.

##### Observed Results

The `heketi-storage-copy-job` is not ending. After some investigation, the job created does not have the same permissions as the "heketi-deploy" pod and can't access to the glusterfs endpoint. You can find bellow the openshift output from the monitoring tab

```
Error creating: pods "heketi-storage-copy-job-" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.containers[0].securityContext.volumes[0]: Invalid value: "glusterfs": glusterfs volumes are not allowed to be used]
```

I tried to create the job with the same ServiceAccount as the `deploy-heketi` pod but did not solve the issue either.

**Comment by juanwolf** [comment]
Looks like some regression as the fix provided in ﻿https://github.com/heketi/heketi/issues/848 fixed my issue. 

To summarize the `heketi-cli setup-openshift-heketi-storage` does not provide the `serviceAccount: heketi-storage-service-account` declaration and the copy job fail. 

The fix was to leave the playbook running during the checks ` Wait for copy job to finish`, delete the job created and create a new one with the serviceAccountName and serviceAccount defined fix the whole playbook run. 

Here's the definition of the job: 

```
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    deploy-heketi: support
  name: heketi-storage-copy-job
  namespace: glusterfs
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
      name: heketi-storage-copy-job
    spec:
      containers:
      - command:
        - cp
        - /db/heketi.db
        - /heketi
        image: heketi/heketi:latest
        imagePullPolicy: Always
        name: heketi
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /heketi
          name: heketi-storage
        - mountPath: /db
          name: heketi-storage-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: heketi-storage-service-account
      serviceAccountName: heketi-storage-service-account
      terminationGracePeriodSeconds: 30
      volumes:
      - glusterfs:
          endpoints: heketi-storage-endpoints
          path: heketidbstorage
        name: heketi-storage
      - name: heketi-storage-secret
        secret:
          defaultMode: 420
          secretName: heketi-storage-secret
status: {}
```
