### ISSUE TITLE
Error Enabling Calico

### ISSUE THREAD

**Issue by srirammageswarank** [openshift/openshift-ansible#6336]
Hi ,

I get the below error when installing enabling calico on Atomic Host 

Destination /lib/systemd/system not writable

Can we create these fines in /etc/systemd dir.?

@ozdanborne 
@ingvagabund 
@VincentS 

Thanks ,
Sriram Mageswaran.

**Comment by ingvagabund** [comment]
Checking the `calico` role the path is really hard-coded: https://github.com/openshift/openshift-ansible/blob/master/roles/calico/tasks/main.yml#L50

I don't think we have ever tested the calico deployment in AH.

Something like this could do:
```yaml
- name: Detecting Atomic Host Operating System
  stat:
    path: /run/ostree-booted
  register: ostree_booted

- name: Calico Node | Configure Calico service unit file
  template:
    dest: "{{ '/lib/systemd/system/calico.service' if not ostree_booted.stat.exists | bool else '/etc/systemd/system' }}"
    src: calico.service.j2
```

@ozdanborne @VincentS WDYT?

@srirammageswaran8 can you applied it and test if it works for you?
