### ISSUE TITLE
openshift_storage_nfs_lvm role with_sequence formatting error

### ISSUE THREAD

**Issue by jeffcpullen** [openshift/openshift-ansible#6413]
#### Description

Attempts to use the the openshift_storage_nfs_lvm role results in an error 

`unrecognized arguments to with_sequence: [u'_raw_params']`

##### Version

```
ansible 2.4.1.0
openshift-ansible-3.6.173.0.85-1
```

##### Steps To Reproduce
1. Create a playbook to run the role
```
---
- hosts: nfs
  gather_facts: yes
  become: yes
  roles:
    - role: openshift_storage_nfs_lvm
      osnl_mount_dir: /exports
      osnl_volume_prefix: "tdl"
      osnl_volume_size: 5
      osnl_volume_num_start: "1"
      osnl_number_of_volumes: "2"
      osnl_volume_reclaim_policy: "Recycle"
      osnl_volume_group: vg-nfs-1
```
2. Run it against an NFS server

##### Observed Results
Describe what is actually happening.

```
TASK [openshift_storage_nfs_lvm : Export the directories] ************************************
fatal: [nfs.example.com]: FAILED! => {
    "failed": true
}

MSG:

unrecognized arguments to with_sequence: [u'_raw_params']

```

##### Additional Information

I was able to work around this issue by modifying the nfs.yml file as such

```
diff --git a/roles/openshift_storage_nfs_lvm/tasks/nfs.yml b/roles/openshift_storage_nfs_lvm/t
index 03f4fce..7e4c37e 100644
--- a/roles/openshift_storage_nfs_lvm/tasks/nfs.yml
+++ b/roles/openshift_storage_nfs_lvm/tasks/nfs.yml
@@ -19,8 +19,5 @@
   lineinfile: dest=/etc/exports
               regexp="^{{ osnl_mount_dir }}/{{ item }} "
               line="{{ osnl_mount_dir }}/{{ item }} {{osnl_nfs_export_options}}"
-  with_sequence:
-    start: "{{osnl_volume_num_start}}"
-    count: "{{osnl_number_of_volumes}}"
-    format: "{{osnl_volume_prefix}}{{osnl_volume_size}}g%04d"
+  with_sequence: start="{{osnl_volume_num_start}}" count="{{osnl_number_of_volumes}}" format=
   notify: restart nfs
```
