### ISSUE TITLE
openshift-ansible uses a tag of docker.io/ansibleplaybookbundle/ansible-service-broker that does not exist.

### ISSUE THREAD

**Issue by ozdanborne** [openshift/openshift-ansible#6435]
#### Description

My fresh v3.7 cluster is provisioning successfully but the `openshift-ansible-service-broker` pod is stuck in `ErrImagePull`.

```
  containerStatuses:
  - image: ansibleplaybookbundle/ansible-service-broker:latest
    imageID: ""
    lastState: {}
    name: asb
    ready: false
    restartCount: 0
    state:
      waiting:
        message: 'rpc error: code = 2 desc = Tag latest not found in repository docker.io/ansibleplaybookbundle/ansible-service-broker'
        reason: ErrImagePull
```
Seems that by default (https://github.com/openshift/openshift-ansible/blob/master/roles/ansible_service_broker/vars/default_images.yml#L4) they use the tag `latest` which doesn't exist on dockerhub: https://hub.docker.com/r/ansibleplaybookbundle/ansible-service-broker/tags/

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`: 

If you're operating from a **git clone**:

* The output of `git describe`: 

Place the output between the code block below:

```
ansible 2.4.2.0
openshift-ansible-3.4.17-1-4257-g8e4c88a
```

##### Steps To Reproduce

Will have to find time later to give more information than that. Mostly I'm stunned that I'm the only one hitting this...

##### Expected Results
Describe what you expected to happen.

```
Example command and output or error messages
```

##### Observed Results
Describe what is actually happening.

```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
CentOS Linux release 7.4.1708 (Core) 

```
