### ISSUE TITLE
Node auth cache configuration

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-ansible#673]
https://github.com/openshift/origin/pull/4873 added settings to the node config to control authentication and authorization caching:

```
authConfig:
  authenticationCacheSize: 1000
  authenticationCacheTTL: "5m"
  authorizationCacheSize: 1000
  authorizationCacheTTL: "5m"
```

TTL settings are valid duration strings, or `"0m"` to disable caching (empty string or missing setting gets default). Cache size is a positive number (0 or missing setting gets default)
