### ISSUE TITLE
Add proxy client certs to master config

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-ansible#685]
https://github.com/openshift/origin/pull/5011 allows setting a client certificate for the API proxy to use when proxying to TLS-enabled pods/services.

A configuration option in `master-config.yaml` allows setting a client cert for the proxy to present when proxying using TLS:
```
kubernetesMasterConfig:
  ...
  proxyClientInfo:
    certFile: "path/to/client-cert.crt"
    keyFile: "path/to/client-cert.key"
```

`oadm ca create-master-certs` sets up a default cert/key for this purpose:
```
master.proxy-client.crt
master.proxy-client.key
```

Those files are expected as output from create-master-certs, and should be set in the master-config.yaml template
