### ISSUE TITLE
GlusterFS Hosted Registry - Deploy PersistentVolumeClaim definitions failure

### ISSUE THREAD

**Issue by Tirke** [openshift/openshift-ansible#7167]
#### Description

```yaml
Play:     Create Hosted Resources - persistent volumes
     Task:     Deploy PersistentVolumeClaim definitions
     Message:  AnsibleError: template error while templating string: no test named 'None'. String: ---
               apiVersion: "v1"
               kind: "List"
               items:
               {% for claim in persistent_volume_claims %}
               - apiVersion: "v1"
                 kind: "PersistentVolumeClaim"
                 metadata:
                   name: "{{ claim.name }}"
                 spec:
                   accessModes: {{ claim.access_modes | lib_utils_to_padded_yaml(2, 2) }}
                   resources:
                     requests:
                       storage: "{{ claim.capacity }}"
               {% if claim.storageclass is not None %}
                   storageClassName: "{{ claim.storageclass }}"
               {% endif %}
               {% endfor %}
```

This is on a fresh install of openshift-ansible-3.9.0-0.45.0

Edit : lowercase none should fix it ?
