### ISSUE TITLE
Support setting custom certificates in serving info

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-ansible#737]
https://trello.com/c/Gc3FDSK8/524-2-allow-setting-custom-serving-certs-for-specific-hostnames-in-api-console-using-sni added support for specifying custom certificates for particular hostnames.

The most common use of this will be to provide a certificate signed by a public CA for use with the public master hostname.

The cert/key files both need to be PEM-encoded and unencrypted (the cert can be a full cert chain). They would be set in the servingInfo section of the master-config (which takes effect for both the API and the web console), or the assetConfig.servingInfo section of the master-config (when the asset server is bound to a separate port and is being served separately).

The structure looks like this:
```
servingInfo:
  certFile: master.server.crt
  keyFile: master.server.key
  namedCertificates:
  - certFile: custom1.crt
    keyFile: custom1.key
    names:
    - public-master-host.com
```

Multiple named certificates can be specified, and multiple names per certificate can be specified
