### ISSUE TITLE
3.7 file not found: /etc/origin/logging/ca.crl.srl

### ISSUE THREAD

**Issue by dungdm93** [openshift/openshift-ansible#7725]
### Description
Install OpenShift Origin 3.7 on CentOS 7 got following error:
```
TASK [openshift_logging : pulling down signing items from host] ********************************************************************************************************************************************
Monday 02 April 2018  18:07:05 +0700 (0:00:00.042)       0:03:12.959 ********** 
changed: [ocp-master-c8k3] => (item=ca.crt)
changed: [ocp-master-c8k3] => (item=ca.key)
changed: [ocp-master-c8k3] => (item=ca.serial.txt)
failed:  [ocp-master-c8k3] (item=ca.crl.srl) => {"changed": false, "item": "ca.crl.srl", "msg": "file not found: /etc/origin/logging/ca.crl.srl"}
changed: [ocp-master-c8k3] => (item=ca.db)

```
### Version
* `ansible --version`
```
ansible 2.5.0
  config file = /me/Workspaces/OpenShift/openshift-ansible/ansible.cfg
  configured module search path = [u'/home/dungdm93/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```
* `git describe`
```
openshift-ansible-3.7.42-1-5-g39058c1
```

### Steps To Reproduce
```
ansible-playbook playbooks/byo/openshift-cluster/openshift-logging.yml -i inventory/byo/hosts.ini -e @inventory/byo/variables.yaml
```
Logging config:
```yaml
openshift_logging_install_logging: true
openshift_logging_storage_kind: dynamic
openshift_logging_storage_volume_size: 50Gi
openshift_logging_es_memory_limit: 4Gi
```

**Comment by dungdm93** [comment]
P/S: After manual add this file and re-run playbook, logging is installed successful

**Comment by oybed** [comment]
Same here - OpenShift Container Platform 3.7 (3.7.23) on RHEL 7.4 with the `release-3.7` branch.

**Comment by HP-dufeng** [comment]
Same with - Openshift Origin 3.9 on Centos 7 with release-3.9 branch and ansible --version 2.5.0

**Comment by mikecali** [comment]
this is even showing on 3.6 as well.

Using: openshift-ansible-3.7.42-1-5-g39058c1
            Ansible 2.5.0

**Comment by kisamoto** [comment]
Seeing the same for Openshift Container Platform 3.9 (enterprise) with ansible version 2.5.0 on RHEL 7. 

Possibly error with generating certificates (which refer to a `.crt.srl`)

```
- name: Checking for ca.crt.srl
  stat: path="{{generated_certs_dir}}/ca.crt.srl"
  register: ca_cert_srl_file
  check_mode: no
- copy: content="" dest={{generated_certs_dir}}/ca.crt.srl
  check_mode: no
  when:
    not ca_cert_srl_file.stat.exists
```

in `openshift-ansible/roles/openshift_logging/tasks/generate_certs.yaml`

installed via 

```
Installed Packages
Name        : openshift-ansible
Arch        : noarch
Version     : 3.9.14
Release     : 1.git.3.c62bc34.el7
Size        : 56 k
Repo        : installed
From repo   : rhel-7-server-ose-3.9-rpms
```
