### ISSUE TITLE
use official grafana image (?)

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-ansible#7735]
I would like to suggest to move to use official grafana image (https://hub.docker.com/r/grafana/grafana/), instead of one built by @mrsiano in our grafana playbooks.

Not like its bad, but it would be easier to maintain if we use an official image from grafana. 

cc: @mrsiano , @jeremyeder, @sdodson 

I already have a version/adoption of the playbook which is using official image and all functionality is the same.

Few differences are:
1. It has to run as anyuid scc
```
- name: Set privileged permissions for grafana
  oc_adm_policy_user:
    namespace: "{{ grafana_namespace }}"
    resource_kind: scc
    resource_name: anyuid
    state: present
    user: "system:serviceaccount:{{ grafana_namespace }}:{{ grafana_serviceaccount_name }}"
```
2. Entry point for volumes and cmd are different. 
3. Few Other minor bits and bobs.

Would like to get some input about this. Not sure what is our relationship with Grafana to publish this image via "registry.redhat.com"
