### ISSUE TITLE
Package 'origin-3.9*' not found

### ISSUE THREAD

**Issue by dungdm93** [openshift/openshift-ansible#7848]
#### Description
I got following error while installing OpenShift 3.9
```
Package 'origin-3.9*' not found
```

##### Version
* `ansible --version`
```
ansible 2.5.0
  config file = /me/Workspaces/OpenShift/openshift-ansible/ansible.cfg
  configured module search path = [u'/home/dungdm93/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

* `git describe`
```
openshift-ansible-3.9.19-1-1-g5af4d45
```

##### Steps To Reproduce
```shell
$ ansible-playbook -i inventory/me/gce -i inventory/me/hosts.ini -e @inventory/me/variables.yaml playbooks/prerequisites.yml
$ ansible-playbook -i inventory/me/gce -i inventory/me/hosts.ini -e @inventory/me/variables.yaml playbooks/deploy_cluster.yml
```
My configs:
```yaml
openshift_deployment_type: origin
containerized: False
openshift_release: '3.9'

openshift_master_api_port: '443'
openshift_master_console_port: '443'
os_sdn_network_plugin_name: 'redhat/openshift-ovs-subnet'
osm_cluster_network_cidr: 172.16.0.0/16
openshift_master_default_subdomain:       apps.dungdm93.tk
openshift_master_cluster_hostname:        internal-master.dungdm93.tk
openshift_master_cluster_public_hostname: master.dungdm93.tk
openshift_master_cluster_method:          native

openshift_cloudprovider_kind: gce
openshift_gcp_project:  gcp-labshift-project
openshift_gcp_prefix:   labshift
```
