### ISSUE TITLE
Unable rsh and port-forward from external

### ISSUE THREAD

**Issue by dungdm93** [openshift/openshift-ansible#7905]
#### Description
I have OpenShift 3.9 cluster on GCP. But I can't `rsh` as well as `port-forward` from external.
However, running the same command in internal cluster (master node) work well.
```bash
$ oc rsh anaconda-1-rsqxc
```
```html
error: unable to upgrade connection: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 400 (Bad Request)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>400.</b> <ins>That’s an error.</ins>
  <p>Your client has issued a malformed or illegal request.  <ins>That’s all we know.</ins>
```

So, what did i miss? Here is my config:
```yaml
openshift_deployment_type: origin
openshift_repos_enable_testing: true
containerized: False
openshift_release: '3.9'

openshift_master_api_port: '443'
openshift_master_console_port: '443'
os_sdn_network_plugin_name: 'redhat/openshift-ovs-subnet'
osm_cluster_network_cidr: 172.16.0.0/16

openshift_cloudprovider_kind: gce
openshift_gcp_project:  my-gcp-project
openshift_gcp_prefix:   labshift
osm_default_node_selector: 'region=primary'
openshift_hosted_router_selector: 'region=infra'
```
P/S: I also try expose all port from all cluster instances, but it don't help.
![image](https://user-images.githubusercontent.com/6848311/38610376-dd3a6af6-3daa-11e8-9d22-e8ab73014c5d.png)
