### ISSUE TITLE
Prometheus - kubernetes-service-endpoints down

### ISSUE THREAD

**Issue by pgeorgiev333** [openshift/openshift-ansible#7986]
#### Description

I have installed openshift 3.9 using the playbooks (deploy_cluster.yml) with the test repo RPMs. I have also enabled the metrics and prometheus. 
After the installation is done i looked at the prometheus "targets" page and most of the "kubernetes-service-endpoints" are down.

I looked particularly at the kubernetes_name="logging-es-prometheus" endpoint and i can see the following messages in the proxy container inside the logging-es-data-master-xxxx pod:
```
authorizer reason: User "system:anonymous" cannot "view" "prometheus.metrics.openshift.io" with name "" in project "logging"
```

![image](https://user-images.githubusercontent.com/16955574/38859273-5472fc3e-4236-11e8-854c-bc07553cf6dd.png)

I also noticed that Endpoint URLs are kind of weird too: 
https://90.49.0.11:9300_prometheus/metrics

Any hints on what might be wrong?

UPDATE:

I tried curl to the first endpoint (the "router" one) and i get similar error:
```
Forbidden: User "system:anonymous" cannot get routers/metrics.route.openshift.io at the cluster scope
```
Just found the defect for the ROUTER endpoint:
https://github.com/openshift/origin/issues/17685

**Comment by pat2man** [comment]
The router stuff isn't set up correctly. It looks like it will be working in the next release: 3.10. See https://github.com/openshift/origin/pull/19318

The logging elasticsearch one seems like it should be working, but there are some changes that would need to be made. First of all, the kubernetes-service-endpoints don't do auth. You would need to add something like ```bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token``` to that section of the prometheus config. After doing that on my 3.7 cluster I get this error: ```authorizer reason: User "system:serviceaccount:openshift-metrics:prometheus" cannot "view" "prometheus.metrics.openshift.io" with name "" in project "logging"``` which would indicate some sort of access control issue.

**Comment by Reamer** [comment]
@pat2man Any progress in your rbac problem? For me the logging metric endpoint works with "bearer_token_file" in prometheus.yml configuration file.
My prometheus serviceaccount has the cluster role "cluster-readers".

But I don't know, how to solve a quite similar message for haproxy.
```
Unauthorized User "system:serviceaccount:openshift-metrics:prometheus" cannot get routers/metrics.route.openshift.io at the cluster scope
```
With my user cluster-admin token the haproxy metric endpoint works as expected. Also when I give the prometheus serviceuser the same rights.

Has anyone some ideas for me?

**Comment by pat2man** [comment]
@Reamer if you take a look at the latest prometheus example it has a prometheus-scraper cluster role:

https://github.com/openshift/origin/blob/master/examples/prometheus/prometheus.yaml

**Comment by lukas-vlcek** [comment]
The `prometheus.io/path` for Elasticsearch prometheus service is invalid. I opened a ticket for this https://github.com/openshift/openshift-ansible/issues/8343 and linked relevant PR.

However, there is another issue, the path `/_prometheus/metrics` **SHOULD** be used only in connection to port `9200`. There is no point in making Prometheus scrape ports `9300` or `4443`. How can we fix that?

**Comment by lukas-vlcek** [comment]
To make it more clear, this is what I am talking about:
![screen shot 2018-05-11 at 15 27 41_edit](https://user-images.githubusercontent.com/205174/39928635-34cd81ac-5536-11e8-848e-b4743a751579.jpg)
If we make it work via proxy (4443) then we should stop scraping other ports (9200 and 9300).

I had a quick discussion about this with @jcantrill and he had an idea of creating a new extra Prometheus rules just for logging. He has a PR for this also https://github.com/openshift/origin/pull/18796/files I will try to push his approach further.

**Comment by pat2man** [comment]
@lukas-vlcek you can annotate the service with prometheus.io/port to restrict it to the correct port

**Comment by lukas-vlcek** [comment]
@pat2man right, there is PR to fix that: https://github.com/openshift/openshift-ansible/pull/8432

**Comment by simonpasquier** [comment]
FYI I've submitted a PR to get the router's metrics back, see #8512

**Comment by prasenforu** [comment]
Can anyone explain how to fix in existing (running) 3.9 ?
What are the steps need to take to fix this router metric issue.

**Comment by simonpasquier** [comment]
@prasenforu I think you can get around it by fixing a couple of permissions. At least it worked for me using `oc cluster up`.

First, create the following cluster role:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-scraper
rules:
- apiGroups:
  - route.openshift.io
  resources:
  - routers/metrics
  verbs:
  - get
- apiGroups:
  - image.openshift.io
  resources:
  - registry/metrics
  verbs:
  - get
```

Then assign this cluser role to the `prometheus` service account.
Finally you need to add the `system:auth-delegator` cluster role to the `router` service account.

**Comment by prasenforu** [comment]
@simonpasquier 

Let me try, 
Though I am not so familiar with RBAC but again checking last two execution, please verify and let me know.

```
oc adm policy add-cluster-role-to-user prometheus-scraper system:serviceaccount:openshift-metrics:prometheus

oc adm policy add-cluster-role-to-user system:auth-delegator system:serviceaccount:default:router
```

**Comment by simonpasquier** [comment]
@prasenforu I used:

```
oc adm policy add-cluster-role-to-user system:auth-delegator -z router -n default
oc adm policy add-cluster-role-to-user prometheus-scraper -z prometheus -n openshift-metrics
```

Not sure if it makes a difference.

**Comment by prasenforu** [comment]
@simonpasquier 

tnx ... will try & let know.

**Comment by simonpasquier** [comment]
@prasenforu right so I've checked again and IIUC what's missing is that the `kubernetes-service-endpoints` job doesn't provide any token to authenticate against the scraped endpoints.

Can you check whether this command succeeds after you've added the permissions?

```bash
oc rsh po/prometheus-0 sh -c 'curl -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" http://router.default.svc:1936/metrics'
```

If it does, I'd recommend adding another scrape configuration specifically for the router (loosely adapted from https://github.com/openshift/origin/pull/18254):

```yaml
      - job_name: 'openshift-router'
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - default
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: default;router;1936-tcp
```

And modify the `kubernetes-service-endpoints` job to drop the router endpoints by adding the following rule to the `relabel_configs` section:

```yaml
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: drop
          regex: default;router;1936-tcp
```

**Comment by prasenforu** [comment]
@simonpasquier 

I created new scape (haproxy)

```
- job_name: 'haproxyr'
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - default
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: default;router;1936-tcp
```

And modify the kubernetes-service-endpoints job to drop the router endpoints by adding the following rule to the relabel_configs section:

``` 
       - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: drop
          regex: default;router;1936-tcp
```

Its working.

But still red error in "kubernetes-service-endpoints" and as a result I am getting mail alert as alert is configured in prometheus.

![image](https://user-images.githubusercontent.com/19322497/40633108-0ca8cb68-630b-11e8-8042-506c40b95716.png)
