### ISSUE TITLE
Yum on base-AMI does not find relevant packages

### ISSUE THREAD

**Issue by naumannt** [openshift/openshift-ansible#8105]
#### Description
I am currently trying to install a simple OpenShift-Cluster on AWS, using the provided playbooks in playbooks/aws.
I am currently trying to run Step 1 after running Step 0 with the provisioning_vars.yml listed below.

##### Version

* Your ansible version per `ansible --version`

ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

* The output of `git describe`
openshift-ansible-3.9.24-1-19-g0d70b5a9e

* The output of `rpm -q openshift-ansible`
```
openshift-ansible-3.7.23-1.git.0.bc406aa.el7.noarch
```
Not entirely sure why this is so outdated, I was trying to install it in different ways before this so the version might still be from that time (and is unused?)
##### Steps To Reproduce
1. Run 'Step 0' from https://github.com/openshift/openshift-ansible/tree/release-3.9/playbooks/aws with the following provisioning_vars.yml:
```
openshift_deployment_type: 'openshift-enterprise'
openshift_release: '3.9'
openshift_pkg_version: '-3.9.0'

openshift_master_api_port: 8443
openshift_aws_clusterid: ose

openshift_aws_region: eu-central-1

openshift_aws_create_vpc: true
openshift_aws_vpc:
  name: "{{ openshift_aws_vpc_name }}"
  cidr: 172.31.0.0/16
  subnets:
    eu-central-1:
    - cidr: 172.31.48.0/20
      az: "eu-central-1a"
      default_az: true
    - cidr: 172.31.32.0/20
      az: "eu-central-1b"
    - cidr: 172.31.16.0/20
      az: "eu-central-1c"

openshift_aws_vpc_name: "{{ openshift_aws_clusterid }}"

openshift_aws_ssh_key_name: ourkeyname

openshift_aws_build_ami_ssh_user: root

container_runtime_docker_storage_type: overlay2
container_runtime_docker_storage_setup_device: /dev/xvdb

openshift_aws_base_ami: ami-c86c3f23

openshift_aws_iam_cert_path: '/home/ec2-user/openshift-template/certs/ca.crt'
openshift_aws_iam_cert_key_path: '/home/ec2-user/openshift-template/certs/ca.key'
openshift_aws_iam_cert_chain_path: '/home/ec2-user/openshift-template/certs/ca-cert.crt'
```
Afterwards I tried running Step 1, which ran into an error; after configuring the resulting instance to allow becoming root via SSH (like so: https://forums.aws.amazon.com/thread.jspa?messageID=369913) it worked until I hit the current error.

##### Expected Results
The playbook running until the end to create the base-AMI.

##### Observed Results
Playbook fails with this error:
```
TASK [openshift_excluder : Install docker excluder - yum] *******************************************************************************************************************************************************************************
FAILED - RETRYING: Install docker excluder - yum (2 retries left).
FAILED - RETRYING: Install docker excluder - yum (1 retries left).
fatal: [ec2-*****.eu-central-1.compute.amazonaws.com]: FAILED! => {"attempts": 2, "changed": false, "msg": "No package matching 'atomic-openshift-docker-excluder-3.9.0*' found available, installed or updated", "rc": 126, "results": ["No package matching 'atomic-openshift-docker-excluder-3.9.0*' found available, installed or updated"]}
```

##### Additional Information

The AMI I use as "base for the base" is ami-c86c3f23, which is the basic RHEL 7.5 image provided by AWS.

No further inventory or variable-files used.

I ssh'd into my base-AMI instance to see if I can find something wrong, but it's weird: yum doesn't seem to find any relevant packages. 'sudo yum search atomic-openshift-docker-excluder' results in no matches (as root). Without root, yum can't connect to the RedHat-endpoints.
