### ISSUE TITLE
Support for SSL redirects in oc_route.py

### ISSUE THREAD

**Issue by slauger** [openshift/openshift-ansible#8175]
#### Description

The ansible module oc_route.py currently does not support to set the option `insecureEdgeTerminationPolicy`, which allows to enable an redirect for unsecure HTTP traffic to HTTPS. The default for insecureEdgeTerminationPolicy is None.
For example, this means it's currently not possible to access the docker registry via `http://registry-console-default.example.tld`.

```
- name: Configure a passthrough route for docker-registry
  oc_route:
    name: docker-registry
    namespace: "{{ openshift_hosted_registry_namespace }}"
    service_name: docker-registry
    tls_termination: "{{ openshift_hosted_registry_routetermination }}"
    host: "{{ openshift_hosted_registry_routehost | default(omit, true) }}"
    # currently missing
    insecureedgeterminationpolicy: redirect
```

It would be cool if this feature could be added to oc_route. I'm also using the lib_openshift for automating my deployments inside openshift, so it would be useful there as well.
