### ISSUE TITLE
glusterfs deploy fails with glusterfs_heketi_user_key is undefined

### ISSUE THREAD

**Issue by preinking** [openshift/openshift-ansible#8193]
#### Description

When using glusterfs the following code fails with 'glusterfs_heketi_user_key is undefined' which is kind of expected here but it seems Ansible gets confused by this definition. Clearly the until is evaluated before glusterfs_heketi_user_key is set in the line above.

```
- name: Generate heketi user key
  set_fact:
    glusterfs_heketi_user_key: "{{ 32 | lib_utils_oo_generate_secret }}"
  until: "glusterfs_heketi_user_key != glusterfs_heketi_admin_key"
  delay: 1
  retries: 10
  when:
  - glusterfs_heketi_is_native
  - glusterfs_heketi_user_key is undefined
```

##### Version

```
ansible 2.5.1
  config file = /home/oelan/openshift-ansible/ansible.cfg
  configured module search path = [u'/home/oelan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

openshift-ansible-3.9.27-1-18-g9ac6bf4
```

##### Steps To Reproduce
1. Add glusterfs nodes to /etc/ansible/hosts
2. Run deployOpenShift.sh

**Comment by rabem00** [comment]
Same here! Tried with openshift-ansible versions 3.9.27-1, 3.9.24-1 and 3.9.12-1, they all have the same problem. If needed i could provide deployment details or test any possible solutions.

**Comment by rabem00** [comment]
As @preinking  already stated it is the until line that's not working. A temporary workaround is changing some lines glusterfs_common.yml:

```
- name: Generate heketi user key
  set_fact:
    glusterfs_heketi_user_key: "{{ 32 | lib_utils_oo_generate_secret }}"
  #until: "glusterfs_heketi_user_key != glusterfs_heketi_admin_key"
  #delay: 1
  #retries: 10
  when:
  - glusterfs_heketi_is_native
  - glusterfs_heketi_user_key is undefined

- name: test if they are not the same
  set_fact:
    glusterfs_heketi_user_key: "{{ 32 | lib_utils_oo_generate_secret }}"
  until: "glusterfs_heketi_user_key != glusterfs_heketi_admin_key"
  delay: 1
  retries: 10
  when:
  - glusterfs_heketi_is_native
```
Of course this is a end solution (that's why no pull request) but the installation will now continue.
