### ISSUE TITLE
node-exporter dashboard needs queries update.

### ISSUE THREAD

**Issue by mrsiano** [openshift/openshift-ansible#8279]
In continuing to https://github.com/openshift/openshift-ansible/pull/8263
we need to tune some of the queries in order to have reliable dashboard.
some of the graphs shows N/A data.

@jeremyeder

**Comment by eye0fra** [comment]
Hi @mrsiano,

As you see on the prometheus.yml config:

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_prometheus/templates/prometheus.yml.j2#L185

all the important metrics used by the node exporter dashboard have action: drop. 
That's the reason of the N/A. 
If you comment them everything works as expected.

**Comment by mrsiano** [comment]
I tried it, but we when redeploy it I faced this:
level=error ts=2018-05-07T09:47:55.715218931Z caller=main.go:582 err="Error loading config couldn't load configuration (--config.file=/etc/prometheus/prometheus.yml): parsing YAML file /etc/prometheus/prometheus.yml: relabel configuration for replace action requires 'target_label' value"

**Comment by mrsiano** [comment]
Right,
we need to understand if we can get rid of this.

I see @smarterclayton submit this change.
https://github.com/openshift/origin/commit/30516b58a23e247cef8efa084fb403e1750ecc0e#diff-d834a5fd4c91cb4a584e1113a1db37a5

any thoughts ?

**Comment by eye0fra** [comment]
Yes that change is already on release-3.9.
So I have to change it like this:

```
metric_relabel_configs:
      #- source_labels: [__name__]
      #  action: drop
      #  regex: 'node_cpu|node_(disk|scrape_collector)_.+'
      # preserve a subset of the network, netstat, vmstat, and filesystem series
      - source_labels: [__name__]
        action: replace
        regex: '(node_(netstat_Ip_.+|vmstat_(nr|thp)_.+|filesystem_(free|size|device_error)|network_(transmit|receive)_(drop|errs)))'
        target_label: __name__
        replacement: renamed_$1
      #- source_labels: [__name__]
        #action: drop
        #regex: 'node_(netstat|vmstat|filesystem|network)_.+'
      - source_labels: [__name__]
        action: replace
        regex: 'renamed_(.+)'
        target_label: __name__
        replacement: $1
      # drop any partial expensive series
      #- source_labels: [__name__, device]
      #  action: drop
      #  regex: 'node_network_.+;veth.+'
      #- source_labels: [__name__, mountpoint]
      #  action: drop
      #  regex: 'node_filesystem_(free|size|device_error);([^/].*|/.+)'
```
