### ISSUE TITLE
Build deployments to internal registry fail due to wrong host name.

### ISSUE THREAD

**Issue by hendrikhalkow** [openshift/openshift-ansible#8280]
#### Description

When running the demo apps that execute a build, e.g. Django + Postgres and Node + Mongo, the builds fail because they cannot push to the internal registry due to a TLS certificate error:

```
error: build error: Failed to push image: Get https://docker-registry.default.svc:5000/v1/_ping:  x509: certificate is valid for *.apps.your.domain, *.your.domain, your.domain, not docker-registry.default.svc
```

This is the certificate is the one that I configured at openshift_hosted_registry_routecertificates.

##### Version

```
openshift-ansible-3.9.27-1-43-g81cd65e6b
```

##### Steps To Reproduce
1. Install OpenShift Origin 3.9 according to https://docs.openshift.org/3.9/install_config/install/advanced_install.html
2. configure the openshift_hosted_registry_* variables as follows (I use YAML inventories):

```
    openshift_hosted_registry_routecertificates:
      certfile: /etc/letsencrypt/live/your.domain/fullchain.pem
      keyfile: /etc/letsencrypt/live/your.domain/privkey.pem
      cafile: /etc/letsencrypt/ca.pem
      names:
        - registry.apps.your.domain
        # Necessary to access the console with a valid certificate
        - registry-console-default.apps.your.domain
    openshift_hosted_registry_routehost: registry.apps.your.domain
    openshift_hosted_registry_storage_kind: glusterfs
    openshift_hosted_registry_routetermination: passthrough
    openshift_master_default_subdomain: apps.your.domain
```

3. Deploy an example app like Django + Postgres and Node + Mongo

##### Expected Results

I expect both the registry and registry Web UI to be available at registry.apps.your.domain with a valid TLS certificate as configured. I also expect the apps to build successfully and to push their resulting images either to registry.apps.your.domain or to docker-registry.default.svc while ignoring the certificate error. I don't want to issue a public certificate with docker-registry.default.svc as a SAN (and Letsencrypt doesn't allow this for a good reason).

##### Observed Results

Both routes docker-registry-default.apps.your.domain and registry.apps.your.domain are deployed. Deployments from the example applications fail due to the error message described above because they use the internal registry docker-registry.default.svc which presents the public certificates that don't contain docker-registry.default.svc as SAN.
