### ISSUE TITLE
FluentD daemonset issue

### ISSUE THREAD

**Issue by antarass** [openshift/openshift-ansible#8996]
#### Description

Deploying Origin 3.9 Logging stack the FluentD cannot read any of the logs. Having a look inside the pod I noticed that the path to the files is actually missing:

Sample file:
`/var/log/containers/apiserver-k2jvf_kube-service-catalog_apiserver-5e47edd43931317c9389e2d05fce4a31e6538bc2c6e699186c72b4757f882e43.log -> /var/log/pods/dd2bd1cc-790b-11e8-8d0b-fa163e6bd299/apiserver_0.log -> /var/lib/containers/docker/containers/43646207927baf74cd1c3bdf4c291b0a680020e5a4b62e70aab24491e658789b/43646207927baf74cd1c3bdf4c291b0a680020e5a4b62e70aab24491e658789b-json.log`

The issue is that the daemon set does not mount /var/lib/containers inside the FluentD pods.

What I did as workaround is to actually mount that folder:

```
....
- mountPath: /var/lib/containers
          name: varlibcontainers
          readOnly: true
.....
- hostPath:
          path: /var/lib/containers
          type: ""
        name: varlibcontainers
```

##### Version

# On branch release-3.9
openshift-ansible-3.9.30-1-33-gde18f91
Docker runtime: Docker version 1.13.1, build 94f4240/1.13.1

##### Expected Results
Fixed template for the daemonset.

##### Additional Information

This is the template which needs to be updated.
```
https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_logging_fluentd/templates/fluentd.j2
```
