### ISSUE TITLE
Unable to upgrade service catalog from 3.7 to 3.9 - Origin

### ISSUE THREAD

**Issue by benscottub** [openshift/openshift-ansible#9380]
#### Description

When using the following playbook:
```
ansible-playbook -i openshift/ansible-hosts/dev openshift-ansible/playbooks/openshift-service-catalog/config.yml
```

the playbook crashes at this step:
```
TASK [ansible_service_broker : Create the Broker resource in the catalog] 
```
with the following error:
```
<osmdev1.acsu.buffalo.edu> (1, '\r\n{"msg": {"returncode": 1, "cmd": "/usr/bin/oc replace -f /tmp/ansible-service-broker-ROvmbA -n default", "results": {}, "stderr": "Error from server (Forbidden): error when replacing \\"/tmp/ansible-service-broker-ROvmbA\\": clusterservicebrokers.servicecatalog.k8s.io \\"ansible-service-broker\\" is forbidden: not yet ready to handle request\\n", "stdout": ""}
```
##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:
```
[bscott@bscott ~]$ ansible --version
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/bscott/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
[bscott@bscott openshift-ansible]$ git describe
openshift-ansible-3.9.38-1
```
##### Steps To Reproduce
1) Upgrade the control plane and nodes with 
```
openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_9/upgrade.yml
```
2) Upgrade metrics and logging with their respective config.yml playbooks
3) Run 
```
openshift-ansible/playbooks/openshift-service-catalog/config.yml
```
 against our development inventory file

##### Expected Results
Describe what you expected to happen.

We expect to see that the service catalog has been successfully upgraded to 3.9 like the masters, nodes, logging and metrics.

##### Observed Results
Describe what is actually happening.

The playbook crashes with the error 
```
"Error from server (Forbidden): error when replacing \\"/tmp/ansible-service-broker-ROvmbA\\": clusterservicebrokers.servicecatalog.k8s.io \\"ansible-service-broker\\" is forbidden: not yet ready to handle request".
```
We grabbed the contents of the /tmp/ansible-service-broker file referenced in the error message and found this additional information:
```
status:
  operationStartTime: '2018-07-09T13:26:15Z'
  conditions:
  - status: 'False'
    type: Ready
    message: 'Error fetching catalog. Error getting broker catalog: Get https://asb.openshift-ansible-service-broker.svc:1338/ansible-service-broker/v2/catalog:
      dial tcp 172.30.216.62:1338: connect: cannot assign requested address'
    lastTransitionTime: '2018-05-14T18:22:25Z'
    reason: ErrorFetchingCatalog
  reconciledGeneration: 1
```
We confirmed that we are able to resolve the broker's DNS listed in the above error:
```
@osmdev1 ~]$ nslookup asb.openshift-ansible-service-broker.svc
Server:		128.205.194.228
Address:	128.205.194.228#53

Name:	asb.openshift-ansible-service-broker.svc.cluster.local
Address: 172.30.216.62
```
##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

[dev-inventory.txt](https://github.com/openshift/openshift-ansible/files/2246878/dev-inventory.txt)
```
@osmdev1 ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.5 (Maipo)
```
Thank you for your help and I apologize if I left out any important information.
