### ISSUE TITLE
Add pre/post hooks.

### ISSUE THREAD

**Issue by pierreozoux** [openshift/openshift-ansible#9434]
#### Description

As a cluster operator, I'd like to be able to run playbooks before and after open shift installation.
We currently have hooks for upgrades, but not for installation.

This would ease automatic installation, such as the Amazon quickstart:
https://github.com/aws-quickstart/quickstart-redhat-openshift/issues/159

**Comment by benfairless** [comment]
Could you not maybe just create a wrapper playbook of your own?

I have something like this:

```yaml
 - hosts: all
   tasks:
     # Do some stuff

 - import_playbook: openshift-ansible/playbooks/deploy_cluster.yml

 - hosts: all
   tasks:
     # do some stuff
```
