### ISSUE TITLE
Custom node labels in Openshift 3.10

### ISSUE THREAD

**Issue by jocelynthode** [openshift/openshift-ansible#9463]
Hey,

In Openshift 3.10 labels are now set from the configmaps. However we currently have custom labels on our nodes for example (site=<SITE>) so that we can schedule certain pods based on site where the node resides to have true HA.

Is there still a way to declare different labels for different nodes ?

**Comment by vrutkovs** [comment]
If these labels are persistent you should create a new node group (retaining the default ones):
```
openshift_node_groups:
  - name: node-config-master
    labels:
      - 'node-role.kubernetes.io/master=true'
    edits: []
  - name: node-config-infra
    labels:
      - 'node-role.kubernetes.io/infra=true'
    edits: []
  - name: node-config-compute
    labels:
      - 'node-role.kubernetes.io/compute=true'
    edits: []
  - name: node-config-master-infra
    labels:
      - 'node-role.kubernetes.io/infra=true,node-role.kubernetes.io/master=true'
```

if the labels should be set dynamically you should use `oc label node` - it would still work and be persistent across sync runs
