### ISSUE TITLE
Do not copy router certificates to /etc/origin/master

### ISSUE THREAD

**Issue by jkroepke** [openshift/openshift-ansible#9547]
#### Description
See:
https://github.com/openshift/openshift-ansible/blob/1597613fa0acee2d04a16effed9bebb023acce83/roles/openshift_hosted/tasks/router.yml#L27

For example, if the router ca is named ca.crt, it would be override the /etc/origin/master/ca.crt.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
$ 
ansible --version
ansible 2.6.2
  config file = None
  configured module search path = [u'/Users/jan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.6.2/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]

$ openshift-ansible-3.9.40-1-31-gc643a1ad6
```

##### Steps To Reproduce
1. Configure `openshift_hosted_router_certificate`, named the `cafile` ca.crt
2. Run the openshift_hosted playbook. At the end, `/etc/origin/master/ca.crt` is overwritten.

##### Expected Results
None of the files inside `/etc/origin/master/` should be overwrite.

##### Observed Results

`/etc/origin/master/ca.crt` is overwritten with the file from openshift_hosted_router_certificate.cafile

**Comment by DanyC97** [comment]
can we see your inventory file please?

**Comment by jkroepke** [comment]
@DanyC97 this should be the relevant part:

```
openshift_hosted_router_certificate:
  certfile: "{{ inventory_dir }}/../files/certificates/domain.de/domain.de.crt"
  keyfile: "{{ inventory_dir }}/../files/certificates/domain.de/domain.de.key"
  cafile: "{{ inventory_dir }}/../files/certificates/domain.de/ca.crt"
```
