### ISSUE TITLE
OKD 3.9 + Cisco ACI Install Error

### ISSUE THREAD

**Issue by CelsoSantos** [openshift/openshift-ansible#9565]
#### Description

Infrastructure: 
- 1 bastion
- 1 master
- 1 infra
- 1 node

Install method: Ansible (Advanced Install)

The install process never completes upon integrating with Cisco ACI (PR#8221).

##### Version

```
ansible --version:
ansible 2.6.2
  (...)
  python version = 2.7.5

git describe:
openshift-ansible-3.9.40-1-35-g337e91b
```

##### Steps To Reproduce
1. Merge PR#8221 into release-3.9 (locally)
2. Run `ansible-playbook -i /root/ansible/inventory.yaml /root/openshift-ansible/playbooks/deploy_cluster.yml -v`

##### Expected Results
Openshift Origin installs and integrates with Cisco ACI without issues

##### Observed Results
(Some) Pods regarding ACI keep CrashLooping, `router-1-deploy` Errors, `docker-registry-1-deploy` stuck on ContainerCreating.

On the master node the `aci-containers-host-xxx` runs fine without restarts, on Node and Infra nodes, it always Crashes.

Install process fails upon `TASK [openshift_hosted : Poll for Openshift pod deployment success]`

```
TASK [openshift_hosted : Poll for OpenShift pod deployment success] *************************************************************************************************************
FAILED - RETRYING: Poll for OpenShift pod deployment success (60 retries left).
...
FAILED - RETRYING: Poll for OpenShift pod deployment success (1 retries left).

failed: [ptstporiginmaster.stp.pt] (item=[{u'name': u'router', u'certificate': {u'keyfile': u'/etc/origin/master/openshift-router.key', u'certfile': u'/etc/origin/master/openshift-router.crt', u'cafile': u'/etc/origin/master/ca.crt'}, u'replicas': u'1', u'namespace': u'default', u'serviceaccount': u'router', u'stats_port': 1936, u'edits': [{u'action': u'put', u'key': u'spec.strategy.rollingParams.intervalSeconds', u'value': 1}, {u'action': u'put', u'key': u'spec.strategy.rollingParams.updatePeriodSeconds', u'value': 1}, {u'action': u'put', u'key': u'spec.strategy.activeDeadlineSeconds', u'value': 21600}], u'images': u'openshift/origin-${component}:${version}', u'selector': u'region=infra', u'ports': [u'80:80', u'443:443']}, {'_ansible_parsed': True, 'stderr_lines': [], u'cmd': [u'oc', u'get', u'deploymentconfig', u'router', u'--namespace', u'default', u'--config', u'/etc/origin/master/admin.kubeconfig', u'-o', u'jsonpath={ .status.latestVersion }'], u'end': u'2018-08-13 16:08:58.371020', '_ansible_no_log': False, u'stdout': u'1', 'failed': False, '_ansible_item_result': True, u'changed': True, 'item': {u'name': u'router', u'certificate': {u'certfile': u'/etc/origin/master/openshift-router.crt', u'keyfile': u'/etc/origin/master/openshift-router.key', u'cafile': u'/etc/origin/master/ca.crt'}, u'replicas': u'1', u'namespace': u'default', u'serviceaccount': u'router', u'selector': u'region=infra', u'edits': [{u'action': u'put', u'value': 1, u'key': u'spec.strategy.rollingParams.intervalSeconds'}, {u'action': u'put', u'value': 1, u'key': u'spec.strategy.rollingParams.updatePeriodSeconds'}, {u'action': u'put', u'value': 21600, u'key': u'spec.strategy.activeDeadlineSeconds'}], u'images': u'openshift/origin-${component}:${version}', u'stats_port': 1936, u'ports': [u'80:80', u'443:443']}, u'delta': u'0:00:00.237233', u'stderr': u'', u'rc': 0, u'invocation': {u'module_args': {u'creates': None, u'executable': None, u'_uses_shell': False, u'_raw_params': u"oc get deploymentconfig router --namespace default --config /etc/origin/master/admin.kubeconfig -o jsonpath='{ .status.latestVersion }'", u'removes': None, u'argv': None, u'warn': True, u'chdir': None, u'stdin': None}}, 'stdout_lines': [u'1'], u'start': u'2018-08-13 16:08:58.133787', '_ansible_ignore_errors': None, '_ansible_item_label': {u'name': u'router', u'certificate': {u'certfile': u'/etc/origin/master/openshift-router.crt', u'keyfile': u'/etc/origin/master/openshift-router.key', u'cafile': u'/etc/origin/master/ca.crt'}, u'replicas': u'1', u'namespace': u'default', u'serviceaccount': u'router', u'stats_port': 1936, u'edits': [{u'action': u'put', u'value': 1, u'key': u'spec.strategy.rollingParams.intervalSeconds'}, {u'action': u'put', u'value': 1, u'key': u'spec.strategy.rollingParams.updatePeriodSeconds'}, {u'action': u'put', u'value': 21600, u'key': u'spec.strategy.activeDeadlineSeconds'}], u'images': u'openshift/origin-${component}:${version}', u'selector': u'region=infra', u'ports': [u'80:80', u'443:443']}}]) => {"attempts": 60, "changed": true, "cmd": ["oc", "get", "replicationcontroller", "router-1", "--namespace", "default", "--config", "/etc/origin/master/admin.kubeconfig", "-o", "jsonpath={ .metadata.annotations.openshift\\.io/deployment\\.phase }"], "delta": "0:00:00.226742", "end": "2018-08-13 16:19:29.493914", "failed_when_result": true, "item": [{"certificate": {"cafile": "/etc/origin/master/ca.crt", "certfile": "/etc/origin/master/openshift-router.crt", "keyfile": "/etc/origin/master/openshift-router.key"}, "edits": [{"action": "put", "key": "spec.strategy.rollingParams.intervalSeconds", "value": 1}, {"action": "put", "key": "spec.strategy.rollingParams.updatePeriodSeconds", "value": 1}, {"action": "put", "key": "spec.strategy.activeDeadlineSeconds", "value": 21600}], "images": "openshift/origin-${component}:${version}", "name": "router", "namespace": "default", "ports": ["80:80", "443:443"], "replicas": "1", "selector": "region=infra", "serviceaccount": "router", "stats_port": 1936}, {"_ansible_ignore_errors": null, "_ansible_item_label": {"certificate": {"cafile": "/etc/origin/master/ca.crt", "certfile": "/etc/origin/master/openshift-router.crt", "keyfile": "/etc/origin/master/openshift-router.key"}, "edits": [{"action": "put", "key": "spec.strategy.rollingParams.intervalSeconds", "value": 1}, {"action": "put", "key": "spec.strategy.rollingParams.updatePeriodSeconds", "value": 1}, {"action": "put", "key": "spec.strategy.activeDeadlineSeconds", "value": 21600}], "images": "openshift/origin-${component}:${version}", "name": "router", "namespace": "default", "ports": ["80:80", "443:443"], "replicas": "1", "selector": "region=infra", "serviceaccount": "router", "stats_port": 1936}, "_ansible_item_result": true, "_ansible_no_log": false, "_ansible_parsed": true, "changed": true, "cmd": ["oc", "get", "deploymentconfig", "router", "--namespace", "default", "--config", "/etc/origin/master/admin.kubeconfig", "-o", "jsonpath={ .status.latestVersion }"], "delta": "0:00:00.237233", "end": "2018-08-13 16:08:58.371020", "failed": false, "invocation": {"module_args": {"_raw_params": "oc get deploymentconfig router --namespace default --config /etc/origin/master/admin.kubeconfig -o jsonpath='{ .status.latestVersion }'", "_uses_shell": false, "argv": null, "chdir": null, "creates": null, "executable": null, "removes": null, "stdin": null, "warn": true}}, "item": {"certificate": {"cafile": "/etc/origin/master/ca.crt", "certfile": "/etc/origin/master/openshift-router.crt", "keyfile": "/etc/origin/master/openshift-router.key"}, "edits": [{"action": "put", "key": "spec.strategy.rollingParams.intervalSeconds", "value": 1}, {"action": "put", "key": "spec.strategy.rollingParams.updatePeriodSeconds", "value": 1}, {"action": "put", "key": "spec.strategy.activeDeadlineSeconds", "value": 21600}], "images": "openshift/origin-${component}:${version}", "name": "router", "namespace": "default", "ports": ["80:80", "443:443"], "replicas": "1", "selector": "region=infra", "serviceaccount": "router", "stats_port": 1936}, "rc": 0, "start": "2018-08-13 16:08:58.133787", "stderr": "", "stderr_lines": [], "stdout": "1", "stdout_lines": ["1"]}], "rc": 0, "start": "2018-08-13 16:19:29.267172", "stderr": "", "stderr_lines": [], "stdout": "Failed", "stdout_lines": ["Failed"]}
        to retry, use: --limit @/root/openshift-ansible/playbooks/deploy_cluster.retry

PLAY RECAP **********************************************************************************************************************************************************************
localhost                  : ok=12   changed=0    unreachable=0    failed=0
ptstporigininfra.stp.pt    : ok=154  changed=59   unreachable=0    failed=0
ptstporiginmaster.stp.pt   : ok=507  changed=190  unreachable=0    failed=1
ptstporiginnode.stp.pt     : ok=154  changed=59   unreachable=0    failed=0


INSTALLER STATUS ****************************************************************************************************************************************************************
Initialization             : Complete (0:00:49)
Health Check               : Complete (0:00:38)
etcd Install               : Complete (0:02:30)
Master Install             : Complete (0:06:08)
Master Additional Install  : Complete (0:00:23)
Node Install               : Complete (0:09:40)
Hosted Install             : In Progress (0:14:31)
        This phase can be restarted by running: playbooks/openshift-hosted/config.yml



Failure summary:


  1. Hosts:    ptstporiginmaster.stp.pt
     Play:     Poll for hosted pod deployments
     Task:     Poll for OpenShift pod deployment success
     Message:  All items completed
```

##### Additional Information

```
cat /etc/redhat-release:
Red Hat Enterprise Linux Server release 7.5 (Maipo)
```

The inventory file & output for several `oc describe` is available in a gist: https://gist.github.com/CelsoSantos/8fc68092901e1fad7d3a9cb5e0059a00

**Comment by CelsoSantos** [comment]
Update on this issue:

I can now get all ACI pods to run successfully, but I had to add `openshift_no_proxy` to the inventory.
However, `router-1-deploy` and `docker-registry-1-deploy` keep erroring with the message `Get https://10.3.86.129:443/api/namespaces/default/replicationcontrollers/router-1: dial tcp 10.3.86.129:443: i/o timeout`

**Comment by camrossi** [comment]
Hi @CelsoSantos , 

Did you manage to get your cluster up and running ?
If you need help with the ACI CNI part I can probably help you out.

Let me know,
Cam

**Comment by CelsoSantos** [comment]
Hello @camrossi,

I did not (well, not with ACI, I have a cluster running with ovs-subnet for now) but because the Network Admin realised in the meantime that the ACI version installed on our testplant facility was 3.1, which according to the [compatibility matrix](https://www.cisco.com/c/dam/en/us/td/docs/Website/datacenter/aci/virtualization/matrix/virtmatrix.html) is not compatible with OKD 3.9.
He tried upgrading to 3.2 but hit some kind of a snag and it was not successful getting the ACI cluster with nodes giving out a message of `Data layer partially diverged` or something of the sorts.

That being said, the project is stopped for a couple of weeks now (people are on vacations) but we'll resume the efforts starting September 10, and I suspect that by then we will still see some errors, at which time (I suspect) we may need some help.

I'm keeping the issue open for now since it relates to an open PR that may or may not need to be updated.
In the meantime, if it makes sense to continue this discussion somewhere else, feel free to hit me up on my e-mail :)

Best Regards

**Comment by camrossi** [comment]
Hi Celso,

If you need help specific on ACI + OKD integration let me know and I can either help you or put you in touch with the right resources from Cisco. Surprise surprise I work there and I spend most of my time with ACI and Kubernetes/OpenShift :)

Cam

**Comment by CelsoSantos** [comment]
Hello @camrossi,

Well, we've resumed the efforts today to integrate OKD and ACI (which meanwhile has been successfully upgraded to v3.2(3i).

The plan is to integrate an existing OKD 3.9 installation which was installed with `redhat/openshift-ovs-subnet` initially, with ACI.

So the process we've been using to integrate ACI into OKD is described in the next steps:
1. Disabling `redhat/openshift-ovs-subnet` and enabling `cni` on the Master by editing `/etc/origin/master/master-config.yaml` and changing the property `networkPluginName` from `networkPluginName: redhat/openshift-ovs-subnet` to `networkPluginName: 'cni'`.
2. Restarting the services on the masters: `systemctl restart origin-master-api && systemctl restart origin-master-controllers`
3. Disable `redhat/openshift-ovs-subnet` and replace by `cni` on Infra and Nodes by editing `/etc/origin/node/node-config.yaml` 
4. Restarting the Infra and Node services: `systemctl restart origin-node`
5. Integrate ACI into OKD by applying the ACI-generated yaml file:
`oc apply -f /path/to/my-aci-containers.yaml` whose contents are the following:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: aci-containers-system
  labels:
    aci-containers-config-version: "1e9ad58e-a1cd-44d2-a7bf-188053d3029a"
    network-plugin: aci-containers
  annotations:
    openshift.io/node-selector: ''
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aci-containers-config
  namespace: aci-containers-system
  labels:
    aci-containers-config-version: "1e9ad58e-a1cd-44d2-a7bf-188053d3029a"
    network-plugin: aci-containers
data:
  controller-config: |-
    {
        "log-level": "info",
        "apic-hosts": [
            "10.1.20.141",
            "10.1.20.142",
            "10.1.20.143"
        ],
        "apic-username": "openshift",
        "apic-private-key-path": "/usr/local/etc/aci-cert/user.key",
        "apic-use-inst-tag": true,
        "aci-prefix": "openshift",
        "aci-vmm-type": "OpenShift",
        "aci-vmm-domain": "openshift",
        "aci-vmm-controller": "openshift",
        "aci-policy-tenant": "openshift",
        "require-netpol-annot": false,
        "aci-service-phys-dom": "openshift-pdom",
        "aci-service-encap": "vlan-1011",
        "aci-service-monitor-interval": 0,
        "aci-vrf-tenant": "openshift",
        "aci-l3out": "openshift_l3out",
        "aci-ext-networks": [
            "openshift_extepg"
        ],
        "aci-vrf": "openshift_vrf",
        "default-endpoint-group": {
            "policy-space": "openshift",
            "name": "kubernetes|kube-default"
        },
        "namespace-default-endpoint-group": {
            "aci-containers-system": {
                "policy-space": "openshift",
                "name": "kubernetes|kube-system"
            }
        },
        "service-ip-pool": [
            {
                "end": "10.3.86.126",
                "start": "10.3.86.66"
            }
        ],
        "static-service-ip-pool": [
            {
                "end": "10.3.86.62",
                "start": "10.3.86.2"
            }
        ],
        "allocate-service-ips": false,
        "pod-ip-pool": [
            {
                "end": "10.131.255.254",
                "start": "10.128.0.2"
            }
        ],
        "node-service-ip-pool": [
            {
                "end": "172.30.255.254",
                "start": "172.30.0.2"
            }
        ],
        "node-service-subnets": [
            "172.30.0.0/16"
        ]
    }
  host-agent-config: |-
    {
        "log-level": "info",
        "aci-vmm-type": "OpenShift",
        "aci-vmm-domain": "openshift",
        "aci-vmm-controller": "openshift",
        "aci-vrf": "openshift_vrf",
        "aci-vrf-tenant": "openshift",
        "service-vlan": 1011,
        "encap-type": "vxlan",
        "aci-infra-vlan": 3967,
        "cni-netconfig": [
            {
                "gateway": "10.128.0.1",
                "routes": [
                    {
                        "dst": "0.0.0.0/0",
                        "gw": "10.128.0.1"
                    }
                ],
                "subnet": "10.128.0.0/14"
            }
        ]
    }
  opflex-agent-config: |-
    {
        "log": {
            "level": "info"
        },
        "opflex": {
        }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: aci-user-cert
  namespace: aci-containers-system
  labels:
    aci-containers-config-version: "1e9ad58e-a1cd-44d2-a7bf-188053d3029a"
data:
  user.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUNkUUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQWw4d2dnSmJBZ0VBQW9HQkFLR1o3bUlUV1puZEhCbWsKbHVteHFyMy9Ic2doanlIaWtxakVGRlRwU0NJYW44VVRpZ2paYkhHNnM3WHFEaEhXUjhJcE5MVVY1Z2F6OTExQgp2bmEyMU1TaHN3cy9odDlsMTBodFdHSGdrc3p6MFVpKzA3S2Q4SkxhY0NqZzFmZDlxZGtncG1BdHVoMnF5SzVECm4yUndKVFdSblVNT3ptMTVDUW96RFVtbFBMalpBZ01CQUFFQ2dZQWMxY2l4ZTE1cmxBYWxsTGJROEVEVk1pYWQKODA4RTd0YllnbFJXYW1IU3BBbUtNdGhZaCtOUHo4NnRVUnc5bG95cldvcnJIUU0wZ3Z4S2lhYWdyREwrc24xdwpMWVhuL05LaExXczgxVWlZdHJ6azhPTGEzRGcveG9neXJtRXUya1Y1SGhhN1VDV1g3bDRseVVlVXN0SldoVzVCClRBd0QxMFdIaUcrUEEwbERBUUpCQU13WnhDSUx3TGpOcG45bVVXN0Fva2FjN2t2eDZxZ1cvWG9GYTBoL0NJdDEKYXpJYWpGOFJ5SGQzbGxhQ2NXSU8vZzZxaTNGNDFkaXNQdUV2dVdCNVBWRUNRUURLc1p0S0FhMFdKYjNHUk5wRwpBYXZsS3YyaUlPRE9QdVhWT3g4c3o2a0pVSzdUK1IrSWFOaDJrT0hTbzEwNFp3TFljSWkzVzBsYmw4dllqL0szCjZFRUpBa0J4dDgxNjlyZHJnRkhMWEJQMU5HbDJGSXdGVG9YakgrUWRMNVhGNzltdjhqMUd6bG4xd20vQ2VLUVEKRVYvaE5kOUNCcTNwREYyQit2NlI4MGhEUTJueEFrQkJYM0QzT0gwcnBIYUZpTlZoT003STljbWh6YnJUcWlPVQpWeUloNE1QaTlqdThzQitFYmxSS1FVWWtHbjVKWDZmaVNNRS9hZGpLQ3JZN0hZb3AyR1dKQWtCL2N5WWw3dUtFClliUFFRRUl3U2tiK0Z2NjdoT3BXWW94V0lTWitJMEQ4TFBDOTVCQWRSWVFKaUs1Sm96NXNMcUVxM3I0K0JGckwKRnl1QVlXNXVDWm9hCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  user.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI3RENDQVZVQ0FnUG9NQTBHQ1NxR1NJYjNEUUVCQlFVQU1ENHhDekFKQmdOVkJBWVRBbFZUTVJZd0ZBWUQKVlFRS0RBMURhWE5qYnlCVGVYTjBaVzF6TVJjd0ZRWURWUVFEREE1VmMyVnlJRzl3Wlc1emFHbG1kREFlRncweApPREE1TURZd05ESTVNamxhRncweU9EQTVNRE14TmpJNU1qbGFNRDR4Q3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEClZRUUtEQTFEYVhOamJ5QlRlWE4wWlcxek1SY3dGUVlEVlFRRERBNVZjMlZ5SUc5d1pXNXphR2xtZERDQm56QU4KQmdrcWhraUc5dzBCQVFFRkFBT0JqUUF3Z1lrQ2dZRUFvWm51WWhOWm1kMGNHYVNXNmJHcXZmOGV5Q0dQSWVLUwpxTVFVVk9sSUlocWZ4Uk9LQ05sc2NicXp0ZW9PRWRaSHdpazB0UlhtQnJQM1hVRytkcmJVeEtHekN6K0czMlhYClNHMVlZZUNTelBQUlNMN1RzcDN3a3Rwd0tPRFY5MzJwMlNDbVlDMjZIYXJJcmtPZlpIQWxOWkdkUXc3T2JYa0oKQ2pNTlNhVTh1TmtDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUVVGQUFPQmdRQk1ka2F2cWI0OXU1b3ZsaHhyRGpKUwp0TjdVYWM4eXBGRzB0Z2s5OEZwQkE2YWdlazN6ZTJkanNEQ0F3Mis5QjArTGZHekcwbllkT3Z6T2VQZkt0MlZxCkQyLzVvaVhsc21mNEx2RXZSMjh6Zy9HK2haVUQwNWo5bGgwNG1sNW10VFhVeVl4WnRpN3NkR0JRNWYzV1FuWDcKY2RoYnErRjNwZ2cxYVpuUllRN1p6Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-controller
  namespace: aci-containers-system
  labels:
    aci-containers-config-version: "1e9ad58e-a1cd-44d2-a7bf-188053d3029a"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-host-agent
  namespace: aci-containers-system
  labels:
    aci-containers-config-version: "1e9ad58e-a1cd-44d2-a7bf-188053d3029a"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "1e9ad58e-a1cd-44d2-a7bf-188053d3029a"
    network-plugin: aci-containers
  name: aci-containers:controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "apps"
  resources:
  - deployments
  - replicasets
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    aci-containers-config-version: "1e9ad58e-a1cd-44d2-a7bf-188053d3029a"
    network-plugin: aci-containers
  name: aci-containers:host-agent
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - endpoints
  - services
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:controller
  labels:
    aci-containers-config-version: "1e9ad58e-a1cd-44d2-a7bf-188053d3029a"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:controller
subjects:
- kind: ServiceAccount
  name: aci-containers-controller
  namespace: aci-containers-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aci-containers:host-agent
  labels:
    aci-containers-config-version: "1e9ad58e-a1cd-44d2-a7bf-188053d3029a"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:host-agent
subjects:
- kind: ServiceAccount
  name: aci-containers-host-agent
  namespace: aci-containers-system
---
kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: aci-containers-scc
  labels:
    aci-containers-config-version: "1e9ad58e-a1cd-44d2-a7bf-188053d3029a"
users:
  - system:serviceaccount:aci-containers-system:aci-containers-controller
  - system:serviceaccount:aci-containers-system:aci-containers-host-agent
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
defaultAddCapabilities: []
requiredDropCapabilities: []
readOnlyRootFilesystem: false
fsGroup:
  type: RunAsAny
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
seccompProfiles:
- '*'
volumes:
- '*'
priority: 100
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aci-containers-host
  namespace: aci-containers-system
  labels:
    aci-containers-config-version: "1e9ad58e-a1cd-44d2-a7bf-188053d3029a"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-host
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-host
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      initContainers:
        - name: cnideploy
          image: noiro/cnideploy:1.9r30
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          volumeMounts:
            - name: cni-bin
              mountPath: /mnt/cni-bin
      containers:
        - name: aci-containers-host
          image: noiro/aci-containers-host:1.9r30
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: cni-bin
              mountPath: /mnt/cni-bin
            - name: cni-conf
              mountPath: /mnt/cni-conf
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: host-config-volume
              mountPath: /usr/local/etc/aci-containers/
          livenessProbe:
            httpGet:
              path: /status
              port: 8090
        - name: opflex-agent
          image: noiro/opflex:1.9r35
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-hostconfig-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/base-conf.d
            - name: opflex-config-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/conf.d
        - name: mcast-daemon
          image: noiro/opflex:1.9r35
          command: ["/bin/sh"]
          args: ["/usr/local/bin/launch-mcastdaemon.sh"]
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
      restartPolicy: Always
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt
        - name: cni-conf
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: host-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: host-agent-config
                path: host-agent.conf
        - name: opflex-hostconfig-volume
          emptyDir:
            medium: Memory
        - name: opflex-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: opflex-agent-config
                path: local.conf
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aci-containers-openvswitch
  namespace: aci-containers-system
  labels:
    aci-containers-config-version: "1e9ad58e-a1cd-44d2-a7bf-188053d3029a"
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: aci-containers-openvswitch
      network-plugin: aci-containers
  template:
    metadata:
      labels:
        name: aci-containers-openvswitch
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-openvswitch
          image: noiro/openvswitch:1.7r24
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
                - SYS_NICE
                - IPC_LOCK
          env:
            - name: OVS_RUNDIR
              value: /usr/local/var/run/openvswitch
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: hostetc
              mountPath: /usr/local/etc
            - name: hostmodules
              mountPath: /lib/modules
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/liveness-ovs.sh
      restartPolicy: Always
      volumes:
        - name: hostetc
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: hostmodules
          hostPath:
            path: /lib/modules
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aci-containers-controller
  namespace: aci-containers-system
  labels:
    aci-containers-config-version: "1e9ad58e-a1cd-44d2-a7bf-188053d3029a"
    network-plugin: aci-containers
    name: aci-containers-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: aci-containers-controller
      network-plugin: aci-containers
  template:
    metadata:
      name: aci-containers-controller
      namespace: aci-containers-system
      labels:
        name: aci-containers-controller
        network-plugin: aci-containers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      serviceAccountName: aci-containers-controller
      tolerations:
        - key: CriticalAddonsOnly
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: aci-containers-controller
          image: noiro/aci-containers-controller:1.9r30
          imagePullPolicy: Always
          volumeMounts:
            - name: controller-config-volume
              mountPath: /usr/local/etc/aci-containers/
            - name: aci-user-cert-volume
              mountPath: /usr/local/etc/aci-cert/
          livenessProbe:
            httpGet:
              path: /status
              port: 8091
      volumes:
        - name: aci-user-cert-volume
          secret:
            secretName: aci-user-cert
        - name: controller-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: controller-config
                path: controller.conf
```

6. Once ACI pods are successfully created, run the following commands (according to the ACI manual):
`oc delete svc router`, `oc delete dc router` and `oc adm router --service-account=router --host-network=false`
7. At this point, there is a `router-1-deploy` pod which goes into an error state, whose logs only state: `error: couldn't get deployment router-1: Get https://172.30.0.1:443/api/v1/namespaces/default/replicationcontrollers/router-1: dial tcp 172.30.0.1:443: getsockopt: no route to host`

After this, nothing seems to work. The question is, what are we doing wrong, if anything, because from my (limited) understanding of ACI, these seem to be the correct steps. 
Is this information enough?
How can I provide you with more information/configurations if required?

Best Regards.
