### ISSUE TITLE
GlusterFS not native, uninstall removes too much

### ISSUE THREAD

**Issue by MansM** [openshift/openshift-ansible#9590]
#### Description

When testing install for gluster we had to uninstall and it removed too much from the gluster nodes
we  are using openshift_storage_glusterfs_is_native: False

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `2.5.x (Tower)`

If you're operating from a **git clone**:

* The output of `release-3.9 & release3-10 (others probably as well)`

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
1. install gluster with native = false
2. uninstall glusterfs playbook with native=false

##### Expected Results
still working gluster cluster

```
 failed to open logfile /var/log/glusterfs/cli.log"
```

https://github.com/openshift/openshift-ansible/blob/release-3.9/roles/openshift_storage_glusterfs/tasks/glusterfs_uninstall.yml#L61 should have something like
```
- name: Delete pre-existing additional GlusterFS config
  file:
    path: /etc/glusterfs
    state: absent
  delegate_to: "{{ item }}"
  with_items: "{{ glusterfs_nodes | default([]) }}"
  when: "{{ openshift_storage_glusterfs_is_native }}" <-- new
```

this is not the only task that should be changed
