### ISSUE TITLE
Lack of info  configuring Custom Certificates for the Web Console

### ISSUE THREAD

**Issue by DanyC97** [openshift/openshift-ansible#9710]
For the last few days i was trying on a Origin/ ansible v3.7 to create and deploy custom certification on existing cluster so i can get rid of the annoying browser warning.

So far it feels like a never ending process due to lack of consistent documentation ...

What i've done

* after many trial and errors i was made [aware](https://github.com/openshift/openshift-ansible/pull/4920#issuecomment-414442885) by @abutcher about a very good guide which explain how to create the certs for private/ internal domains
* copied `openshift-master.private.dani.com.cert.pem` & `openshift-master.private.dani.com.key.pem` to each master under `/etc/origin/master/`
* manually set the `master-config.yaml` as below and restarted the `origin-master-api.service` & `origin-master-controller.service`

```
assetConfig:
  extensionScripts:
  - /etc/origin/master/openshift-ansible-catalog-console.js
  logoutURL: ''
  masterPublicURL: https://openshift-master.private.dani.com:8443
  publicURL: https://openshift-master.private.dani.com:8443/console/
  servingInfo:
    bindAddress: 0.0.0.0:8443
    bindNetwork: tcp4
    certFile: master.server.crt
    clientCA: ''
    keyFile: master.server.key
    maxRequestsInFlight: 0
    requestTimeoutSeconds: 0
    namedCertificates:
      - certFile: openshift-master.private.dani.com.cert.pem
        keyFile: openshift-master.private.dani.com.key.pem
        names:
          - "openshift-master.private.dani.com"
...
oauthConfig:
  masterURL: https://openshift-master-int.private.dani.com:8443
```
however accessing the web console is still retrieving the default self-signed master certificate. Even when doing `openssl s_client -showcerts -connect openshift-master.private.dani.com:8443 -servername openshift-master.private.dani.com` i get same result

**Findings**:

thinking that i've done something wrong, i decided to try the automation thinking there is one ... .wrong decision which cost me 1 day!

* 3.7 [docs](https://docs.openshift.com/container-platform/3.7/install_config/certificate_customization.html#configuring-custom-certificates) (same info is in 3.10) mention how to set custom certs for web console 
* you would think for an existing cluster you would need to redeploy the certs as mentioned [here](https://docs.openshift.com/container-platform/3.7/install_config/redeploying_certificates.html#redeploying-master-certificates) however what is not being mention at all is the info i came across in [this BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1553102#c2)
   * and if you come across https://github.com/openshift/openshift-docs/issues/7495#issuecomment-364319969 you would think that to automate the whole process (including the adding the right info into `master-config.yaml`) you must run `edeploy-master-certificates.yml` ... wrong !
* even for a green/ fresh deployment, setting http://v1.uncontained.io/playbooks/installation/custom_certificates.html#master-api-certificate it won't be enough since the below snippet is not automated 

```
namedCertificates:
      - certFile: openshift-master.private.dani.com.cert.pem
        keyFile: openshift-master.private.dani.com.key.pem
        names:
          - "openshift-master.private.dani.com"

```

@abutcher as the contributor of the named_certificate role, any chance you can share more info around how the internals works:

1) for the new custom certs created by following [this guide](https://jamielinux.com/docs/openssl-certificate-authority/index.html) do i need to drop the intermediate CA ? 
2) since `cafile` is not used, how does the custom certs know/ works with the selg-signed generated internal certs ? 
3) the `certFile` value does it needs to be a chain file ? - see [here](https://jamielinux.com/docs/openssl-certificate-authority/create-the-intermediate-pair.html#create-the-certificate-chain-file)

**Comment by DanyC97** [comment]
@sdodson @vrutkovs @michaelgugino fyi 
cc @vikram-redhat in case he has any interest to improve the docs with some notes once we get to the bottom of it

**Comment by DanyC97** [comment]
@abutcher quick update for you:

1) i've created a full chain between `intermediate.cert.pem` & `openshift-master.private.dani.com.cert.pem` and set to `certFile` in `/etc/origin/master-config.yaml` but no dice

any feedback much appreciated.

_Note_: you can find me on irc too if that is easier for you

**Comment by DanyC97** [comment]
@ikke-t you've done some research on this, any chance you might be able to help above ?

**Comment by abutcher** [comment]
@DanyC97 Hey sorry for the lack of update.

The file pointed to by `namedCertificates.certFile` should contain the certificate, intermediate CA (if you are using an intermediate CA as the guide I shared does) and the root CA certificate, in that order. Note that an intermediate CA is not required but must be added to the `certFile` if you have one and the `certFile` would be a chain containing cert -> int CA -> root CA.

The root CA certificate then must be added to the browser/system trust in order to not receive a warning from the browser unless the root CA would already be trusted by your browser/system which would be the case with letsencrypt, digicert, etc.

Another pit trap with named certificates is that the external and internal cluster names must be different. This is because we intend to serve your cert for `openshift-master.private.dani.com` on the public endpoint only and serve the self signed cluster certificates internally. If the cluster were served your named certificate when speaking to the internal cluster hostname then openshift would not trust it.

**Comment by DanyC97** [comment]
@abutcher thank you for your reply, i'll give it a go on the chain file formed by cert -> int CA -> root CA.

I already done for cert -> int CA but as mentioned that didn't work.

**Comment by ikke-t** [comment]
Good luck with it. I remember it like abutcher wrote. I have never done it since I dag into it. So I don't know if it has changed.

**Comment by DanyC97** [comment]
@abutcher here is the update:

* went ahead and created the full chain `cat openshift-master.private.dani.com.cert.pem ca-chain.cert.pem > fullchain.pem`
* set `certFile: named_certificates/fullchain.pem`
* restarted `origin-master-api.service`
* imported into my browser `ca-chain.cert.pem` (the file was created as per [instruction](https://jamielinux.com/docs/openssl-certificate-authority/create-the-intermediate-pair.html#create-the-certificate-chain-file)) 

On the browser went and loaded the web console at `https://openshift-master.private.dani.com:8443` and i get the same thing where the certificate presented to the browser still has the `CN: <master IP>` instead of the new certs which is associated with `namedCertificates`.

What am i missing?

Note i have not run any redeploy-* playbooks

**Comment by DanyC97** [comment]
@abutcher even making the change as below made no difference ... so i'm v confused now

```
assetConfig:
  extensionScripts:
  - /etc/origin/master/openshift-ansible-catalog-console.js
  logoutURL: ''
  masterPublicURL: https://openshift-master.private.dani.com:8443
  publicURL: https://openshift-master.private.dani.com:8443/console/
  servingInfo:
    bindAddress: 0.0.0.0:8443
    bindNetwork: tcp4
    certFile: named_certificates/fullchain.pem
    clientCA: ''
    keyFile: named_certificates/openshift-master.private.dani.com.key.pem
    maxRequestsInFlight: 0
    requestTimeoutSeconds: 0
    namedCertificates:
      - certFile: named_certificates/fullchain.pem
        keyFile: named_certificates/openshift-master.private.dani.com.key.pem
        names:
          - "openshift-master.private.dani.com"
...
oauthConfig:
  masterURL: https://openshift-master-int.private.dani.com:8443

```

**Comment by abutcher** [comment]
@DanyC97 Sorry for not noticing this in the original post but the `namedCertificates` config should be placed under the top level `servingInfo` rather than `assetConfig.servingInfo`.  Here's where we configure `namedCertificates` in the master config template https://github.com/openshift/openshift-ansible/blob/release-3.7/roles/openshift_master/templates/master.yaml.v1.j2#L256-L273.

**Comment by DanyC97** [comment]
cool, much thanks @abutcher !!

If anyone will ever come to this issue, the final setup looked like below following the steps [here](https://github.com/openshift/openshift-ansible/issues/9710#issuecomment-415195856)
```
assetConfig:
  extensionScripts:
  - /etc/origin/master/openshift-ansible-catalog-console.js
  logoutURL: ''
  masterPublicURL: https://openshift-master.private.dani.com:8443
  publicURL: https://openshift-master.private.dani.com:8443/console/
  servingInfo:
    bindAddress: 0.0.0.0:8443
    bindNetwork: tcp4
    certFile: master.server.crt
    clientCA: ''
    keyFile: master.server.key
    maxRequestsInFlight: 0
    requestTimeoutSeconds: 0

...
oauthConfig:
  masterURL: https://openshift-master-int.private.dani.com:8443
....

servingInfo:
  bindAddress: 0.0.0.0:8443
  bindNetwork: tcp4
  certFile: master.server.crt
  clientCA: ca.crt
  keyFile: master.server.key
  maxRequestsInFlight: 1000
  requestTimeoutSeconds: 3600
  namedCertificates:
  - certFile: named_certificates/fullchain.pem
    keyFile: named_certificates/openshift-master.private.dani.com.key.pem
    names:
      - "openshift-master.private.dani.com"


```
I'll send you a docs PR to add a note about the 

> namedCertificates.certFile should contain the certificate, intermediate CA (if you are using an intermediate CA as the guide I shared does) and the root CA certificate, in that order. Note that an intermediate CA is not required but must be added to the certFile if you have one and the certFile would be a chain containing cert -> int CA -> root CA.

> The root CA certificate then must be added to the browser/system trust in order to not receive a warning from the browser unless the root CA would already be trusted by your browser/system which would be the case with letsencrypt, digicert, etc.
