### ISSUE TITLE
cockpit ui deployment fails after IMAGE refactor in 03c04b0b

### ISSUE THREAD

**Issue by nirik** [openshift/openshift-ansible#9808]
#### Description

Provide a brief description of your issue here. For example:

Doing a byo deployment, the playbook stops at: 

[cockpit-ui : Deploy registry-console] ************************************", "Tuesday 28 August 2018  19:20:32 +0000
 (0:00:02.145)       0:06:39.369 ******** ", "fatal: [os-master01.stg.phx2.fedoraproject.org]: FAILED! => {\"changed\":
 true, \"cmd\": [\"oc\", \"new-app\", \"--template=registry-console\", \"-p\", \"IMAGE_NAME=registry.access.redhat.com/
openshift3/registry-console:v3.10\", \"-p\", \"OPENSHIFT_OAUTH_PROVIDER_URL=https://os.stg.fedoraproject.org:443\", \"-
p\", \"REGISTRY_HOST=docker-registry-default.app.os.stg.fedoraproject.org\", \"-p\", \"COCKPIT_KUBE_URL=https://registr
y-console-default.app.os.stg.fedoraproject.org\", \"--config=/tmp/openshift-ansible-lL885Zg/admin.kubeconfig\", \"-n\",
 \"default\"], \"delta\": \"0:00:00.129185\", \"end\": \"2018-08-28 19:20:32.944702\", \"failed_when_result\": true, \"
msg\": \"non-zero return code\", \"rc\": 1, \"start\": \"2018-08-28 19:20:32.815517\", \"stderr\": \"error: unexpected 
parameter name \\\"IMAGE_NAME\\\"\", \"stderr_lines\": [\"error: unexpected parameter name \\\"IMAGE_NAME\\\"\"], \"std
out\": \"\", \"stdout_lines\": []}", "", "PLAY RECAP ******************************************************************
***", "localhost                  : ok=1

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

ansible 2.6.3
  config file = /root/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
openshift-ansible-3.10.38-1
```

##### Steps To Reproduce
1. run deployment with cockpit enabled.
2. crash

##### Expected Results
Describe what you expected to happen.

```
Example command and output or error messages
```

##### Observed Results
Describe what is actually happening.

```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
rhel 7 hosts. 
```

in 03c04b0baaf5b622068d6726dfe5b96d31e6fa05 the registry images parameters were split, but the call to make the app is still using just IMAGE_NAME.

failing call: 

oc new-app --template=registry-console -p IMAGE_NAME="registry.access.redhat.com/openshift3/
registry-console:v3.10" -p OPENSHIFT_OAUTH_PROVIDER_URL=https://os.stg.fedoraproject.org:443 -p REGISTRY_HOST=docker-re
gistry-default.app.os.stg.fedoraproject.org -p COCKPIT_KUBE_URL=https://registry-console-default.app.os.stg.fedoraproje
ct.org --config=/tmp/openshift-ansible-lL885Zg/admin.kubeconfig -n default
error: unexpected parameter name "IMAGE_NAME"

Needs to be adjusted to: 

oc new-app --template=registry-console -p IMAGE_PREFIX=registry.access.redhat.com/openshift3
/ -p IMAGE_BASENAME=registry-console -p IMAGE_VERSION=v3.10 -p OPENSHIFT_OAUTH_PROVIDER_URL=https://os.stg.fedoraprojec
t.org:443 -p REGISTRY_HOST=docker-registry-default.app.os.stg.fedoraproject.org -p COCKPIT_KUBE_URL=https://registry-co
nsole-default.app.os.stg.fedoraproject.org --config=/tmp/openshift-ansible-lL885Zg/admin.kubeconfig -n default

**Comment by vrutkovs** [comment]
Is this still an issue in latest  `release-3.10` branch or `openshift-ansible-3.10.41-1`? If its still reproducibl please attach the inventory and output of `ansible-playbook -vv` runs

**Comment by varesa** [comment]
I also ran into this on release-3.10, rev e10ee8d4a75e55ebb1041aa7fdb6d8945c4c1fef.

Error:
```
TASK [cockpit-ui : Deploy registry-console] ***********************************************************************************************************************************************************************************************************************************************************************************
Monday 03 September 2018  16:19:59 +0300 (0:00:03.261)       0:12:24.473 ******                                                                                                                                                                                                                                               
fatal: [openshift-master1]: FAILED! => {"changed": true, "cmd": ["oc", "new-app", "--template=registry-console", "-p", "IMAGE_NAME=docker.io/cockpit/kubernetes:latest", "-p", "OPENSHIFT_OAUTH_PROVIDER_URL=https://openshift-master.tre.esav.fi:8443", "-p", "REGISTRY_HOST=docker-registry-default.ocp.tre.esav.fi", "-p", "
COCKPIT_KUBE_URL=https://registry-console-default.ocp.tre.esav.fi", "--config=/tmp/openshift-ansible-3dn8YPU/admin.kubeconfig", "-n", "default"], "delta": "0:00:00.339147", "end": "2018-09-03 16:20:00.425948", "failed": true, "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2018-09-03 16:2
0:00.086801", "stderr": "error: unexpected parameter name \"IMAGE_NAME\"", "stderr_lines": ["error: unexpected parameter name \"IMAGE_NAME\""], "stdout": "", "stdout_lines": []}
```
The template that's in the temp directory has the parameter:
```
openshift-master1 openshift-ansible-repo (release-3.10) # cat /tmp/openshift-ansible-3dn8YPU/registry-console.yaml | grep parameters -A100
parameters:
  - description: 'Specify fully qualified image name and version; e.g. for "registry.access.redhat.com/openshift3/registry-console:v3.11"'
    name: IMAGE_NAME
    value: "openshift3/registry-console:latest"
  - description: "The public URL for the Openshift OAuth Provider, e.g. https://openshift.example.com:8443"
    name: OPENSHIFT_OAUTH_PROVIDER_URL
    required: true
  - description: "The registry console URL. This should be created beforehand using 'oc create route passthrough --service registry-console --port registry-console -n default', e.g. https://registry-console-default.example.com"
    name: COCKPIT_KUBE_URL
    required: true
  - description: "Oauth client secret"
    name: OPENSHIFT_OAUTH_CLIENT_SECRET
    from: "user[a-zA-Z0-9]{64}"
    generate: expression
  - description: "Oauth client id"
    name: OPENSHIFT_OAUTH_CLIENT_ID
    value: "cockpit-oauth-client"
  - description: "The integrated registry hostname exposed via route, e.g. registry.example.com"
    name: REGISTRY_HOST
    required: true
```

However the template in the namespace openshift is different:
```
openshift-master1 openshift-ansible-repo (release-3.10) # oc export template registry-console | grep parameters: -A100
Command "export" is deprecated, use the oc get --export
parameters:
- description: Specify "registry/namespace" prefix for container image; e.g. for "registry.example.com/cockpit/kubernetes:latest",
    set prefix "registry.example.com/cockpit/"
  name: IMAGE_PREFIX
  value: cockpit/
- description: Specify component name for container image; e.g. for "registry.example.com/cockpit/kubernetes:latest",
    use base name "kubernetes"
  name: IMAGE_BASENAME
  value: kubernetes
- description: Specify image version; e.g. for "cockpit/kubernetes:latest", set version
    "latest"
  name: IMAGE_VERSION
  value: latest
- description: The public URL for the Openshift OAuth Provider, e.g. https://openshift.example.com:8443
  name: OPENSHIFT_OAUTH_PROVIDER_URL
  required: true
- description: The registry console URL. This should be created beforehand using 'oc
    create route passthrough --service registry-console --port registry-console -n
    default', e.g. https://registry-console-default.example.com
  name: COCKPIT_KUBE_URL
  required: true
- description: Oauth client secret
  from: user[a-zA-Z0-9]{64}
  generate: expression
  name: OPENSHIFT_OAUTH_CLIENT_SECRET
- description: Oauth client id
  name: OPENSHIFT_OAUTH_CLIENT_ID
  value: cockpit-oauth-client
- description: The integrated registry hostname exposed via route, e.g. registry.example.com
  name: REGISTRY_HOST
  required: true

```
